### ISSUE TITLE
consider rewriting URLs instead of copying resources

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#101]
The compiler currently copies resources that are mentioned in the HTML into the output folder (see [source][1]). Another option is to rewrite URLs in the output HTML to point to the original resources.

There are some pros and cons for each.

In favor of coping:
* the out folder is self contained and you can practically "ship it".
* the server can serve contents from the out folder alone.

In favor of rewriting:
* transitive locations don't need to be copied (e.g. what if a .css has a background image  url?)
* resources don't need to be parsed (e.g. same example as above)

[1]:https://github.com/dart-lang/dev_compiler/blob/1970680381da640eaa1b69651b6beac6fe7dcecd/lib/src/dependency_graph.dart#L190

**Comment by jmesserly** [comment]
I think this will be obsolete when https://github.com/dart-lang/dev_compiler/issues/277 is addressed
