### ISSUE TITLE
use same JS annotations as package:js

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#102]
e.g. JsName
https://github.com/dart-lang/js-interop/blob/master/lib/src/metadata.dart

@a14n is also looking into improving package:js, and using source_gen to support them

**Comment by jmesserly** [comment]
fyi @jacob314

**Comment by a14n** [comment]
See my [source_gen branch](https://github.com/a14n/js-interop/blob/source_gen/lib/js.dart#L32-L45).

```dart
/// A metadata annotation that allows to customize the name used for method call
/// or attribute access on the javascript side.
class JsName {
  final String name;
  const JsName(this.name);
}

class _Anonymous {
  const _Anonymous();
}

/// This means that the Js object is a anonymous js object. That is it is
/// created with `new Object()`.
const _Anonymous anonymous = const _Anonymous();
```

and a sample : https://github.com/a14n/js-interop/blob/source_gen/example/gmaps/map-simple/page.dart

**Comment by jmesserly** [comment]
@jacob314 are you looking into this one?

**Comment by jacob314** [comment]
Taking a look now

**Comment by jmesserly** [comment]
fixed a while ago YAY
