### ISSUE TITLE
dart_runtime.dart is out-of-date

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#117]
The type rules in dart_runtime.dart are out-of-date wrt Function handling.  We should either fix and add the corresponding tests to the main test runner or delete.

**Comment by vsmenon** [comment]
Cl pending for this:

https://codereview.chromium.org/1043323002/

**Comment by vsmenon** [comment]
Landed.

**Comment by jmesserly** [comment]
filed https://github.com/dart-lang/dev_compiler/issues/125 for the JS side
