### ISSUE TITLE
Assignment operator is ignored

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/dev_compiler#118]
This Dart code:
// C is of type List<int>
if (C[j] == null) C[j] = 2;
else C[j] *= 2;

Is compiled into:
if (C.get(j) == null)
    C.set(j, 2);
else
    C.set(j, 2);

**Comment by frankpepermans** [comment]
Same happens with foo |= 2 for example, it would become foo = 2 in the generated ES6

**Comment by vsmenon** [comment]
It looks like we're ignoring the node.operator in js_codegen.dart / visitAssignmentExpression.  In this case, we'd need to lower compound assignments.

**Comment by jmesserly** [comment]
found a related bug in prefix/postfix, going to roll that into a fix here

**Comment by jmesserly** [comment]
fixed in https://github.com/dart-lang/dev_compiler/commit/0c480a7d4b518d5f2ce5d3afbe706937299a0ff2
