### ISSUE TITLE
categorize analyzer errors for ddc

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#120]
we need to go over each error message and categorize it as error/warning/info in DDC:
- wrong inferred const type will likely be an error
- unused import or unused private member will likely be info or fine
...

**Comment by jmesserly** [comment]
we're likely going to run with warning as error turned on in Analyzer.
I think we need this turned on for soundness.

**Comment by jmesserly** [comment]
I think @munificent is looking at this.

**Comment by jmesserly** [comment]
(dropping soundness tag as we are defensive right now, and treat all warnings as errors, for better or worse)

**Comment by jmesserly** [comment]
this has been done 🎉 
Landed in Analyzer in https://codereview.chromium.org/2108823002/
