### ISSUE TITLE
upgrade analyzer

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#124]
v24.1 has a nice fix for isPotentiallyMutated*, and maybe some other things?

I think we are still forked (`url: https://github.com/dart-lang/ddc_analyzer.git`) wonder if it's time to unfork and what the best route is?

**Comment by sigmundch** [comment]
it should be totally possible to upstream the changes we needed for inference (they were a few non controversial changes to make some APIs public). I'm happy to help with this when I return if you like.

**Comment by sigmundch** [comment]
This is in progress:
- [x] our ddc_analyzer has the latest changes from 0.24.1
- [ ] [CL][1] in progress to upgrade dev_compiler to use the latest version in ddc_analyzer
- [ ] [CL][2] in progress to upstream our changes back to analyzer.

[1]: https://codereview.chromium.org/1054343004/
[2]: https://codereview.chromium.org/1067903002/

**Comment by sigmundch** [comment]
as of 29fb79e7356fa22fe2e1cae92b283a41aa6f8905 we are using analyzer 0.24.3

For reference, I didn't include here links to the CLs that updated ddc_analyzer. The process of doing that requires a few steps, but they are pretty mechanical (see these [notes](https://github.com/dart-lang/ddc_analyzer/wiki) for details).
