### ISSUE TITLE
Test framework for runtime tests / generated code tests

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#128]
We currently need to run runtime_tests.js by hand in Chrome Canary with the appropriate flags.  It's not part of our automated test framework.

It looks like karma could automate this for us.  Karma appears to already support Canary (with custom flags), mocha, and travis.  Angular2 tests use Karma+Canary.

@kevmoo : any thoughts on this?

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1243503007/ -- the CL is about async support, but it extends your test pattern to run a bunch of language tests on Karma.

The main thing we're missing is a proper Karma plugin that runs DDC automatically in response to a watcher... Instead test/codegen_test is the "build" script, which is a bit odd.

**Comment by jmesserly** [comment]
this is fixed now
