### ISSUE TITLE
missing checks on calls to methods with dynamic arguments

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#129]
I think for function types:
```dart
typedef Func(x);
Func f = foo;
foo(String x) {
  print('I hope this is a string: ' + x);
}
main() {
  f(123); // needs an argument type check at runtime
  // like this psuedocode: f(123 as f.$arg0type); 
}
```
Is this true for methods?
```dart
abstract class Base {
  foo(x);
}
class Derived extends Base {
  // is this overload allowed?
  // if so, do we generate a type check in the method body?
  foo(String x) {
    print('I hope this is a string: ' + x);
  }
}
Base b;
main() {
  b.foo(123); // or does this need an argument check, like the "f" case above?
}
```

**Comment by vsmenon** [comment]
If we do support this form of overloading, we probably should do a callee side check as you suggest.

So, either way, no caller side check / dinvoke in this case.

**Comment by jmesserly** [comment]
update subject. To answer my original question above: we currently accept both examples statically, and generate unsound code (it is missing checks in both examples). Changing this to bug.

Not sure how we intend to solve this? CC @leafpetersen 

For functions: I guess we have to generate a caller side check (`dcall` would be easiest way to get it), because up front we have no idea if a function will be assigned to one of these dynamic-ish function types.

For methods: probably the same solution? If we generate it callee side, we'd end up checking twice in the case of a tear off. And there'd be no way to ever skip the call, even if you know the static type is the derived class.

If so, we may want to warn/hint people about methods that have `dynamic` as the argument type, since calls to it will be slow/ugly?

**Comment by leafpetersen** [comment]
In both examples, we have an expression of "fuzzy" type being applied, which implies that there should be a dcall/dinvoke used at the call site.  I thought we were handling this already, but apparently this is being missed here?

**Comment by jmesserly** [comment]
exactly, it's not in the generated output. Perhaps a simple fix to isDynamicCall (called from https://github.com/dart-lang/dev_compiler/blob/master/lib/src/checker/checker.dart#L545)

**Comment by leafpetersen** [comment]
I don't understand why isDynamicCall isn't already doing the right thing here:

https://github.com/dart-lang/dev_compiler/blob/master/lib/src/checker/rules.dart#L494

**Comment by vsmenon** [comment]
The first example is emitting a dcall with tip when I run it.

The second one is not.  It should either emit a dcall/dsend or statically reject.

**Comment by jmesserly** [comment]
ah, yes, as @vsmenon notes, it's only methods are a problem. I think it's the `if (call is SimpleIdentifier) {` block above.

**Comment by vsmenon** [comment]
(Note - in the second example, Derived should extend Base.)

We need to decide if
(a) We should statically reject the second example (as we would if Base.foo took Object), or
(b) Always use dcall on Base.foo.

I'd lean toward (b).

**Comment by jmesserly** [comment]
ah, I see ... yeah we could do (a) ... if I write `Object` in Base.foo I get:
```
severe: line 7, column 3 of ../../../scratch/test.dart: [InvalidMethodOverride] Invalid override. The type of Derived.foo ((String) → dynamic) is not a subtype of Base.foo ((Object) → dynamic).
  foo(String x) {
  ^^^^^^^^^^^^^^^^
```

**Comment by leafpetersen** [comment]
I believe that this is fixed.  We generate a dcall in the first case, and reject the override in the second.
