### ISSUE TITLE
accept anything with a .iterator in for-in loops

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#130]
From spec 2nd edition, section 17.6.2:
> A for statement of the form `for (finalConstVarOrType? id in e) s` is equivalent to the following code:
```dart
var n0 = e.iterator;
while (n0.moveNext()) {
  finalConstVarOrType? id = n0.current;
  s
}
```
where n0 is an identifier that does not occur anywhere in the program. Note that in fact, using a const variable would give rise to a compile time error since n0.current is not a constant expression.

It seems that `e` doesn't have to be an `Iterable`, instead we should do a structural check that there is an `iterator` on the type of `e`.

Long term - It might be valuable to request a change in the spec to encode this information in a type, for example, introduce `class IteratorProducer<T> { Iterator<T> get iterator; }` and require that `e` implements this type.

**Comment by jmesserly** [comment]
we'll need a fix to JS codegen too, though it's doable. Currently we inject the [Symbol.iterator] adapter method directly onto core.Iterable, instead we should do this any time we see the Dart "iterator" getter.

**Comment by jmesserly** [comment]
(and pull the adapter application into a method, so we aren't duplicating the logic. Here's the current adapter: https://github.com/dart-lang/dev_compiler/blob/0c480a7d4b518d5f2ce5d3afbe706937299a0ff2/lib/runtime/dart/core.js#L1111)

**Comment by vsmenon** [comment]
Hitting this issue at runtime on MappedIterable - which implements Iterable, but does not extend it.

**Comment by jmesserly** [comment]
hah, nice. Shouldn't be too hard to fix this. On it.

**Comment by jmesserly** [comment]
it was worse than I thought, but this gets it pretty far along: https://codereview.chromium.org/1126713002/
