### ISSUE TITLE
Use before define from variables to classes.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#131]
This code (from Angular):

```dart
/// Marker for an uninitialized value.
const UNINITIALIZED = const _Uninitialized();
class _Uninitialized { const _Uninitialized(); }
```

is causing a runtime error on generated code as the use is before the define:
```javascript
  let UNINITIALIZED = new _Uninitialized();
  class _Uninitialized extends core.Object {
    _Uninitialized() {
    }
  }
```

**Comment by jmesserly** [comment]
this is basically https://github.com/dart-lang/dev_compiler/issues/29, consts aren't implemented

**Comment by jmesserly** [comment]
update, getting closer on this. The new design unifies all use-before-define concepts. It folds in the existing _lazyClass checks, without requiring duplication. It will also allow constants in method bodies to be hoisted out to the top-level (as an optimization, but also what a human would write in JS code).

**Comment by jmesserly** [comment]
there's essentially two mechanisms:
* ability to qualify identifiers later. In other words, `exports.someName` vs `someName` ... we don't know if we need this at first. The same mechanism should help ES6 module stuff too. (Basically, having to qualify names all the time is a drag.)
* ability to reorder all top level "module items" on-the-fly. It still defaults to source order, but things can be filled in at different places if needed.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1133593004/ ... finally :)
