### ISSUE TITLE
start server faster

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#133]
If I switch to terminal and kill server, then restart it, then go back to browser and refresh, the first load will usually fail to connect, even though the browser has printed:
```
fine: Serving sunflower.html at http://localhost:8080/
```
by that point. Not entirely sure what's going on, but ideally the load would spin for a second or so while the server gets going.

**Comment by sigmundch** [comment]
oh, we might be printing that message a bit too early. I think the print might be happening even before the server is listening for connections.

We should move it down a bit, maybe after this line: https://github.com/dart-lang/dev_compiler/blob/master/lib/devc.dart#L281

**Comment by sigmundch** [comment]
https://codereview.chromium.org/1088603002/

**Comment by sigmundch** [comment]
fixed in 86678fdcdb8ad2034633a2f6687259ff4b03557f
