### ISSUE TITLE
JsName and other metadata needs to live somewhere

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#135]
Either in a package or in a SDK library.

```dart
import 'what_the_heck_do_I_write_here' show JsName;

@JsName('HTMLAwesomeElement')
class AwesomeElement extends HTMLElement { ... }
```

**Comment by jmesserly** [comment]
the most obvious place to put it now would be package:dev_compiler. It's a place, that we can add to, and works for testing/examples until we find something better.

**Comment by jmesserly** [comment]
Otherwise, everyone needs to copy+paste JsName, that seems bad right?

**Comment by jmesserly** [comment]
dart:js might probably the right place once it's stable. Or just skip it and use package:js, since not sure it would need to be in dart:

**Comment by jacob314** [comment]
dart:js seems pretty reasonable although I can also see the case for
package:js/annotations.dart
or even 
package:dev_compiler
although I dislike that option as I expect these annotations will be consumed by code generators other than dev_compiler in the future.

**Comment by jmesserly** [comment]
> although I dislike that option as I expect these annotations will be consumed by code generators other than dev_compiler in the future.

agreed, dev_compiler would be a temporary place.

**Comment by ochafik** [comment]
Noobie question: can we use the annotation before the import and still get the right element?
```
@JsName(name = 'window')
library dom;

import 'package:js/src/internal.dart' show JsName;
```
(here the annotation seems to have a type which lib is `dom` :-S)

**Comment by jacob314** [comment]
Yep you can use the annotation before the import. We rely on that all the
time for the
@JS annotation.

**Comment by jmesserly** [comment]
Think the work here is done. Annotations found a good home.
