### ISSUE TITLE
upstream various analyzer helpers

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#143]
we've accumulated a few package:analyzer helpers, it would be good to get these upstreamed over time, and/or figure out if we're using it wrong.

off the top of my head, in no particular order:

AstNode
* sometimes is missing common super interface that would help code avoid multiple type tests and/or cast to dynamic, e.g. `name` on Declarations and `externalKeyword`.
* PrefixedIdentifier vs PropertyAccess
* .element vs .staticElement
* have a way of marking compiler generated intermediate nodes (isSynthetic? it seems to have another purpose)
* AstBuilder helpers

Element
* `type` getter is common to some subclasses but no common superinterface
* easier ways to query for members
* member lookups are currently linear search, should there be a hash for faster (algorithmic) lookup?
* logic for figuring out if a variable initializer is "effectively constant"
* logic for figuring out if an identifier is "stateless" within a given context. This is similar to isPotentiallyMutated* but only considers assignments within that context (and closure mutations from anywhere).

Types
* no easy way to get the default (dynamic) substitution of a generic type
* have a standard pattern for walking the type hierarchy (one for super/mixins, one for super/mixin/interfaces)? Skipping mixins is usually an error.
* It might be nice if there was a way to view the "flattened" single inheritance view, thereby not needing to think about mixins in code that doesn't need to care. Discussed below[1].

[1] This would mean a ".flattenedSuper" getter that could sometimes return a synthetic type to express the mixins. For example: `class Foo extends Bar with Baz, Qux {}` could be viewed as:

```dart
class Bar&Baz extends Bar implements Baz {
 // Baz members
}
class Bar&Baz&Qux extends Bar&Baz implements Qux {
 // Qux members
}
class Foo extends Bar&Baz&Quz {
}
```
the dart:mirrors API works this way
(https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:mirrors.ClassMirror#id_mixin), e.g. `reflectClass(Foo).superclass` returns `ClassMirror on '.Bar with .Baz, .Qux'`

that said, the way analyzer currently presents mixins is also useful

**Comment by jmesserly** [comment]
fyi @bwilkerson and @leafpetersen  ... no action needed now though, maybe best to discuss these items individually and/or next meeting offline? But I wanted to make sure we were tracking these somehow :)

**Comment by jmesserly** [comment]
another one: Leaf has some helpers for compiler generating AST nodes. It's a little tricky especially if the intent is to produce a resolved AST, requires populating lots of stuff, is there a better way?

**Comment by jmesserly** [comment]
Also, best pattern for marking nodes? We compute extra info sometimes (e.g. checker wants to say "this node is a dynamic runtime operation, codegen it that way") but no good way to store it.

**Comment by bwilkerson** [comment]
I'd be interested in looking at the helper methods and either pulling them in or suggesting alternatives, but I don't know where to look for them. In the mean time, a couple of thoughts.

> AstNode
>
> have a way of marking compiler generated intermediate nodes (isSynthetic? it seems to have another purpose)

Yes, I think that "synthetic" should be used for nodes that are implicit because of the language specification but are not explicit in the code (such as default constructors).

We also want to be careful about having the backend modify the AST structure because it has implications for other tooling (such as code completion, etc.) when the dev compiler is running in analysis server.

> Element
>
> member lookups are currently linear search, should there be a hash for faster (algorithmic) lookup?

Do we have evidence that this is a performance issue? It doesn't appear to be a problem in the analysis engine, but perhaps the dev compiler has different needs.

> logic for figuring out if a variable initializer is "effectively constant"

We definitely want to add this.

> Leaf has some helpers for compiler generating AST nodes. It's a little tricky especially if the intent is to produce a resolved AST, requires populating lots of stuff, is there a better way?

We have an AstFactory class, but it's currently only used for tests. This isn't the first time we've had a request like this, so we should definitely consider addressing it.

> Also, best pattern for marking nodes?

AstNode.getProperty(String) and AstNode.setProperty(String, Object)?

**Comment by jmesserly** [comment]
Just noticed this helper we have:
```dart
  FormalParameterList _parametersOf(node) {
    // Note: ConstructorDeclaration is intentionally skipped here so we can
    // emit the argument initializers in a different place.
    if (node is MethodDeclaration) return node.parameters;
    if (node is FunctionDeclaration) node = node.functionExpression;
    if (node is FunctionExpression) return node.parameters;
    return null;
  }
```
During transformation, we need to emit parameter checks inside the function body, so that code lives in visitExpressionFunctionBody/visitBlockFunctionBody ... it asks for its parent, then needs to do some type checks to get parameters in a consistent way.

Unrelated, but another issue: Element -> Node mapping. Some code would be cleaner to write if I could just iterate through elements and then get their nodes. This is for code in the library we're currently transforming, so the AST is available and safe to get, but the `.node` getter is somewhat of a performance trap. Maybe we should just have our compiler visit the whole AST (skipping method bodies) and collect element -> node mappings up front before we try and compile a library. (I'm sort of doing that in an ad hoc way already, to ensure classes are defined before use in other top-level code.)

**Comment by jmesserly** [comment]
minor issue: FunctionDeclaration isn't always a top level function declaration ... sometimes it's part of FunctionDeclarationStatement. Even though the comment says `A top-level declaration` and it's a CompilationUnitMember.

**Comment by jmesserly** [comment]
One gotcha we hit: `.length` on AstNode... calling it on a NodeList is fine, but accidentally calling it on an AstNode gives a very wrong answer, as it's the textual length. This can happen, e.g. `parameters.length` instead of `parameters.parameters.length`

also, not sure if anything can be done, but for VariableDeclarationList, I'd often rather see it "flattened" into a bunch of VariableDeclarations, even though that isn't how it parses. We have a lot of code like `node.fields.variables` and `node.variables.variables` ... e.g. because of how TopLevelVariableDeclaration/FieldDeclaration/VariableDeclarationStatement. It's kind of a shame because usually FieldDeclaration is just a single field.

**Comment by jmesserly** [comment]
update, we can now use TypeDefiningElement to get rid of `(element as dynamic).type` pattern. CL was here: https://codereview.chromium.org/1165213002/

**Comment by vsmenon** [comment]
One more pain point: When an Annotation is a constant constructor call, we need similar handling to InstanceCreationExpression in our backend, but the two are put together differently:
- Both have a constructorName field, but one (ICE) is a ConstructorName and the other (Annotation) is a SimpleIdentifier
- ConstructorName wraps a TypeName, where as Annotation has an Identifier

**Comment by jmesserly** [comment]
Many (most?) of these are fixed now. I think we can take these on a case by case basis now that we're mostly merged into Analyzer. CL's will be easier to track. :)
