### ISSUE TITLE
static/top-level const can hit use before define error

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#144]
Const can result in use-before-define errors as the code isn't sorted properly. library cycles make this worse, but the bug exists even with a single library, as the initializer expression isn't taken into account at all for class ordering. non-const final fields can hit this too, since we try to pretend they are const if possible.

Fortunately we already have means to codegen lazy fields, as that's how most statics work. So shouldn't be too bad, just need to track it.

Related issue on const canonicalization: https://github.com/dart-lang/dev_compiler/issues/29

**Comment by jmesserly** [comment]
At the moment I'm fixing the most egregious case regarding list initializers

**Comment by vsmenon** [comment]
Dup with #131?

**Comment by jmesserly** [comment]
ah, fair, didn't see that one.
