### ISSUE TITLE
Field formal parameter renaming isn't consistently handled

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#145]
Given this:
```dart
StackZoneSpecification([this._onError]);
```
we're generating this:
```javascript
    StackZoneSpecification(onError) {
      if (_onError === void 0)
        _onError = null;
      ...
    }
```
Note that _onError is renamed to onError in the param, but not in the body.

**Comment by jmesserly** [comment]
looks like optional params aren't going through visitSimpleIdentifier. We have some legacy code that does `name.name` ... which is much always wrong. (Class names are one of the few places where it might be legit.)

**Comment by vsmenon** [comment]
Our code to initialize optional params is just doing the following:

```dart
      // TODO(justinfagnani): rename identifier if necessary
      var name = param.identifier.name;
```

Is there a way to query the rename of identifier here?

**Comment by jmesserly** [comment]
haha, wow. Old TODO :)
