### ISSUE TITLE
Create quickfix that handles missing typed parameters on Array literals

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#15]
We're seeing 1000s if issues due to missing types on Array literals.  If an error occurred we know what they should have written.  Go ahead and write it as a quick fix.

Example:

```dart
Iterable<Type> get _types {
    if (_bindings == null) return  /* severe: StaticTypeError */ [];
    ...
}

should be rewritten as

Iterable<Type> get _types {
    if (_bindings == null) return  <Type>[];
    ...
}
```

by the quickfix tool

**Comment by vsmenon** [comment]
Downward inference now handles these cases.
