### ISSUE TITLE
Properly type check async methods

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#151]
Given this:

```dart
import 'dart:async';

Future<bool> foo() async { return true; }
```

we're reporting the following error:

```
severe: line 3, column 35 of foo.dart: [StaticTypeError] Type check failed: true (bool) is not of type Future<bool>
Future<bool> foo() async { return true; }
```

**Comment by jmesserly** [comment]
I presume we want to codegen these too at some point :)

**Comment by jmesserly** [comment]
fwiw ... if we could eventually refactor CodeChecker so it's more just integrate our typing rules into the existing Analyzer, we'd get new features like this "for free" :)
