### ISSUE TITLE
1.toString() generates invalid JavaScript code

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#155]
1.toString() is valid dart code but not JavaScript code. In JS you need to emit
(1).toString() or one of the JS synonyms for toString() such as ("" + 1)

**Comment by jmesserly** [comment]
huh. That strikes me as a bug in the src/js/printer.dart precedence logic. I'm surprised as dart2js uses the same library. Maybe they never generate that pattern though.

**Comment by jmesserly** [comment]
The fix would be to change LiteralNumber precedence to something lower, probably. Although maybe that's too conservative

**Comment by jmesserly** [comment]
yeah -1 on the precedence level fix, that would break `1.0.toString()` ... going to see what's up with LiteralNumber printing.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1090613006/

**Comment by rakudrama** [comment]
Hmm.  I thought there was code to force a space between the digit and the
period, i.e.
1 .toString()


      if (isValidJavaScriptId(fieldWithQuotes)) {
        if (access.receiver is LiteralNumber) out(" ", isWhitespace: true);
        out(".");

**Comment by jmesserly** [comment]
good question. Maybe our js_ast code is too old, I don't see that. I like that way of fixing tho

**Comment by jmesserly** [comment]
ah, seems I broke it when adding support for ES6 methods/enhanced object literals. d'oh
