### ISSUE TITLE
use ES6 const

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#156]
ES6 `const` is like Dart `final` ... we should generate that if it makes sense.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

**Comment by jmesserly** [comment]
this will be fixed in https://codereview.chromium.org/1483813002/

**Comment by ochafik** [comment]
Fixed by https://github.com/dart-lang/dev_compiler/commit/87c73d0365a790828078f6379ce418abc28dbad9
