### ISSUE TITLE
Generics and named constructors

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#158]
We appear to generate invalid code for named constructors with generic types:

```dart
class A<T> {
  A.named() {
    init();
  }

  init() {
    print('hello');
  }
}

main() {
  new A<int>.named();
}
```

results in this error when the named constructor is executed:
"Uncaught TypeError: this.init is not a function"

**Comment by vsmenon** [comment]
@jmesserly helped me track this down to precedence.  

We're generating:
```javascript
new A$(core.int).named();
```

We should be generating:
```javascript
new (A$(core.int).named)();
```

**Comment by vsmenon** [comment]
This is somewhat related to / muddled by #162.
E.g., this surprisingly seems to work today:
```dart
  new core.Map$(core.String, core.String).from(oldmap);
```
but it is actually creating an empty Map via the default constructor and calling from as an instance method on it.

**Comment by jmesserly** [comment]
yeah, that's the same bug

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1122283002/
