### ISSUE TITLE
Dynamic invokes (dsend) to Iterable / List methods are broken.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#167]
A dynamic invoke on an Iterable (runtime type UnmodifiableListView) with 'map' is throwing a NSM.  The object has a [core.$map], but that is not found.

**Comment by vsmenon** [comment]
@jacob314 @jmesserly Do you guys have thoughts on how to handle this?

**Comment by jmesserly** [comment]
dupe of https://github.com/dart-lang/dev_compiler/issues/142 right?
