### ISSUE TITLE
Implement dload checks robustly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#169]
dload (dynamic load) needs to implement the following checks.  They are either not implemented or not quite robust:
- [ ] NSM check on missing properties (should this be skipped for actual JS types?)
- [x] Tearoff / bind checks when "loading" a method
- [x] Extension methods (See #142)

**Comment by jmesserly** [comment]
NSM checks -- I presume we should always* call noSuchMethod, since Object.noSuchMethod is the one that actually throws?

(* with extra some "fun" if the type is not a Dart type)

**Comment by vsmenon** [comment]
@jmesserly We also have dart.noSuchMethod which tests for null & primitives and otherwise forwards to Object.noSuchMethod.  We could use that as a consistent entry point too.

@jacob314 for thoughts on NSM and JS types.

**Comment by jmesserly** [comment]
I am fixing nSM

**Comment by jmesserly** [comment]
duping this against https://github.com/dart-lang/dev_compiler/issues/59
