### ISSUE TITLE
consider providing auto-fixing tools for some specific cases

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#17]
Some cases that could easily involve a quick-fix:

  * inferrable overrides: subclass left out the return type of a method or getter, suggest the type in the superclass, example:
```dart
  /*suggest: String*/ toString() => 'foo';
```
  * operator `==` overrides:
```dart
operator ==(T t) => ...
/* suggest: operator ==(t) => t is T && ... */
```

Let's add more examples to this issue as we discover them...

**Comment by jmesserly** [comment]
we ended up using member inference instead
