### ISSUE TITLE
_emitTypeName not emitting type args for parameterized function types

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#171]
I haven't noticed this in the output, but looking at the implementation, it doesn't seem like it could possibly work: if the `type is FunctionType`, it will never get to the `type is ParameterizedType` check.

I think we're generating the definitions (visitFunctionTypeAlias) correctly, so it's only an issue at the use sites.

**Comment by leafpetersen** [comment]
I think name will be non-empty (and lowerTypedef will be false) for this case, won't it?  In which case, we should fall down to the right case?

**Comment by jmesserly** [comment]
ah, you're right :)
