### ISSUE TITLE
Rationalize runtime type encoding / setting

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#172]
We encode runtime types differently for nominal (implicitly on the proto) and structural types (not really implemented but see dart.setRuntimeType).  We're not clear in the code about what we use when - e.g., dart.setType and dart.setRuntimeType.

@leafpetersen

**Comment by jmesserly** [comment]
we just want to rename these methods to be more clear?

**Comment by jmesserly** [comment]
and add doc comments

**Comment by leafpetersen** [comment]
Based on our conversations, I'm planning to start out by making this uniform: every dart object will have an _runtimeType property which contains the type object.  We can then iterate towards where we want to end up (e.g. if we want to be less uniform).  I'll probably do some restructuring/renaming somewhere along the way.

**Comment by jmesserly** [comment]
isn't that redundant, though?
* why set a _runtimeType field when we already know it from the prototype/constructor?
* why set it on the object, which wastes a per-instance storage slot to store identical info?

if we had to have _runtimeType, at least it could be on the __proto__, to not waste space.

**Comment by leafpetersen** [comment]
So, I'm totally open to making this non-uniform.  I was just thinking of starting from someplace uniform that I was sure handled all the cases, and then optimizing from there.  My concern with just working from the prototype/constructor is that we seemed to be having a bit of a hard time distinguishing between various cases just based on that.  My understanding is that given an object, the cases that we have are: is it a primitive, is it a type object, is it a function/closure/method tear-off, or is it a regular object (there are also js objects, but let's ignore that for now).  For each of these, we need to be able to find the runtime type information (rtti).

We can distinguish primitives using instanceof, and just return the right rtti for each of them.

For regular objects, .constructor gives us the right rtti.

I don't think .constructor gives us the right answer for type objects and function/closure/method tear-offs does it?  Assuming not, then we need to be able to distinguish these from regular objects (that is, we need to get their rtti in a different way).  One way to do this is to put a _runtimeType property or getter on them.  For type objects, I think (if I understand the semantics correctly) we can put this as a static property on core.Object which just returns core.Type - inheritance of statics means that this property will end up on the prototype chain of the constructors.  For functions/closures/tear-offs we can attach this property to each one - maybe there's a way to share it, but not sure?  

So we could just use the _runtimeType property for everything except regular objects, and then we would just first look for the _runtimeType property, and if not found, use .constructor.  This is fine.  I was thinking maybe of making it completely uniform by adding _runtimeType as a getter (non-static) on core.Object which just returned this.constructor (I think that does the right thing).  If we use a symbol as the name of the getter, then we don't need to worry about name collisions.  Then we can tell the difference between dart objects and non dart objects, but I guess we can already do that by just walking up the chain looking core core.Object.  So maybe not worth doing.

Does putting it everywhere except on regular objects seem reasonable?  Can we get away with less?  Is there a better way to attach it to functions/closures/tear-offs than just banging in a symbol property?

**Comment by leafpetersen** [comment]
Fixed https://codereview.chromium.org/1182653002/  (at least for now).  Nominal types (classes) are represented by the javascript constructor for the class.  Special types and structural types are represented as instances of subclasses of TypeRep (see runtime/_types.js).  Object rtti is accessed as obj.constructor.  Primitive types are recognized via typeof.  Everything else (including classes, etc) has a type attached as a property.
