### ISSUE TITLE
Enforce growable vs non-growable List / Array

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#175]
The following:

```dart
void main() {
  var l = new List(10);
  l.add(32);
  print(l.length);
}
```

throws in the VM but prints "11" in DDC.

**Comment by vsmenon** [comment]
@jmesserly I think you've suggested injecting a different proto / subtype?  Pretty much the same point we call setType?

**Comment by jmesserly** [comment]
yeah, kind of strange this doesn't work tho:
https://github.com/dart-lang/dev_compiler/blob/d9fadc32b2fa2efc382d56a610abd2570e5497ff/tool/input_sdk/patch/core_patch.dart#L261
ah, it's this:
https://github.com/dart-lang/dev_compiler/blob/d9fadc32b2fa2efc382d56a610abd2570e5497ff/tool/input_sdk/private/js_array.dart#L88

if we made that look at the `fixed$length` property it would start working. I presume there's some type tracking logic that dart2js interceptors would use to figure out `fixed$length` ... but that doesn't work for us.
