### ISSUE TITLE
Inner functions need to be properly bound

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#177]
In the following code, both calls to inner (direct and via foo) fail as this is captured in neither case.

```dart
void foo(int f()) {
  print(f());
}

class A {
  int x;
  
  A(this.x);

  void run() {
    void inner() {
      return x;  
    }

    print(inner() - 1);
    foo(inner);
  }
}

void main() {
  new A(42).run();
}
```

This pattern shows up in isolate_helper.dart.

**Comment by jmesserly** [comment]
ah, nice. yeah we should generate those as arrow functions:
```js
let inner = () => {
  return this.x;
};
```

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1132113003/
