### ISSUE TITLE
Use analyzer's memory_file_system instead of our InMemoryUriResolver

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#183]
As @jmesserly points out here:

https://codereview.chromium.org/1130093007/diff/1/lib/src/in_memory.dart

we should be able to just use the analyzer's functionality:

```dart
new ResourceUriResolver(new MemoryResourceProvider())
```

instead of our own version.

**Comment by jmesserly** [comment]
@vsmenon if you aren't looking at this yet, I'm happy to :)

**Comment by vsmenon** [comment]
@jmesserly Feel free.  :-)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1146503003/
