### ISSUE TITLE
Named constructor on String is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#193]
This prints false in DDC:

```dart
main() {
  var str = new String.fromCharCode(42);
  print(str is String);
}
```

It appears that the type object of str is core.String, not the primitive String.

**Comment by vsmenon** [comment]
Ugh - this appears due to:

http://www.ecma-international.org/ecma-262/5.1/#sec-13.2.2

Since the fromCharCode constructor function is returning a non-Object (a string), we're ignoring the return value.

**Comment by jmesserly** [comment]
doh. probably want to compile that one as a static method.

**Comment by vsmenon** [comment]
Hmm, this seems a more general problem:

```dart
class A {
  factory A.foo() => null;
}

main() {
  print(new A.foo());
}
```

The above prints 'null' on the VM and "Instance of 'A'" in DDC.

**Comment by jmesserly** [comment]
@vsmenon were you looking into this one? If not I can take a look. Should be pretty straightforward.

**Comment by jmesserly** [comment]
one fun case, `factory Foo() =>` ... in other words, when the factory isn't a named constructor. In that case we have to make up a name for it, and call it as e.g. `Foo.new(...)`. Contrast with `factory Foo.bar() =>` which is called as `Foo.bar(...)`

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1156993015/
