### ISSUE TITLE
null is not a subtype of function types?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#194]
fyi, angular seems to be failing after recent function type checking change. Line 5449 in async.js:

```js
return dart.dcall(implementation.function, implementation.zone, parentDelegate, this, f)
```
ftype.checkApply(args) returns false, leading to a NoSuchMethodError (should be a type error, per TODO)

Here's some debugging I did:
ftype.name: "(Zone, ZoneDelegate, Zone, () -> Object) -> Object"

args realRuntimeType names: 

[_RootZone, Null, _CustomZone, () -> Object]

not sure what's up there ... it seems to fail because of the null is not a subtype of the function type.

**Comment by jmesserly** [comment]
oh, I stepped through what it's doing and it's definitely the `null` argument that fails the subtype test.

**Comment by jmesserly** [comment]
CC @leafpetersen

**Comment by leafpetersen** [comment]
Looks like realRuntimeType returns core.Null for null objects, which is probably reasonable, but means we need to check for null explicitly in checkApply before calling realRuntimeType and doing the subtype check.
