### ISSUE TITLE
Allow us to pass --url-mapping down into analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dev_compiler#201]
The analyzer has a --url-mapping which allows us to map embedder specific libraries to paths on disk. We use it to analyzer dart:sky code, for example.

We'd like to use this with dev_compiler so we can use the analysis capabilities of ddc with the Sky framework.

Thanks!

**Comment by jmesserly** [comment]
sounds good to me! will take a look at how analyzer_cli handles this

**Comment by jmesserly** [comment]
hmm, once we're integrated with analyzer_cli we get this for free.
Although seems good to unblock, so I'll throw together a quick fix

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1150143006/

**Comment by sethladd** [comment]
Thanks! We'll give it a shot on the Sky code.

**Comment by jmesserly** [comment]
yeah, really eager to hear! Was tempted to try myself, but it sounded like building mojo far enough to get dart_sky was a bit tricky, so figured it'd be easier for y'all that have things set up already. :)
