### ISSUE TITLE
Downward inference of parameter types

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#203]
In the closure in following code, we infer the return type (as int), but not the parameter types (left as dynamic):

```dart
typedef int Foo(int x, int y);

void bar() {
  Foo f = (x, y) => x+y;
}
```

That is sound, but suboptimal - `x+y` is handled via a dynamic invoke in generated code.

**Comment by leafpetersen** [comment]
Fixed by https://codereview.chromium.org/1462133005/ .
