### ISSUE TITLE
clean up options.dart

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#204]
discussion in this CL
https://codereview.chromium.org/1150143006/diff/1/lib/src/options.dart#oldcode21

here's my suggested course of action:

1. ResolverOptions, only what is needed for lib/src/checker/resolver.dart, move to that file?
2. CheckerOptions, only what is needed for lib/src/checker/checker.dart, move to that file?
3. UriResolverOptions/SourceFactoryOptions, or maybe AnalysisContextOptions? what is needed to set up an AnalysisContext, or maybe just a SourceFactory.
4. ServerOptions, all of the server stuff.
5. CompilerOptions to merge those, and add anything else that's left?

Also, I think making these mutable would work better with Dart as it exists today. Immutable was a noble goal, but it caused a lot of duplication in the default values, and worse it meant duplication in the fields, because mixins couldn't be used. I'd rather just go for mutable, and trust ourselves not to mutate them from inside the compiler.

**Comment by jmesserly** [comment]
@vsmenon thoughts on this?

**Comment by jmesserly** [comment]
fyi, I don't think we're blocked on this ... we can have analyzer_cli create a "CompilerOptions" class even though most are ignored. But seems like it would be good for Resolver/Checker options to be all it needs to care about.

**Comment by vsmenon** [comment]
Nice breakdown.  Yeah, I was getting confused by the different kinds of "resolution" we have and which one ResolverOptions really meant.  :-)

How do you think this fits in terms of potentially breaking apart the typechecker, the codegen, and the server into various packages?  One CompilerOptions class makes less sense there I think.

**Comment by jmesserly** [comment]
yeah, I think this will fit in nicely. lib/src/checker is almost a standalone package already. But yeah, that would push towards actually putting the CheckerOptions type under there somewhere

**Comment by jmesserly** [comment]
looking at some of this, for analyzer_cli integration. In particular splitting options used by "checker/" folder vs all other ones.
