### ISSUE TITLE
For loop variable type inference doesn't always work correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#21]
We should infer that i has type int here.

      for (var i = 0; i < 10; i++) {
        int j = /*info:DownCast should be pass*/i + 1;
      }

We seem to do this sometimes, not sure why it doesn't happen here - I think maybe the inference is happening but not getting propagated?

**Comment by vsmenon** [comment]
We appear not to handle for loops of this form.  From DDC rules.dart:

    // t must be an InterfaceType.
    List<DartType> typeArguments = (t as InterfaceType).typeArguments;
    for (var typeArgument in typeArguments) {
      if (!typeArgument.isDynamic) return false;
    }

We're reporting the call to isDynamic as a dinvoke - we should infer that typeArgument is a DartType, but we are not.

**Comment by vsmenon** [comment]
Fixed now.
