### ISSUE TITLE
Using == in generated JavaScript yields casts between Strings and numbers

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#210]
Should use `===` instead in `dart.equals` (and maybe in general, wherever `==` is outputted).

```
main() {
  print("10" == 10);
}
```

Code compiled with `dartdevc` prints `true`, expecting `false`.

**Comment by jmesserly** [comment]
fixed by #2101 right?

**Comment by ochafik** [comment]
Yes seems fixed, can't find examples where generating `==` in the code causes implicit conversions (good job on the type inference btw!).

**Comment by ochafik** [comment]
Oops, here's a case that fails:

```
class Foo {
  var x = 1;
  Foo([this.x = "1"]);
}
main() {
  print(new Foo().x == 1);
}
```

**Comment by jmesserly** [comment]
yeah ... I think we originally used === everywhere, and some of them got relaxed to == allow `undefined` to work as `null`. (I'm still not sure if that's a good idea, fwiw)

Most credit on inference goes to @sigmundch and @vsmenon :)

Regarding your example, might that be initializer ordering?

**Comment by ochafik** [comment]
No, actually it seems the issue is it's just not typechecking the default value of initializing formals.

For instance, this yields a `Type check failed: "1" (String) is not of type int` error:
```
class Foo {
  var x = 1;
  Foo() : this.x = "1";
}
```

**Comment by jmesserly** [comment]
Aha, that makes sense. So it thinks they're both `int` and uses `==` ... still might be safer to generate `===` in that case, though.

**Comment by jmesserly** [comment]
yeah, in general, the JS code only works assuming type checking was done correctly.
