### ISSUE TITLE
Default values of initializing formals is not typechecked

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#214]
This gives a `Type check failed: "1" (String) is not of type int` error:
```dart
class Foo {
  var x = 1;
  Foo() : this.x = "1";
}
```
But this does not (and should):
```dart
class Foo {
  var x = 1;
  Foo([this.x = "1"]);
}
```
(this causes subtle `==` issues, described in issue #210)

**Comment by jmesserly** [comment]
So, the type checking for this looks right. visitDefaultFormalParameter does the check. My guess is type is `dynamic` at this point. "1" assigns to dynamic, and then dynamic assigns to int. Contrast with:
```dart
class Foo {
  var x = 1;
  Foo([int this.x = "1"]);
}
```

What I think is going on here is two issues:

First bug: there's a coercion required for the "this.x" dynamic -> int conversion ... which we might not be generating. It's a somewhat odd AST so maybe js_codegen or reify_coercions drops the runtime type check.

Second bug/enhancement: we should really, really be inferring the type of the parameter "this.x" to be the same as the field "x". Not sure if this is just a missing feature, or some kind of ordering issue where we infer "this.x" too late relative to inferring the field type "x".

**Comment by jmesserly** [comment]
(btw, triple-backtick immediately followed by `dart` will give highlighting. It looks like `'''dart` but with backtick instead of single quote)

**Comment by jmesserly** [comment]
> First bug: there's a coercion required for the "this.x" dynamic -> int conversion ... which we might not be generating. It's a somewhat odd AST so maybe js_codegen or reify_coercions drops the runtime type check.

Doh. Above description is wrong, dynamic doesn't assign to int in DDC:
```
severe: line 72, column 6 of test/codegen/fieldtest.dart: [InvalidParameterDeclaration] Type check failed: dynamic this.x is not of type int
  C([dynamic this.x = "1", dynamic this.y = "2"]);
     ^^^^^^^^^^^^^^
severe: line 72, column 28 of test/codegen/fieldtest.dart: [InvalidParameterDeclaration] Type check failed: dynamic this.y is not of type int
  C([dynamic this.x = "1", dynamic this.y = "2"]);
                           ^^^^^^^^^^^^^^
```
So I tried this example:
```dart
class C {
  int x = 1;
  var/*inferred:int*/ y = 1;

  // Both parameters need runtime checks for the default values.
  C([this.x = "1", this.y = "2"]);
}
```
and got:
```
severe: line 72, column 15 of test/codegen/fieldtest.dart: [StaticTypeError] Type check failed: "1" (String) is not of type int
  C([this.x = "1", this.y = "2"]);
              ^^^
```

Which makes me think it's an inference/ordering issue.

**Comment by jmesserly** [comment]
This one was crazy ... it turns out Analyzer itself infers types for initializing formals with no type annotation, by using the field type (my guess is Dart spec has this rule). And this happens really early on, before we've done our type inference, so we end up concluding "1" assigns to dynamic (the type Analyzer filled in for that parameter), but when we checked the parameter for a type, we see there was no explicit type, so we concluded (incorrectly) that there was no check to perform. Wow.

**Comment by ochafik** [comment]
Wow, thanks / kudos for fixing this so fast!

Out of curiosity, how much does DDC depend on types inferred by the Analyzer? (does it just "strengthen" types from the Analyzer, or does it redo most of the inference job? could the Analyzer types be discarded completely?)

**Comment by vsmenon** [comment]
We mostly still use the analyzer's rules to compute static types, e.g., for computing the static type of an expression, strengthening it at certain points, and adding checks to validate.

We don't use the analyzer's 'propagatedType' at all though.
