### ISSUE TITLE
length not invoked properly on dynamic invokes

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#215]
The following prints undefined instead of 3:

```dart
dynamic l = [1, 2, 3];

void main() {
  print(l.length);
}
```

**Comment by jmesserly** [comment]
Probably just our special case for `length`. Lesson: why you shouldn't add special cases. My bad.

**Comment by jmesserly** [comment]
fyi ... I'm just going to remove the special case ... it also gets in the way of overriding the setter of length, if we want to do that.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1178523004/
