### ISSUE TITLE
should be able to compile more than one library in the same invocation

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#219]
And it'll be faster because we can reuse anything cached in analysis context...

**Comment by jmesserly** [comment]
we'll need this for SDK, or we'll have to create a fake library that imports all of the SDK libs ...

**Comment by vsmenon** [comment]
Yes - I've been getting around this by compiling 'dart:mirrors' instead of 'dart:core' in build_sdk, but that'll probably break once we get to the next one.

**Comment by jmesserly** [comment]
haha, I'm using the exact same trick for #168

**Comment by jmesserly** [comment]
yeah, so this is almost blocking me now, as our codegen tests are slowed down by reanalyzing the world over and over. I'm playing around with various ways to fix... What I think might work, is creating a simple front-end for batch compiler, that doesn't need to do any of the dependency graph tracking, instead just churns through a sources list reusing the same analysis context.

**Comment by jmesserly** [comment]
this will also be key to getting through language tests quickly
