### ISSUE TITLE
add private Dart libraries for our hand-coded JS runtime modules

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#220]
e.g. https://github.com/dart-lang/dev_compiler/blob/master/lib/runtime/_operations.js

could be "dart:_operations" in libraries.dart. We'll skip actually generating code for it, though, in the build_sdk step.

This will allow us to call them directly, rather than wrapping with the `JS` builtin:

https://codereview.chromium.org/1186683005/diff/20001/tool/input_sdk/private/js_mirrors.dart?context=10&column_width=80&tab_spaces=8

```dart
dynamic _dload(obj, String name) {
 return JS('', '#.dload(#, #)', _dart, obj, name);
}
```

might also help with moving these helpers to coercion reifier (e.g. actually generate a call to "dsend" top level method in "dart:_operations")

**Comment by vsmenon** [comment]
Perhaps this should use a general-purpose JS interop - it's 'just' another case of slapping a Dart API on top of an existing JS lib.

**Comment by jmesserly** [comment]
yeah, exactly!

**Comment by jmesserly** [comment]
I think this one is obsolete
