### ISSUE TITLE
incremental compile

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#223]
when batch compiling, it would be nice to reuse files in output if they are still valid
This might be blocked on analyzer summaries

**Comment by vsmenon** [comment]
@stereotype441 - is there anything simple we could start with for serializing / deserializing?

**Comment by jmesserly** [comment]
One thing I was contemplating. We could do a quick mtime check on transitive imports. If none are newer than the output artifact for that library, we don't need to recompile it. In some cases we might be able to skip resolution too. Although for low level libraries (like SDK) they'll still end up getting pulled in by something most likely. We can skip JS codegen for them but they'll get resolved.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1322333003/
we don't have summaries, but we can still avoid resolving as much stuff as possible.

FWIW, reading timestamps/source/parsing/js generation is all pretty fast. Resolution (which includes checking & inference in DDC because of our custom LibraryResolver) seems to be most of our time.

**Comment by jmesserly** [comment]
When we have summaries, this will be even more awesome, but even without them, we can still avoid a ton of work. At the very least it helps make our tests quite a bit faster, if you're working on a subset of them, you don't pay for rebuilding all of the other tests.

**Comment by jmesserly** [comment]
This is now the job of the build system (Make, Bazel etc)
