### ISSUE TITLE
Create a dartdevrun script / binary

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#225]
Best would probably be to fork out to [io.js](https://iojs.org/en/es6.html) with the relevant `--harmony-*` flags? Maybe leveraging the server mode + listening sources to re-run, or with a separate gulp config.

This would help run benchmarks (#224).

**Comment by jmesserly** [comment]
not a bad idea. if we got #223 right, it might not even be that slow. We'd want some kind of bindings to io.js APIs though?

**Comment by ochafik** [comment]
Incremental compilation, yay!!! I imagine we wouldn't need (m)any APIs for a start (Needle runs DeltaBlue and Richards with console.log as the only API :-)), but this could be a good testbed for the JS interop (we could auto-generate externs for [all these APIs](https://iojs.org/api/all.html)!)

**Comment by ochafik** [comment]
I've got something running okay in the [devrun_iojs](https://github.com/dart-lang/dev_compiler/tree/devrun_iojs) branch.

If it doesn't look too gruesome, happy to chunk in smaller PRs / send a Big One.

**Comment by jmesserly** [comment]
yeah, it looks nice! I have some comments but they're more of the code review type (e.g. something better than expanding `(typeof global == 'undefined' ? self : global)` in the code repeatedly ... but I bet we can work that out...)

**Comment by ochafik** [comment]
For future reference:
- [ES6 features in iojs](https://iojs.org/en/es6.html)
- [iojs next-nightlies](https://iojs.org/download/next-nightly/)
- Get the version of [V8](https://chromium.googlesource.com/v8/v8.git/) used by iojs: (`4.4.63.12` as of `iojs-v3.0.0-next-nightly20150722`):

  `iojs -p process.versions.v8`

**Comment by jmesserly** [comment]
one thing to keep in mind, they're working on a node/iojs merge: https://github.com/nodejs/node ... I'm not sure the ship status

**Comment by jmesserly** [comment]
ah, it looks like most work is still happening on io.js side (makes sense): https://github.com/nodejs/io.js/blob/master/CHANGELOG.md

**Comment by ochafik** [comment]
This is now in: a recent [iojs-next-nightly](https://iojs.org/download/next-nightly/) or [d8](https://developers.google.com/v8/build?hl=en) can be used with `dartdevrun`.

For instance:
```
dart bin/devrun.dart test/codegen/DeltaBlue.dart
dart bin/devrun.dart --v8-binary=path/to/v8/d8 test/codegen/DeltaBlue.dart
```
(note that a `dartdevrun` command alias was added and should be available with `pub global activate dev_compiler` after the next pub release)

**Comment by jmesserly** [comment]
> (note that a dartdevrun command alias was added and should be available with pub global activate dev_compiler after the next pub release)

DONE! https://github.com/dart-lang/dev_compiler/releases/tag/0.1.5
https://pub.dartlang.org/packages/dev_compiler

**Comment by ochafik** [comment]
Amazing, thanks John!
