### ISSUE TITLE
Rationalize Future<Future<T>>

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#228]
The Dart spec and libraries flatten nested Future types, both statically and at runtime.

This effects soundness of sequences like the following:

```dart
Future<T> f = ...;
f.then((T val) => ...);
```

If `T` is itself a `Future`, then the above should fail (and would in Dart checked mode).

We have a few options here, including some combination of:
- Rejecting code with nested Future types
- Treating Future as a type operator (similar to ! and ? in the non-nullability proposal where T!! is just T!)

@leafpetersen

**Comment by jmesserly** [comment]
I'm working on a fix for this in https://github.com/dart-lang/sdk/issues/25482

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1609093003/
