### ISSUE TITLE
allow is and as checks on generic parameters

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#236]
I think we need to come up with something here. For example:
http://www.dartdocs.org/documentation/matcher/0.12.0%2B1/index.html#matcher/matcher

see discussion around here
https://github.com/dart-lang/dev_compiler/issues/103#issuecomment-106554915

**Comment by jmesserly** [comment]
given
```dart
class SomeType<T> {
  bool test(x) => x is T;
}
main() => new SomeType<List<int>>().test(<Object>[123]);
```
options:
- (1) reject statically at instantiation of `SomeType<T>` ... in other words, there's an implicit constraint that T supports `is`. (variant: reject at construction time)
- (2) reject at runtime `is`, if type tested is a non-ground type (so, inside `test`)
- (3) reject at runtime `is`, but only if results differ from standard Dart `is` check
- (4) always have `is` using Dart semantics, provide a DDC helper library for our subtype check. (variant: the inverse of this)

Based on previous discussions, I think we're leaning towards (3).

CC @leafpetersen @vsmenon

**Comment by jmesserly** [comment]
We won't be able to run a lot of tests until we can support this, so kind of high priority

**Comment by vsmenon** [comment]
We need to resolve this to nail down our checking rules as well.  I think (3) is probably the best option here.  We should perhaps still generate an "info" in this case.

**Comment by jmesserly** [comment]
tagging Angular ... while it might not affect runtime, it'll block all tests, which would make developing an Angular app hard :)
