### ISSUE TITLE
move CodeChecker inference earlier in compilation

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#240]
some inference is happening after Analyzer StaticTypeAnalyzer runs

**Comment by jmesserly** [comment]
related: https://github.com/dart-lang/dev_compiler/issues/261

**Comment by jmesserly** [comment]
also related to #239 ...

**Comment by leafpetersen** [comment]
Fixed by https://codereview.chromium.org/1462133005/ .
