### ISSUE TITLE
integrate with analysis server

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#241]
... if DDC mode is enabled, its warnings/errors will then show up in the editor.

**Comment by bwilkerson** [comment]
We need a mechanism for enabling this in server. We now have an options file available to us; that might be a good short-term solution even if we decide we need something more later on.

We also need to implement the "strong" mode in analyzer. Neither piece sounds like too much work.

**Comment by jmesserly** [comment]
> We also need to implement the "strong" mode in analyzer. Neither piece sounds like too much work.

yeah, good point. this issue is blocked on #239

**Comment by jmesserly** [comment]
fixed a file ago!

.analysis_options:
```yaml
analyzer:
  strong-mode: true
```
