### ISSUE TITLE
reconcile Future/Promise

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#245]
For JS interop, it would be ideal if we could adapt Dart Futures to implement the Promise interface.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

This will also ease DOM interop as Promise becomes more common.

Ideally, Dart Future actually is a JS Promise, simply exposing different user-facing APIs (similar to Dart builtin List type and JS Array). But we could also try adapters, similar to Dart Iterable objects exposing a `[Symbol.iterator]()` method to JS, and Dart for-each consuming JS Iterables.

**Comment by jmesserly** [comment]
related #221

**Comment by jacob314** [comment]
This is now becoming an issue for JS interop

**Comment by jmesserly** [comment]
yeah, just wanted to add an update: this is something we're definitely doing, only question is when it happens. Probably after we've gotten the Dart language tests and modular compilation in a good place.

**Comment by jmesserly** [comment]
and SDK issue is https://github.com/dart-lang/sdk/issues/24679

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27315
