### ISSUE TITLE
dart:html support

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#252]
tracking bug for dart:html support

- [ ] need to annotate "extension interfaces", e.g. Iterable, that are depended on by JsPeerInterface types. Currently this is computed by js_codegen but not in a way that works for separate compilation (so it's hardcoded).
- [ ] need to be able to declare that JS members are exposed (like JsName does), but still add extension members. Currently extension members are all or nothing
- [ ] need a way to remove members. They can be removed from the static type, but we need to remove them from runtime dispatch too. Perhaps we get this for free from JsPeerInterface already.
- [ ] implement dart:html with DDC compatible annotations, or figure out how understand the dart2js ones

**Comment by ferhatb** [comment]
Looks like DDC currently generates code with "normal" method names instead of symbols / computed properties, when trying to call methods on Element:

```dart
import 'dart:html';

main() {
  var e = new DivElement();
  e.append(null); // compiled to e.append, but should be e[dart.dartx.append]
}
```

**Comment by jmesserly** [comment]
Hey @ferhatb, I think this bug is obsolete (dart:html is supported). I'll open a new one for you.

**Comment by jmesserly** [comment]
the new bug is https://github.com/dart-lang/dev_compiler/issues/464
