### ISSUE TITLE
Better StackTrace support

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#254]
Per the Dart spec:

*If the object being thrown is an instance of class Error or a subclass thereof,
its stackTrace getter will return the stack trace current at the point where the
the object was first thrown.*

In this case, the trace can be programmatically obtained via the `Error.stackTrace` getter.

The JS Error type appears to create the trace on allocation (not throw).

For other types, we also need to support:

```dart
try {
  ...
} catch (e, StackTrace st) {
}
```

**Comment by vsmenon** [comment]
Some thoughts here:

1. Always use `dart.throw_` (and probably `dart.rethrow`) instead of a plain JS throw.

2. Those methods should set / preserve a private expando (e.g., [dartx.stack]) with the JS stack trace (which can be created via JS Error).  

3. On a Dart catch, the `dart.stackTrace` method can be used to recover the Dart `StackTrace` from the above.  Similar for `Error.stackTrace`.

For JS interop, the above can also look at the stack field.  That handles the case where JS errors are caught in Dart, but not vice-versa.

For the other direction, perhaps we should overlay Dart's `Error` (and `Exception`?) onto the JS `Error` class?

**Comment by jmesserly** [comment]
> Always use dart.throw_ (and probably dart.rethrow) instead of a plain JS throw.

whenever we can't use the JS operation, it's always a bit of a red flag (context: https://codereview.chromium.org/1233553005/). We did have dart.throw before, but that was used for throw expressions, which JS can't express. And it didn't really do anything except throw. When we start depending on not using JS constructs, we get into interop troubles as well as losing some of our advantages around lightweight understandable codegen.

I don't know how much time we can spend on this now, but ideally, we can find a way to make throw work in most cases.

I'll send some suggestions over on the code review side.

**Comment by vsmenon** [comment]
On Mon, Jul 13, 2015 at 9:24 AM, John Messerly <notifications@github.com>
wrote:

> Always use dart.throw_ (and probably dart.rethrow) instead of a plain JS
> throw.
>
> whenever we can't use the JS operation, it's always a bit of a red flag
> (context: https://codereview.chromium.org/1233553005/). We did have
> dart.throw before, but that was used for throw expressions, which JS can't
> express. And it didn't really do anything except throw. When we start
> depending on not using JS constructs, we get into interop troubles as well
> as losing some of our advantages around lightweight understandable codegen.
>
> I don't know how much time we can spend on this now, but ideally, we can
> find a way to make throw work in most cases.
>
Agreed.  Definitely open to suggestions here.  I used a symbol/expando
instead of wrapping as I thought it'd be better for interop.

This does substantially improve debugging Angular - I get the original
stack trace now.
