### ISSUE TITLE
Unify DDC SDK with Dart repo's SDK

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#257]
DDC compiles against the Dart SDK that is installed, but runs against an older built snapshot from our implementation. Here's the plan to fix that:

- [ ] delete our 1.9 copy. Replace with latest.
- [ ] figure out how we store latest SDK. Ideally we don't check it in. Maybe DEPS or git submodules to point at a hash file?
- [ ] try to patch against our impls. It's an error if the patch files don't line up.
- [ ] fix the impls if needed (i.e. implement new APIs that are lacking DDC impl)
- [ ] save the JS file as well as DDC summary
- [ ] DDC must compile against its own SDK summary (otherwise there's no guarantee the impls will work)

thanks to @vsmenon for helping me brainstorm this :)

**Comment by munificent** [comment]
I'll take dart:async.

**Comment by vsmenon** [comment]
@jacob314 will look at dart:html once dart:async is landed

**Comment by munificent** [comment]
dart:async is done as of 8154650779ea579e4d599ad422e459305b405eac

**Comment by munificent** [comment]
Working on Uri and probably dart:convert (since Uri uses it) now.

**Comment by rakudrama** [comment]
Blocked by #253:
lib/collection/linked_list.dart
lib/collection/queue.dart
lib/collection/splay_map.dart

**Comment by munificent** [comment]
OK, Uri and dart:convert are landed, though @floitschG says there may be some more dart:convert changes coming soon after. What's left to do?

**Comment by munificent** [comment]
This issue was originally about *unforking* DDC's SDK but we've been using it to refer to *rolling* it. To disambiguate, I'm forking the bug. This one is now about unforking. The bug for just rolling the latest SDK is #565.

**Comment by jmesserly** [comment]
I investigated DDC summary. We can produce it with new Analyzers, but we can't build tests against it because some packages and a few tests seem to depend on dart:io (not sure if they use much of it or what's up there).

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27314
