### ISSUE TITLE
Problems with array method dispatch

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#258]
This needs to be triaged a littler further, but the following is breaking

```dart
void main() {
  var l = true ? [] : <int>[];
  l.add(42);
  print(l);
}
```

the error is:

```
NoSuchMethodError : method not found: 'undefined'
Receiver: Instance of 'JSObject<Array>'
Arguments: [42]
```

If `l` is explicitly typed as `List`, it works.

A couple things going wrong here:
- Inference seems broken in this case - l appears to be inferred as `EfficientLength`
- When inference breaks, our generated code is going off the rails.

**Comment by vsmenon** [comment]
I should add that it's showing a warning that `add` is not implemented in `EfficientLength`.  This should be a static error instead.

**Comment by jmesserly** [comment]
EfficientLength doesn't have `add`, so I think the runtime failure is reasonable, the input isn't sound. That nSM is not totally helpful though, since we lost the name for the method.

I guess generated code assumes `.add` is there, since it just tries to make the best of an unsound situation. Maybe it should generated it as a dsend instead. That would've found the extension method on JSArray.

**Comment by jmesserly** [comment]
oops, I forgot it's not codegen's responsibility to choose dsend or not. Checker should've marked the node as need it.

**Comment by vsmenon** [comment]
I did tweak it to do that:
```
    let l = true ? [] : dart.list([], core.int);
    dart.dsend(l, dartx.add, 42);
    core.print(l);
```
but it generates the error above.

**Comment by vsmenon** [comment]
Ahh, if `l` is `dynamic`, it generates `add` instead of `dartx.add`.  This might be a broken 'fix' on my part.

**Comment by leafpetersen** [comment]
EfficientLength is the "correct" upper bound per the specs definition:  https://github.com/dart-lang/sdk/issues/19425 .  We should probably define our own notion of upper bound.

**Comment by jmesserly** [comment]
we can also kill EfficientLength, it's totally meaningless to DDC

**Comment by jmesserly** [comment]
> Ahh, if l is dynamic, it generates add instead of dartx.add. This might be a broken 'fix' on my part.

yup, dynamically we always call methods by string name, so 'add'. dartx.add is a static call to an extension method. It's up to `dsend` to figure out if it needs to make the call as `dartx.add` vs `add` by taking into account the actual runtime type

**Comment by jmesserly** [comment]
> we can also kill EfficientLength, it's totally meaningless to DDC

oops, ignore that, I thought it as a dart2js impl type. But it's public feature of ListIterator and Set and things like that. DOH.

**Comment by jmesserly** [comment]
> EfficientLength doesn't have add, so I think the runtime failure is reasonable, the input isn't sound. That nSM is not totally helpful though, since we lost the name for the method.

btw, I have a fix for nSM being unhelpful, in this CL https://codereview.chromium.org/1243503007/
related bug: https://github.com/dart-lang/dev_compiler/issues/270

**Comment by jmesserly** [comment]
UPDATE:

> That nSM is not totally helpful though, since we lost the name for the method.

This is fixed.

> I should add that it's showing a warning that add is not implemented in EfficientLength. This should be a static error instead.

Fixed too: severe: [AnalyzerMessage] The method 'add' is not defined for the class 'EfficientLength'

>  When inference breaks, our generated code is going off the rails.

Yeah, so if you're going to run `--force-compile`, not sure we can really fix this. I mean, we rely on type checks for soundness. Unless we bring back the old "flip everything to dynamic" mode...

For this particular one, an unresolved method: maybe we could detect calls that don't resolve. I think when we integrate with analyzer, we'll get this for free. That node won't have an Element associated with it. That's my preferred solution to this: https://github.com/dart-lang/dev_compiler/issues/132

> EfficientLength is the "correct" upper bound per the specs definition: dart-lang/sdk#19425 . We should probably define our own notion of upper bound.

Filed: https://github.com/dart-lang/dev_compiler/issues/288

Anyway I think this is captured by those other specific issues, so closing this one.
