### ISSUE TITLE
ast mutation polluting analysis context

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#259]
every time JS generation runs, so does CoercionReifier, which inserts extra cast nodes.
CodeChecker has a similar issue: it annotates dynamic invokes, and it tries to set the property again. (this is harmless, though, because data is the same, but breaks assertions.) 

we have a super hacky workaround in [lib/src/compiler.dart#L135](https://github.com/dart-lang/dev_compiler/blob/e613c059ee987ab5bc4dcc2c5e2e1c3dc5db6769/lib/src/compiler.dart#L135), but it needs to go

**Comment by jmesserly** [comment]
BTW, some background: CoercionReifier takes a resolved AST, and mutates it to create a resolved AST with extra casts. What's nice about this design is that casts are handled purely at the Dart AST level -- our JS code generator can ignore them. We've really liked this architecture--it's a nice separation of concerns. We've wanted to see even more stuff (dynamic invokes) moved to that phase.

I tried AstCloner, but it doesn't preserve element/type pointers, which we really need. Not sure how to solve this.

**Comment by bwilkerson** [comment]
The class ResolutionCopier should be able to do what you want. Use AstCloner to create a new AST, then use ResolutionCopier to copy the resolution information from the old AST to the new AST.

**Comment by jmesserly** [comment]
ah nice! I'll give that a try :)

**Comment by jmesserly** [comment]
@bwilkerson -- if you don't mind uploading a new analyzer package, I can land https://codereview.chromium.org/1245013005/ and close this \o/

**Comment by bwilkerson** [comment]
It should be published now.
