### ISSUE TITLE
what to do with dartdevc entry point? (bin/devc.dart)

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#260]
Ideally, we could reuse a lot of the code in analyzer_cli (for batch compilation) and analysis_server (for watching files and triggering compile when stuff changes). both of those packages can depend on dev_compiler, but not the reverse.

What's the best approach here? We could have an option that loads the JS generator, but maybe separate entry point(s) would be a way to isolate the JS generation if we're worried about that.

**Comment by jmesserly** [comment]
Also, we need to be running in task model mode (assuming #261 is fixed first). Is there an easy way to turn that on?

**Comment by jmesserly** [comment]
This is kind of a question of `dartdevc` vs `dartanalyzer --js`. Basically how can we reuse code in https://github.com/dart-lang/analyzer_cli.

Not sure how we could add an entry point, since analyzer_cli isn't on Pub, instead it's built by Dart SDK. 

I like that DDC is distributed through Pub at the moment, in that we get better versioning, and the on-the-side feel is appropriate given the experimental state of things. But not sure we can preserve that.

**Comment by bwilkerson** [comment]
> Also, we need to be running in task model mode (assuming #261 is fixed first). Is there an easy way to turn that on?

You can set AnalysisEngine.useTaskModel to true.

> Not sure how we could add an entry point, since analyzer_cli isn't on Pub, instead it's built by Dart SDK.

I haven't done a lot of thinking about it, but one possibility that comes to mind is to create a dartdevc package that depends on dev_compiler and analyzer_cli. We'd have to publish analyzer_cli, but the only reason we haven't so far is a lack of reason to do so.

**Comment by jmesserly** [comment]
I think we're in an OK place for this right now.
(If we have code we want to share, maybe we can move it down into package:analyzer)
