### ISSUE TITLE
flag for enabling mirrors info

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#268]
We get some amount of mirrors "for free" via JS reflection, but other mirror features require us to preserve additional information not needed by code at runtime. We may want to consider options to suppress this extra code for cases where the developer knows it won't be used.

**Comment by eernstg** [comment]
Just to point out some potential sources of synergy, this line of thinking seems to have a lot in common with the `MirrorsUsed` mechanism for `dart:mirrors`, and with the capability specifications for [Reflectable][1].

[1]: https://github.com/dart-lang/reflectable/blob/master/reflectable/doc/TheDesignofReflectableCapabilities.pdf

**Comment by jmesserly** [comment]
Ah, yes, excellent point! Reflectable capabilities would let us be much more precise about what to keep around!
