### ISSUE TITLE
unable to find source input

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#273]
When trying to compile with ddc 0.1.3 (the latest published version), I see this error:
```
[~/projects/atom-dartlang] dartdevc web/entry.dart
Unhandled exception:
Invalid argument (uri): could not find source for: "web/entry.dart"
#0      BatchCompiler.compileFromUri (package:dev_compiler/src/compiler.dart:88)
#1      BatchCompiler.compileFromUriString (package:dev_compiler/src/compiler.dart:83)
#2      Object&ListMixin.forEach (dart:collection/list.dart:63)
#3      BatchCompiler.run (package:dev_compiler/src/compiler.dart:74)
#4      main (http://localhost:57161/devc.dart:47)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

The source file `web/entry.dart` exists :) Previous versions of ddc had been able to compile this file, but I don't remember when I last tried.

**Comment by jmesserly** [comment]
oops, we haven't kicked a release since https://github.com/dart-lang/dev_compiler/commit/0b0f07faea680f4f8b3ffaa8854f82be4febc960 ... I can have that out in a few minutes

**Comment by jmesserly** [comment]
done: https://github.com/dart-lang/dev_compiler/releases/tag/0.1.4
https://pub.dartlang.org/packages/dev_compiler

**Comment by jmesserly** [comment]
and fwiw, the workaround was to supply an absolute path, e.g. `pwd`/web/entry.dart

**Comment by devoncarew** [comment]
Cool, thanks!
