### ISSUE TITLE
Could not activate dev_compiler package v0.1.5

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/dev_compiler#275]
Hello everyone!

Updating my package's dependencies to include `dev_compiler: 0.1.5` as a dependency, `pub get` fails to execute with an error message:
`A transformer imported unknown package "pub_semver" (in "package:pub_semver/pub_semver.dart").`

My SDK version is 0.12.0-dev4
`pub global activate dev_compiler` outputs:
```
Resolving dependencies...
+ analyzer 0.26.0
+ args 0.13.2
+ charcode 1.1.0
+ cli_util 0.0.1+2
+ collection 1.1.1
+ crypto 0.9.0
+ csslib 0.12.1
+ dev_compiler 0.1.5
+ glob 1.0.5
+ html 0.12.1+2
+ http_parser 0.0.2+8
+ logging 0.11.1
+ mime 0.9.3
+ package_config 0.1.1
+ path 1.3.6
+ plugin 0.1.0
+ shelf 0.6.2
+ shelf_static 0.2.3
+ source_maps 0.10.1
+ source_span 1.1.2
+ stack_trace 1.3.4
+ string_scanner 0.1.3+1
+ utf 0.9.0+2
+ watcher 0.9.7
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.3
Precompiling executables...
Loading source assets...
A transformer imported unknown package "pub_semver" (in "package:pub_semver/pub_semver.dart").
```
System: Win 8.1

## Fix:
updating the pubspec.yaml file of dev_compiler to list the pub_semver as a regular dependency, not as a dev dep seemed to have worked.

**Comment by jmesserly** [comment]
Looks like this was fixed ... kicking out a patch release. Thanks for catching

**Comment by jmesserly** [comment]
Released as https://github.com/dart-lang/dev_compiler/releases/tag/0.1.5%2B1, https://pub.dartlang.org/packages/dev_compiler#versions

**Comment by daniel-v** [comment]
I can confirm, 0.1.15+1 fixed the issue.

**Comment by jmesserly** [comment]
\o/
