### ISSUE TITLE
generic methods

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#28]
methods on Iterable, like map, could really use a generic method annotation. Even if we had to do inference for those methods, it would be worth it IMO. Annotation could be opt in.

Some ideas:
```dart
// current signature/impl
Iterable map(f(E element)) => new MappedListIterable(this, f);

// full signature in an annotation
@Sig('(E -> R) -> Iterable<R>')
Iterable map(f(E element)) => ...

// Tells the system to use inference like H-M for this method
// This could be added by the programmer in places where it is needed.
// User friendly but presumably more compute intensive.
// It could also be a convenience feature on top of the explicit signature.
@inferTypes
Iterable map(f(E element)) => ...
```

**Comment by jmesserly** [comment]
I think @leafpetersen is looking into this one

**Comment by jmesserly** [comment]
This is pretty far along now. We have comments in SDK, basic upwards inference. In a few places we need to support explicitly passing type arguments (for calls & tear offs)

**Comment by jmesserly** [comment]
static checking is essentially done, we need the JS compilation side of things

**Comment by nex3** [comment]
Just for reference, what's the syntax for this?

**Comment by jmesserly** [comment]
Syntax is described here: https://github.com/dart-lang/dev_compiler/blob/master/GENERIC_METHODS.md

**Comment by jmesserly** [comment]
Closing this one out, since we definitely decided to do it, and are well along in the implementation.
New tracking bug here: https://github.com/dart-lang/dev_compiler/issues/435
