### ISSUE TITLE
Infer tighter return types for math.max() and math.min()

### ISSUE THREAD

**Issue by munificent** [dart-lang/dev_compiler#281]
Right now, this code:

```dart
void expectInt(int i) {}

main() {
  expectInt(math.min(1, 2));
}
```

generates a warning:

```
[warning] math.min(1, 2) (num) will need runtime check to cast to type int
```

It would be really nice if DDC could infer the tighter `int` return type if it knows the arguments are both ints. A "real" solution likely involves either generic methods:

```dart
T min<T extends num>(T a, T b) { ... }
```

or maybe some kind of TypeScript-style overloading. In the absence of either of those, it could be worth special-casing `min` and `max` in the same way that the spec does for the arithmetic operators.

**Comment by jmesserly** [comment]
Maybe I tend to approach these too much from the JS perspective, but ... we could just treat `int` and `double` the same. It doesn't make any difference to the generated code. I'm not even sure we'll actually emit the cast if you wrote it (maybe just as a null check)

**Comment by jmesserly** [comment]
FWIW, looks like generic methods DEP would fix this: https://github.com/leafpetersen/dep-generic-methods/blob/master/proposal.md#functions

we'll need to implement it soon, at least for the SDK. We're currently ignoring a bunch of unsound casts for a hard coded list of types: https://github.com/dart-lang/dev_compiler/blob/5e0e7d27c36a8d7d6858ddf3b7a66892de6539ae/lib/runtime/_operations.js#L180

see also https://github.com/dart-lang/dev_compiler/issues/28

**Comment by vsmenon** [comment]
We're hitting this several times in Angular too - see:
https://travis-ci.org/angular/angular/jobs/74151416

This should be captured by @leafpetersen 's inference-based generic method work.

**Comment by jmesserly** [comment]
yeah. I have a quick fix about to send out, but Leaf can definite feel free to delete it after :)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1253903004/

**Comment by jmesserly** [comment]
@munificent this is now fixed! I used your suggestion: special case min/max, until we get generic methods.

I take it you were trying out --strong mode? if you're willing to give it another go, I can kick out a dev compiler release and roll it into SDK, would show up in next SDK dev build. Or you could try `pub global activate dev_compiler; dartdevc filename.dart` ... should give more or less the same results as analyzer_cli.

**Comment by munificent** [comment]
Awesome, thank you for the quick fix! :heart:
