### ISSUE TITLE
Generate node.js compatible modules

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#285]
This has been suggested a few times.  Opening this as a tracker.

Some blockers:
- [ ] ES6 (though we now run on io.js with @ochafik 's changes)
- [ ] Plugging into node's modules (see #284)
- [ ] dart:io and friends ... no JS implementation for these

**Comment by jmesserly** [comment]
IMO, ES6 isn't really a blocker ... nodejs is going to support it. So it's a backporting issue: do we want to support older node versions, or do we want this before nodejs is finished with ES6. But in that case, could we just use an existing ES6->5 transpiler for that?

> dart:io and friends ... no JS implementation for these

yeah. tricky part there is I'm not sure how the test coverage is for dart:io these days. Used to be not great. I guess Pub covers it pretty well though, so maybe Pub's tests can work as a dart:io test suite.

**Comment by devoncarew** [comment]
Adding the `atom` label to this. It's not a blocking issue - I'm able to use the existing module system w/ some code-gen - but we've talked about it enough in the context of atom that I thought I'd add the tag.

**Comment by jmesserly** [comment]
> Adding the atom label to this. It's not a blocking issue - I'm able to use the existing module system w/ some code-gen - but we've talked about it enough in the context of atom that I thought I'd add the tag.

yeah, +1. Even if you can work around it, we should still make it so you don't have to/can get rid of the workaround :)

**Comment by jmesserly** [comment]
Fixed in https://github.com/dart-lang/dev_compiler/commit/393c2b3b7212f94e629ed47e0a64b4183ee5a79f :tada:

**Comment by jmesserly** [comment]
I'll open a bug for dart:io node wrapper.

**Comment by jmesserly** [comment]
https://github.com/dart-lang/dev_compiler/issues/436 for dart:io
