### ISSUE TITLE
Static checker hangs on illegal class declaration

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#287]
On the following tests:

https://github.com/dart-lang/co19/blob/master/Language/07_Classes/9_Superclasses_A03_t01.dart
https://github.com/dart-lang/sdk/blob/master/tests/language/cyclic_class_member_test.dart

Both have this pattern:
```dart
class A extends A { ... }
```

Obviously, broken code, but we shouldn't hang.  This happens whether we call via dartanalyzer or devc.

**Comment by jmesserly** [comment]
yeah, analyzer always uses a `visited` HashMap to guard against this.
