### ISSUE TITLE
Finalize override semantics with dynamic-typed parameters

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#289]
We need to nail down which of these overrides to allow and disallow:

```dart
class A {
  void foo(dynamic x) { ... }
  void bar(int y) { ... }
}

class B extends A {
  void foo(int x) { ... }
  void bar(dynamic y) { ... }
}

class C extends B {
  void bar(String y) { ... }
}
```

**Comment by jmesserly** [comment]
Not sure if this is the right bug, but we've discussed covariant parameter types in overrides (and adding a check). I thought it was interesting that Eiffel supported this: 
https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Contravariant_method_argument_type

I think we were considering some explicit annotation (on the base class method? Or on the derived class method?) to opt in.

**Comment by jmesserly** [comment]
merging into analyzer bug: https://github.com/dart-lang/sdk/issues/25232

**Comment by jmesserly** [comment]
actually moved to: https://github.com/dart-lang/sdk/issues/25578, the other bug turned out to not be strong mode specific
