### ISSUE TITLE
Remove UninferredClosure type

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#290]
These are cases that should be handled by contextual inference, but are not.  We appear to still generate these though.  It's a warning.

@leafpetersen : do you know what we're not handling yet?

**Comment by leafpetersen** [comment]
My guess is because I have only implemented downwards inference to functions of the form (x) => e, and not of the form (x) => {...}.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1627503002/
