### ISSUE TITLE
automatically compute list of valid error types for tests

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#3]
Currently we have a list harcoded here:

https://github.com/dart-lang/dart-dev-compiler/blob/02259b871438fcdac72f9cc788908584cbc50129/lib/src/testing.dart#L254

We could use mirrors to generate this automatically instead.

**Comment by jmesserly** [comment]
Wow, 3rd issue ever. Going to fix this.

**Comment by sigmundch** [comment]
Actually, I think this was fixed a while back but forgot to close the issue. See https://github.com/dart-lang/dev_compiler/blob/4bd449fcfe45628db7e3b0a0601c6cec0e66a55e/lib/src/info.dart#L518

**Comment by jmesserly** [comment]
Lovely!
