### ISSUE TITLE
Implement assert() messages behind a flag 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#303]
This adds optional messages to an assert.

See DEP: https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md

Main bug: https://github.com/dart-lang/sdk/issues/24213

**Comment by jmesserly** [comment]
behind a flag? Aren't *we* entirely behind a flag? ;)

**Comment by jmesserly** [comment]
(experimental language flags to an experimental compiler, we must go deeper :) )

**Comment by jmesserly** [comment]
oh shoot, i realized we're blocked on analyzer: https://github.com/dart-lang/sdk/issues/24217

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27342
