### ISSUE TITLE
batch compiler is too slow

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#304]
Building tests...
```
$ dart -c test/codegen_test.dart
00:27 +212: All tests passed!
```
we're building 251 js files in 27 seconds, or about 100ms per file on my laptop. Now, it's not quite that bad, because processing the SDK takes some time at startup. Still, that feels way too slow.

**Comment by jmesserly** [comment]
I haven't looked, but one possibility is we're repeatedly compiling some of the shared libraries (due to lack of a true incremental mode). But I don't think that should be happening with the test context

**Comment by ochafik** [comment]
`BatchCompiler._copyDartRuntime` eats up 7 sec out of the 22 sec that test takes on my laptop: we could / should skip it with some flag + make the copies async anyway (not sure how far async would propagate, though).

**Comment by jmesserly** [comment]
Nice find. That's at least one of our issues. Looks like an easy fix, too.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1321103002/ ... looks like we were copying things repeatedly
> not sure how far async would propagate, though

yeah, same, not sure async will really help.

**Comment by jmesserly** [comment]
js_test is also really slow, makes me wonder if error messages are still really slow to emit. I don't think that should be an issue anymore. (at one point we were rereading the file for every message to compute the span, ouch)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1322333003/ fixes. Duping this against #223
