### ISSUE TITLE
Write all of the runtime in Dart.

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#310]
This would help with:
- Support for different module systems (#284)
- Closure Compiler output (with fully-annotated runtime primitives)

Note that this would imply changing the signature of a couple of vararg functions (`dart.mixin`, `dart.fn`...).

There are a couple of files that need translation as they produce modules:
- [ ] [rtti](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_rtti.js)
- [ ] [types](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_types.js)
- [ ] [classes](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_classes.js)
- [ ] [errors](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_errors.js)
- [ ] [generators](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_generators.js)
- [ ] [operations](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_operations.js)
- [ ] [dart_runtime](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart/_runtime.js)

The following helper file needs to be converted to a module:
- [x] `dart_utils.js` (https://github.com/dart-lang/dev_compiler/commit/d91add0d8490bbb59f72fe676fe70cfeedcd1e91)

Then the following file is used to support the current module system, so we might not want to translate them:
- [dart_library](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart_library.js)

**Comment by ochafik** [comment]
Started experimenting in branch [passthrough-js-interop](https://github.com/dart-lang/dev_compiler/tree/passthrough-js-interop).

**Comment by jmesserly** [comment]
yeah, the methods that take rest arguments are a problem. @jacob314 @vsmenon any thoughts on how we can encode it in such a way DDC understands?

Other than that, do we need anything other than the existing "JS" builtin? dart2js implements the SDK with it, so it should be pretty powerful.

**Comment by jmesserly** [comment]
oh, we also need a way to get DDC to stop emitting type assertions around JS builtin expressions. Either fixing how we parse the type strings, or just trusting them and allow it to be assigned to any type.

**Comment by ochafik** [comment]
Regarding rest params, an ad-hoc annotation [such as `@varargs`](https://codereview.chromium.org/1412663002) would do the trick.

There are a couple of files that need translation as they produce modules:
- [ ] [rtti](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_rtti.js)
- [ ] [types](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_types.js)
- [ ] [classes](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_classes.js)
- [ ] [errors](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_errors.js)
- [ ] [generators](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_generators.js)
- [ ] [operations](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/_operations.js)
- [ ] [dart_runtime](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart_runtime.js)

Then the following files are used to support the current module system, so we might not want to translate them:
- [dart_library](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart_library.js)
- [dart_utils](https://github.com/dart-lang/dev_compiler/tree/master/lib/runtime/dart_utils.js)

Note that `dart_runtime/*` modules might need to be relocated under `dart/*` if they're generated from the sdk input, as there is quite a bit of `dart:` scheme-specific logic in the compiler (and `dart_runtime` is not a valid scheme as it contains an underscore).

That is, for instance, `dart_runtime.js` currently defines a `dart_runtime/dart` module, but we might want the new equivalent `_dart_runtime.dart` to define a `dart._dart_runtime` library instead.

Regarding what to start with:
- It's unclear if any file is easier to translate before the others, as there's quite a bit of interdependence
- We can [adopt rest parameters in our .js helpers](https://codereview.chromium.org/1411473003/), which will make the translation slightly easier.

(side-note: `JS('', '...')` can be used to wrap arbitrary payload without type assertions, and its parsing limitations - no ES6 support - seem straightforward to work around)

**Comment by jmesserly** [comment]
@ochafik -- do you mind moving your checklist into the first message, or do you mind if I do it? GitHub has some special UI magic for checklists, but it only seems to kick in if they're in the initial bug report comment :)

**Comment by jacob314** [comment]
Some support for rest parameters would be very helpful for JS interop in general. This is one of the of edge cases we have to hack around today.

**Comment by ochafik** [comment]
@jacob314 I'm toying with a `@varargs` annotation for params + `varargs(args) -> ...args` argument transform in branch [runtime-varargs](https://github.com/dart-lang/dev_compiler/compare/runtime-varargs), WDYT?

**Comment by jacob314** [comment]
I'm open to adding '''@varargs''' to package:js with the other js interop specific annotations.

**Comment by ochafik** [comment]
@jacob314 Cool! Filed https://github.com/dart-lang/sdk/issues/24623 to track :-)

**Comment by jmesserly** [comment]
:tada:
