### ISSUE TITLE
Clarification about type checking nested Futures with --strong analysis

### ISSUE THREAD

**Issue by kulakowski** [dart-lang/dev_compiler#316]
Consider the following program, where `calculate` returns a `Future` in an `async` method body.

```dart
import 'dart:async';

class Foo {
  int x;
  Foo(this.x);
}

Future<int> loadInt(int x) {
  return new Future.sync(() => x);
}

Future<int> add(x, y) {
  return new Future.sync(() => x + y);
}

Future<int> calculate() async {
  final x = await loadInt(23);
  final y = await loadInt(19);
  return add(x, y);
}

main() {
  calculate().then(print);
}

---------------

$ dart foo.dart                                                                                                                              
42

$ dartanalyzer --strong foo.dart 
Analyzing [foo.dart]...
[error] Type check failed: add(x, y) (Future<int>) is not of type int (foo.dart, line 19, col 10)
1 error found.

```

Is this error correct with the spec you have? Is this error correct with the spec you wish you had?

If this is an error on my part, what is the correct way to collapse the `Future`? `await`ing on the returned function call?

cc @sethladd

**Comment by vsmenon** [comment]
This is very related to #228.  Currently, you'd have to write:

```dart
return await add(x, y);
```

but I think we could do better.  @leafpetersen - thoughts?

**Comment by leafpetersen** [comment]
I think the return case (this one) is easier to handle than the bind case (#228).  We should be able to accept this just fine, unless there are any codegen issues, which I wouldn't expect.  I believe that we allow the dual case (`return await 3;`).

**Comment by kevmoo** [comment]
Hitting this on pkg/test as well https://github.com/dart-lang/test/blob/ef2a46e32b7d8208ad8b3d9a6b0a8238d06ec939/lib/src/runner/engine.dart#L330

Returning `Future<RunnerSuite>` within an `async` method – getter error that it's not `RunnerSuite`

**Comment by jmesserly** [comment]
Might need a codegen tweak here to unwrap the Future, like we do immediately below that for `await`:
https://github.com/dart-lang/dev_compiler/blob/ed47365eaa6985199555289616b242d2c2878a43/lib/runtime/_generators.js#L54

But shouldn't be too bad.

**Comment by kevmoo** [comment]
I'd LOVE this to get fixed in the near term – there are a few projects for which this is the only strong-mode error
