### ISSUE TITLE
support `--version`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#321]
dev_compiler should support the `--version` cli option. Currently it prints:

```
dartdevc --version
Unhandled exception:
Uncaught Error: FormatException: Could not find an option named "version".
Stack Trace:
...
```

Also, the failure mode might just print a usage message :)

**Comment by jmesserly** [comment]
huh. Does the args package do that for invalid options?

**Comment by jmesserly** [comment]
not sure we can easily report --version, due to difficulty finding our own pubspec file :|

**Comment by devoncarew** [comment]
Yeah, it's awkward, but in tools that support `--version`, I've implemented it by some double-entry bookkeeping:

https://github.com/google/grinder.dart/blob/master/pubspec.yaml#L2

You can to update both the pubspec and a const in the source code -

**Comment by devoncarew** [comment]
Any objection if I add a `const` to somewhere like `lib/devc.dart` for the package version? This would need to be updated in tandem with the pubspec version on each release.

The other option I can think of is to copy the pubspec into the `lib/` dir (as a build process), and load the pubspec at runtime using the resource API.

**Comment by jmesserly** [comment]
> Any objection if I add a const to somewhere like lib/devc.dart for the package version? This would need to be updated in tandem with the pubspec version on each release.

works for me!
