### ISSUE TITLE
Can dev_compiler be run w/o generating output?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#329]
I.e., just used as a checker? I don't see a cli option for it.

**Comment by vsmenon** [comment]
Yes - it should do only that if you pass no arguments.  Note, we're moving all this logic into the analyzer proper though.

**Comment by devoncarew** [comment]
Cool, thanks for the info. I gave it a shot analyzing itself (w/o an `--out` flag).

**Comment by jmesserly** [comment]
yeah we don't self host yet. There are some issues that are annoying to fix without generic methods.
