### ISSUE TITLE
Casting JSDouble to int throws an Exception

### ISSUE THREAD

**Issue by adrian-castravete** [dart-lang/dev_compiler#335]
The following code:

```dart
int width, height, scale = 2;

width = window.innerWidth / scale as int;
height = window.innerHeight / scale as int;
```
throws this exception on chrome:

*Uncaught CastError: Casting value of type JSDouble to incompatible type int*

at the third line.

**Comment by vsmenon** [comment]
I believe that follows spec.  `/` returns a `double`.

If `window.innerWidth` is an integer, you can use the integer division operator `~/`.  Otherwise, you can use `(...).truncate()` to convert to int.

**Comment by vsmenon** [comment]
It looks like it is an `int` (wasn't sure whether subpixel rendering changed this):
https://api.dartlang.org/1.12.1/dart-html/Window/innerWidth.html

So, this should work:
```dart
int width, height, scale = 2;

width = window.innerWidth ~/ scale;
height = window.innerHeight ~/ scale;
```

**Comment by adrian-castravete** [comment]
Thank you very much for the reply! I will change accordingly, though it's a big wonky (*in my opinion*) how a JSDouble cannot be typecasted to an int. :smile_cat:

**Comment by lrhn** [comment]
In Dart, you can't *cast* something from one type to another. A value is either an `int` or a `double`, and "casting" (the `as` operator) doesn't change anything. It just checks whether the value is actually that type and throws if not. 
To convert a double into an integer, you can do `myDouble.toInt()`.

The `as` operator is pretty useless as defined, sadly. It's just a type check that you can use even in production mode.

**Comment by adrian-castravete** [comment]
I see! Thanks for the clarification. :smile:
