### ISSUE TITLE
static type of map literals as LinkedHashMap?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#337]
This program works in `dart --checked`:
```dart
import 'dart:collection';

foo(LinkedHashMap<String, String> map) {
  print(map);
}
bar(Map<String, String> map) {
  print(map);
}

main() {
  foo({'hi': 'foo'});
  bar({'hi': 'bar'});
}
```

However, we get a strong mode error:
```
[error] Type check failed: {'hi' : 'foo'} (Map<dynamic, dynamic>) is not of type LinkedHashMap<String, String>
```
It seems unfortunate that the stronger type bound is rejected. The code in question was using LinkedHashMap to enforce that it's ordered.

(aside: I'd have named this type OrderedMap or created an interface with that name, so the name specifies what it does for the user rather than how it's implemented. Similar SortedMap instead of SplayTreeMap. Anyway...)

The Dart language spec says the map is ordered:

> A map literal is ordered: iterating over the keys and/or values of the maps always happens in the order the keys appeared in the source code.

it also has the static type as Map<dynamic, dynamic>, but naturally, we're willing to tighten the types when it makes sense in Strong mode.

Thoughts? @leafpetersen @vsmenon

**Comment by vsmenon** [comment]
My initial reaction is to keep the error if the spec doesn't say `LinkedHashMap`.

**Comment by jmesserly** [comment]
so.... how do I make a LinkedHashMap, then?

**Comment by jmesserly** [comment]
the VM guarantees map literals make LinkedHashMap ... it would be a breaking change not to, because of checked mode. See example.

**Comment by jmesserly** [comment]
Also: normal analyzer also finds "no issues" because of assignability.

Here's my problem: if we *don't* interpret literals as LinkedHashMap (which they are: https://github.com/dart-lang/dev_compiler/blob/97d73b2da5baa09efd81d6db05163cb6ae273ec0/lib/runtime/_operations.js#L271) ... then I'm not sure how to create one. `new LinkedHashMap.from({'foo': 'bar', ...})` seems crazy. I can't imagine that passing a Dart readability review. Reviewer would rightly say "literals are already LinkedHashMap, that's an unnecessary copy".

**Comment by jmesserly** [comment]
(sort of related: https://github.com/dart-lang/sdk/issues/5611 -- the issue for SortedMap)

**Comment by leafpetersen** [comment]
You could insert an explicit cast around the literal to cast it to the implementation type.  Not entirely satisfactory.  I'm not sure that I'm super keen on code implicitly depending on the particular implementation type though - I'd be happier exposing it as OrderedMap, which reflects the specified behavior without committing to the implementation.

**Comment by jmesserly** [comment]
Meh, I guess we'll punt on this one.
