### ISSUE TITLE
publish 0.1.8?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#340]
It'd be great to have a new release of the dev_compiler to make sure I'm testing against the latest source. I see the last published version is `0.1.6`, but there's a github release for 0.1.7 (https://github.com/dart-lang/dev_compiler/releases/tag/0.1.7). So perhaps publishing as 0.1.8?

**Comment by vsmenon** [comment]
Ugh, 0.1.7 looks like my screw up.  

Sure, let's push out 0.1.8.  I can do this later today.

**Comment by devoncarew** [comment]
sounds great, thanks!

**Comment by vsmenon** [comment]
Published yesterday - sdk also rolled to new version.
