### ISSUE TITLE
task mode: field initializer inference is overriding explicit LHS type

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#350]
From @vsmenon's [comment](https://github.com/dart-lang/dev_compiler/issues/342#issuecomment-142446581):
> For the field type inference issue, we're seeing extra casts like:
> ```js
Zone._current = dart.as(zone, _RootZone);
```
> even though _current is declared in Dart as:
> ```dart
  static Zone _current = _ROOT_ZONE;
```
> It appears that the rhs expression type is incorrectly overriding the lhs declared type.

I've also seen this in 'casts in constant contexts' in checker test:
```dart
          class A {
            static const num n = 3.0;
            static const int i = /*info:AssignmentCast*/n;
            final int fi;
            const A(num a) : this.fi = /*info:DownCastImplicit*/a;
          }
          class B extends A {
            const B(Object a) : super(/*info:DownCastImplicit*/a);
          }
          void foo(Object o) {
            var a = const A(/*info:DownCastImplicit*/o);
          }
```

The `i = n` initializer fails with a static type error because it thinks `n` is `double` instead of `num` like it should be.

**Comment by jmesserly** [comment]
@vsmenon and I can confirm this is fixed by https://codereview.chromium.org/1370793002/

**Comment by leafpetersen** [comment]
https://codereview.chromium.org//1370793002 has landed.
