### ISSUE TITLE
task model: fails to correctly restore resolved AST after it is flushed from cache 

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#352]
this is showing up as failures in codegen_test, but only when they're all run together

The "resolved" AST is missing resolution info. This AST is always for a library that is shared by several tests. It only happens if the tests that use this shared library are run far apart (with hundreds of other tests in between).

Thanks to @bwilkerson we believe this may be happening in BuildCompilationUnitElementTask, specifically in the DeclarationResolver step that attempts to rehydrate a CompilationUnit from a cached CompilationUnitElement.

**Comment by jmesserly** [comment]
update: @vsmenon is working around this by having BatchCompiler track which test files we've compiled, so we don't try and get the resolved compilation unit for the shared library more than once.

**Comment by jmesserly** [comment]
fixed now?

**Comment by vsmenon** [comment]
I think this is fixed now - @stereotype441 had a fix.

**Comment by stereotype441** [comment]
Just to complete the paper trail, I believe this is the commit that fixed it: https://github.com/dart-lang/sdk/commit/e40b231771bfb24411dff6bba7178869636427cd
