### ISSUE TITLE
Flag for error on implicit dynamic

### ISSUE THREAD

**Issue by munificent** [dart-lang/dev_compiler#363]
We've discussed this a few times, but I figured I should file a tracking issue (if there isn't one already). I would like to be able to run the analyzer in strong mode with an option to tell me if the type inference engine ever can't pick a static type and ends up picking `dynamic` instead.

For example, I would expect to get an error here:

```dart
someFunction(a) => a.mysteryProperty;
```

But not here:

```dart
someFunction(dynamic a) => a.mysteryProperty;
```

**Comment by jmesserly** [comment]
Nice!

another variant, more for codegen, is "no dynamic invokes" ... this would allow us to omit some helper code. Possibly useful if you're trying to export a Dart library to JS and you want really small code size.

(of course, as far as code size is concerned, we have bigger fish to fry in the SDK libs)

**Comment by vsmenon** [comment]
Would you guys want an error here:
```
var list = [1, 2, 4];
```
?
In this case, the implicit dynamic is within the List type - `List<dynamic>`.  I believe TypeScript's no-implicit-any complains.

**Comment by vsmenon** [comment]
I filed a related bug for no reified dynamics: #365 
I suspect that would also eliminate dynamic invokes, but probably the hard way to get there.

**Comment by munificent** [comment]
Yes, I'd want an error there too.

**Comment by jmesserly** [comment]
this is moved to the SDK now https://github.com/dart-lang/sdk/issues/24712, https://github.com/dart-lang/sdk/issues/24267
