### ISSUE TITLE
add a shortcut to `--force-compile`?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#372]
Right now the cli options are:

```
--[no-]force-compile           Compile code with static errors
-f, --dump-info-file               Dump info json file (requires dump-info)
```

It would be nice to have a shorthand option for `force-compile`. Perhaps use `-f`? It's taken by `--dump-info-file` right now, but that's not frequently used, so appropriating its shorthand option might be ok.

**Comment by vsmenon** [comment]
I haven't used `-f` in ages.  I'd be fine with repurposing.

**Comment by jmesserly** [comment]
+1

**Comment by devoncarew** [comment]
(fixed)
