### ISSUE TITLE
Dart to js interop

### ISSUE THREAD

**Issue by Aetet** [dart-lang/dev_compiler#373]
Hello.
With new js-interop module we can easily convert modules between js to dart, but what about converting dart to js modules? What mechanism will be used for this?

**Comment by jmesserly** [comment]
Dev compiler will produce JS modules :)

**Comment by jmesserly** [comment]
FYI, this should be covered by https://github.com/dart-lang/dev_compiler/issues/34 as well as https://github.com/dart-lang/dev_compiler/issues/284 ... let me know if there's anything else we can help with
