### ISSUE TITLE
very long error messages when extracting text from the error location

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#377]
I see some _very_ long error messages, generally related to closures. DDC is using all the text in the error range as part of the message. Here's a sample long message:

> analysisServer.format(path, offset, end - offset, lineLength: _prefLineLength).then((FormatResult result) {if (result.edits.isEmpty) {if (!quiet) atom.notifications.addSuccess('No formatting changes.'); return false;} else {if (!quiet) atom.notifications.addSuccess('Formatting successful.'); applyEdits(editor, result.edits); editor.setSelectedBufferRange(new Range.fromPoints(buffer.positionForCharacterIndex(result.selectionOffset), buffer.positionForCharacterIndex(result.selectionOffset + result.selectionLength))); return true;}}).catchError((e) {if (e is RequestError) {if (!quiet) {atom.notifications.addError('Error while formatting', description: e.message);}} else {atom.beep(); _logger.warning('error when formatting: ${e}');} return false;}) (Future<dynamic>) **will need runtime check to cast to type Future<bool>**

Emphasis added at the end - that's the part of the error message that's the most actionable for the user, but it's hard to see given the volume of the previous text.

**Comment by jmesserly** [comment]
yeah, that drives me crazy too. I think it pastes the node.toString() in there.

**Comment by munificent** [comment]
This seems like a nice little starter bug for me to poke at.
