### ISSUE TITLE
Extension 'fields' cause a runtime error

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#378]
The following code triggers a runtime error in DDC:

```dart
import 'dart:collection';

class StringIterable extends IterableBase<String> {
  final Iterator<String> iterator = null;
}

main() => new StringIterable();
```

the problem is due to iterator being defined as a field (on the instance) as opposed to a getter/method (on the proto).  We get a type error that `iterator` is an undefined property on `defineExtensionMembers`.

```js
  class StringIterable extends collection.IterableBase$(core.String) {
    StringIterable() {
      this.iterator = null;
      super.IterableBase();
    }
  }
  dart.defineExtensionMembers(StringIterable, ['iterator']);
```

**Comment by vsmenon** [comment]
Per @jmesserly, we can fix this using our virtual field runtime helper.

**Comment by jmesserly** [comment]
we should definitely fix this DDC bug.

However, it's probably worth sending a bug report to this package. Having "iterator" be a final field violates the contract of the "iterator" getter:
https://api.dartlang.org/1.12.2/dart-core/Iterable/iterator.html
> Returns a new Iterator that allows iterating the elements of this Iterable.
> [...]
> Each time iterator is read, it returns a new iterator, which can be used to iterate through all the elements again. The iterators of the same iterable can be stepped through independently, but should return the same elements in the same order, as long as the underlying collection isn't changed.
