### ISSUE TITLE
source maps are surprisingly small

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#384]
When used with the atom plugin, source maps for dart files are surprisingly small:

```
{"version":3,"sourceRoot":"","sources":[],"names":[],"mappings":"","file":"entry.js"}
```

It doesn't look like they have line number info.

**Comment by vsmenon** [comment]
CL out for this:

https://codereview.chromium.org/1425313003/

**Comment by devoncarew** [comment]
They're bigger now :)

> {"version":3,"sourceRoot":"","sources":["../entry.dart"],"names":["print","registerPackage"],"mappings":";;;;;;;;;AAOA,kBAAO;AACL,IAAA,AAAAA,UAAK,CAAC,4BAA4B,CAAC;AAAC,AASpC,IAAA,AAAAC,oBAAe,CAAC,mCAAuB,CAAC;AAAC,GAE3C;;AAAA","file":"entry.js"}

Thanks!
