### ISSUE TITLE
TypeError when compiling dartdevc output with babel

### ISSUE THREAD

**Issue by jonaskello** [dart-lang/dev_compiler#385]
$ babel --version
6.1.18 (babel-core 6.1.19)
$ dartdevc --version
dartdevc version 0.1.10

To reproduce:

.babelrc
```json
{
  "presets": ["es2015", "stage-2"]
}
```

main.dart
```dart
void main() {
  print("Hello world");
}
```

```bash
$ dartdevc -o out main.dart
$ babel out --out-dir out_es5

TypeError: out/dev_compiler/runtime/dart/async.js: Duplicate declaration "timeout"
  664 |         let timer = null;
  665 |         let zone = null;
> 666 |         let timeout = null;
      |             ^
  667 |         function onData(event) {
  668 |           dart.as(event, T);
  669 |           timer.cancel();
    at File.buildCodeFrameError (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:408:15)

```

**Comment by vsmenon** [comment]
Hmm, looks like a local variable is shadowing the function name in the generated async.js:

```javascript
      timeout(timeLimit, opts) {
        let onTimeout = opts && 'onTimeout' in opts ? opts.onTimeout : null;
        dart.as(onTimeout, dart.functionType(dart.void, [EventSink]));
        let controller = null;
        let subscription = null;
        let timer = null;
        let zone = null;
        let timeout = null;
        ...
```

**Comment by vsmenon** [comment]
This is coming from the following Dart code: [https://github.com/dart-lang/dev_compiler/blob/ed47365eaa6985199555289616b242d2c2878a43/tool/input_sdk/lib/async/stream.dart#L1209]:

```dart
  Stream timeout(Duration timeLimit, {void onTimeout(EventSink sink)}) {
    StreamController controller;
    // The following variables are set on listen.
    StreamSubscription<T> subscription;
    Timer timer;
    Zone zone;
    Function timeout;
```

**Comment by jmesserly** [comment]
if it works in real ES6 implementations, it's likely a Babel bug.

**Comment by vsmenon** [comment]
It works fine in Chrome.  That's consistent with my understanding of let block scoping.

@jonaskello Can you file this on Babel?

We can modify the Stream timeout function to avoid this - let us know.

**Comment by jonaskello** [comment]
@vsmenon Do you have a link to the part of the ES6 that specification that states this is valid? I can file it on Babel, just want to be able to include a reference to the spec.

**Comment by vsmenon** [comment]
@jonaskello 

As I understand it, a function has its own `LexicalEnvironment` and corresponding `EnvironmentRecord`.  Creating a new binding only checks for duplicates in that same `EnvironmentRecord` - not in any containing `LexicalEnvironment` / `EnvironmentRecord`:

[http://www.ecma-international.org/ecma-262/6.0/#sec-declarative-environment-records-createmutablebinding-n-d]

**Comment by jonaskello** [comment]
@vsmenon You're right, it's a confirmed bug in babel:

https://github.com/babel/babel/issues/2684
