### ISSUE TITLE
set up travis to test Atom

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#395]
we broke the Atom plugin with recent DDC changes. it'd be good to have Travis set up to catch this next time.

**Comment by ochafik** [comment]
*Ideally*, we could come up with a DDC version of [electron-accelerator](https://github.com/ammeep/electron-accelerator), which would be exercised in travis as an end-to-end test for electron-based apps, WDYT @devoncarew ?

**Comment by devoncarew** [comment]
Hmm, I'm not familiar with it. The atom team uses travis for all their automated testing (module windows - they use appveyor for that). We should be able to get setup in travis, no problem.

**Comment by vsmenon** [comment]
I've been experimenting with karma-electron-launcher to just run our existing tests on Electron:

https://github.com/dart-lang/dev_compiler/compare/electron?expand=1

It seems to choke on too many network requests (i.e., too many script tags), so I've had to concat the language tests into a single file.  That seems to work on my Mac.
