### ISSUE TITLE
Atom plugin broken

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#396]
It looks like the destructuring commit broke Atom (https://github.com/dart-lang/dev_compiler/commit/c9d909ced98dea2aefe20322a59d18fbab2d93b2) ... probably because they're on an older version of Chrome.

I think the new code has fallback logic already in some cases, so we could likely add a flag to turn that on always.

CC @devoncarew @vsmenon

**Comment by ochafik** [comment]
Sent a PR with a flag that disables destructuring (and filed #397 to track multiple runtimes).

@devoncarew, if running build_sdk.sh as part of the plugin's build is not an option, then I can flip `_DESTRUCTURE_NAMED_PARAMS_DEFAULT` to `false` and we'll re-enable it later.

**Comment by devoncarew** [comment]
> if running build_sdk.sh as part of the plugin's build is not an option

It would be a lot more convenient to not have to do rebuilt it :)

**Comment by vsmenon** [comment]
@devoncarew  It looks like destructuring is behind a separate "--harmony-destructuring" in Chrome 45.  Is that possible to turn on?

If not (or it doesn't work), we can disable it by default until Atom rolls forward.

@ochafik does anything break *without* destructuring?

**Comment by ochafik** [comment]
Destructuring fixes a pattern that breaks Closure's advanced mode, but it's not ready yet anyway, so can definitely compile the sdk without it (it will just grow 1% bigger ;-)).

If that's an acceptable middle ground, I suggest building the sdk without it, but leaving it as a default (and have the Atom build to add the `--no-destructure-named-params` flag), this way the generated code looks nicer by default.

**Comment by devoncarew** [comment]
sgtm!

I tried adding this to my start-up script:

```
var v8 = require('v8');
v8.setFlagsFromString('--harmony-destructuring');
```

which changed the failure mode, but did hit another exception.

**Comment by vsmenon** [comment]
@devoncarew Let us know if this is still an issue.  Destructuring has been disabled by default.  

We're also now regressing on Electron (the Chrome 47 version - non-trivial to move that earlier as our karma/travis version doesn't make it easy to run older Electron with --harmony).  This would have caught the destructuring issue early.

**Comment by devoncarew** [comment]
Thanks! Will re-test w/ the latest DDC.

**Comment by jmesserly** [comment]
tentatively closing, let us know if it reoccurs!

**Comment by devoncarew** [comment]
Sorry, yup, it's working for me again.
