### ISSUE TITLE
publish 0.1.13

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#400]
A tracking issue to publish the latest from master. This will capture an analyzer fix and a new option to disable using JS destructuring params.

**Comment by devoncarew** [comment]
friendly ping :) Is master ready to go out?

**Comment by vsmenon** [comment]
Should be - I'll do it now.

**Comment by vsmenon** [comment]
Done: https://pub.dartlang.org/packages/dev_compiler

**Comment by devoncarew** [comment]
Thanks!
