### ISSUE TITLE
encountered an exception when calling JSON. parse

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#408]
More details in this FYI PR: https://github.com/dart-lang/dev_compiler/pull/404

Essentially I think the dart:convert JSON object was shadowing window's JSON. The compiled code was trying to call `(window.)JSON.parse`, but was getting the dart:convert object instead.

**Comment by vsmenon** [comment]
Do you have a pointer to the code / call to dart:convert that was triggering this bug?

**Comment by devoncarew** [comment]
I _think_ it was here: https://github.com/dart-atom/atom.dart/blob/master/lib/atom.dart#L86. That `atom.dart` package is called from the flutter plugin: https://github.com/flutter/atom-flutter. It has some of the build process to compile with ddc, but needs a little bit of setup to switch over to it.

**Comment by vsmenon** [comment]
Here's a repro:

```dart
import 'dart:convert' show JSON;

void main() {
  var str = '{"hello": [1, 2, 3], "world": [4, 5 ,6]}';
  var data = JSON.decode(str);
  print(data);
}
```
