### ISSUE TITLE
expose more of `dart:html`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#412]
Here are some things I've run into:

- `window.screen` (seems to be `null` - I'd like to get window.width and window.height)
- `window.navigator.language`
- `document.documentElement.clientWidth`, `document.documentElement.clientHeight` (I see 'Could not instantiate HTMLHtmlElement' at runtime)

**Comment by vsmenon** [comment]
devon: is clientWidth / clientHeight working for you?  those getters are on Element, so it should work despite the warning message.  (it's instantiating HTMLElement instead of HTMLHtmlElement.)

**Comment by devoncarew** [comment]
I can check. I think I assumed they weren't because of the runtime message.

**Comment by vsmenon** [comment]
it's pretty small, so i'll just go ahead and add it in.

**Comment by vsmenon** [comment]
Fix pending:

https://codereview.chromium.org/1607073002/

**Comment by devoncarew** [comment]
:+1:, these are available to me now
