### ISSUE TITLE
Runtime types appear to be dropped for Map literals

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#415]
Repro:
```
var map = <String>{'foo': 'bar'};
```
shows up as runtime type of _LinkedHashMap<dynamic, dynamic>
writing new Map<String, String> works as expected.

**Comment by jmesserly** [comment]
Did you forget to put the second type arg?
```dart
main() {
  print((<String>{'foo': 'bar'}).runtimeType);
  print((<String, int>{'foo': 'bar'}).runtimeType);
}
```
on Dart VM yields:
```
_InternalLinkedHashMap
_InternalLinkedHashMap<String, int>
```

**Comment by jmesserly** [comment]
dartanalyzer on that:
```
[warning] Map literal requires exactly two type arguments or none, but 1 found (/Users/jmesserly/scratch/test.dart, line 2, col 10)
```

**Comment by jmesserly** [comment]
I'm guessing that this is not a bug, but let me know if I'm missing something.

**Comment by jmesserly** [comment]
just confirmed we do promote that warning to an error, so DDC won't compile that example unless force compile is set.

However, we seem to have the bug with the second example (`<String, String>{'foo': 'bar'}`).

**Comment by jmesserly** [comment]
looks like we never implemented this, there's an old TODO in the code about it. fix on the way

**Comment by jmesserly** [comment]
oops, I had a CL, but working on merging it against the new way runtime libs are written. It's getting close!
