### ISSUE TITLE
Clarify docs on rules for normal mode types on generic methods

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/dev_compiler#419]
From the docs it says that
```
/*=T*/ create/*<T extends Foo>*/(/*=T*/ foo) { ... }
```

is equivalent to 

```
dynamic/*=T*/ create/*<T extends Foo>*/(dynamic/*=T*/ foo) { ... }
```

There is no indication whether I can use anything other than dynamic for normal mode. e.g.

```
Foo/*=T*/ create/*<T extends Foo>*/(Foo/*=T*/ foo) { ... }
```

**Comment by jmesserly** [comment]
Good catch!

> There is no indication whether I can use anything other than dynamic for normal mode.

Yeah, we should fix the docs. Definitely can use another type. Your last code snippet is a perfect example of why it is useful. :)

**Comment by Andersmholmgren** [comment]
\o/ Looking forward to taking this for a spin. It's been my no.1 most wanted dart features for years.

**Comment by munificent** [comment]
Github didn't auto-close this, but I assume it's done now. :)

**Comment by jmesserly** [comment]
@vsmenon needs to review the pull request https://github.com/dart-lang/dev_compiler/pull/420 :)

**Comment by jmesserly** [comment]
or you could @munificent :)

**Comment by munificent** [comment]
Oops, sorry. Didn't see this yesterday.
