### ISSUE TITLE
Ordering issue in codegen

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#427]
@jmesserly If I compile and run order1.dart below, I hit an error when Foo is loaded.  I'm actually trying expose a different bug (on `main`) here, but it's not even getting that far.  Any ideas?

order1.dart:
```dart
import 'order2.dart';

class Foo<T> extends Bar<T> {
  static int x = 24;
  static int y = 42;
  static int z = 54;
}


void main() {
  var b = new Bar();
  print(Bar.c);
}
```

order2.dart:
```dart
import 'order1.dart';

class Bar<T> {
  static int a = 24;
  static int b = 42;
  static int c = 54;

  Foo<T> foo;
}

class Baz<T> extends Foo<T> {
}
```

**Comment by jmesserly** [comment]
What's the error? :)

**Comment by jmesserly** [comment]
it looks like the known problem of static fields on a lazy generic class:
```dart
  dart.defineLazyClassGeneric(exports, 'Foo', {get: Foo$});
  exports.Foo.x = 24;
  exports.Foo.y = 42;
  exports.Foo.z = 54;
```

**Comment by vsmenon** [comment]
```
order1.js:10 Uncaught TypeError: order2.Bar$ is not a function
```

Here's the generated code for order1:

```
dart_library.library('order1', null, /* Imports */[
  'dart/_runtime',
  'dart/core'
], /* Lazy imports */[
  'order2'
], function(exports, dart, core, order2) {
  'use strict';
  let dartx = dart.dartx;
  const Foo$ = dart.generic(function(T) {
    class Foo extends order2.Bar$(T) {
      Foo() {
        super.Bar();
      }
    }
    return Foo;
  });
  dart.defineLazyClassGeneric(exports, 'Foo', {get: Foo$});
  exports.Foo.x = 24;
  exports.Foo.y = 42;
  exports.Foo.z = 54;
  function main() {
    let b = new order2.Bar();
    core.print(order2.Bar.c);
  }
  dart.fn(main, dart.void, []);
  // Exports:
  exports.Foo$ = Foo$;
  exports.main = main;
});
//# sourceMappingURL=order1.js.map
```

**Comment by jmesserly** [comment]
yeah, that's what I'd expect. we're forcing Foo to evaluate eagerly on `exports.Foo.x = 24;` which forces order2, which isn't available yet.

**Comment by jmesserly** [comment]
The bug here is we shouldn't generate Foo's static fields like that.

**Comment by vsmenon** [comment]
Yup, that's exactly what's happening.  Throwing on `exports.Foo.x = 24`.

**Comment by vsmenon** [comment]
Related to #371

**Comment by jmesserly** [comment]
fyi, this looks like a really easy fix. Static fields just need to be pulled out of the "loader" system, back to _finishClassMembers. There might be a slight readability hit, but I doubt it will be bad.

The only reason static fields are handled that way, is cases like:
```Dart
class Foo {
  static int foo = Bar.bar + 100;
  static int baz = 42
}
class Bar {
  static int bar = Foo.baz + 1000;
}
```
Having static fields independent of their class allows better ordering. It's pretty obscure though, doubt it comes up much in practice. We could try and bring it back after we purge the lazyClass stuff.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1636233002/
