### ISSUE TITLE
Reduce severity of missing switch cases

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dev_compiler#428]
Missing switch cases are classified as errors. However, they do not impact the quality of the resulting JS. Let's reduce it to a warning.

**Comment by jmesserly** [comment]
CC: @munificent 

I dug in a bit, and this looks like a double bug: one for DDC and one for Analyzer.

First problem: DDC promotes all analyzer warnings to errors. We need to be more careful about which ones.

Second problem, in Analyzer:
```dart

  /**
   * Enum proposal: It is a static warning if all of the following conditions
   * hold:
   * * The switch statement does not have a 'default' clause.
   * * The static type of <i>e</i> is an enumerated typed with elements
   *   <i>id<sub>1</sub></i>, &hellip;, <i>id<sub>n</sub></i>.
   * * The sets {<i>e<sub>1</sub></i>, &hellip;, <i>e<sub>k</sub></i>} and
   *   {<i>id<sub>1</sub></i>, &hellip;, <i>id<sub>n</sub></i>} are not the
   *   same.
   *
   * Parameters:
   * 0: the name of the constant that is missing
   */
  static const CompileTimeErrorCode MISSING_ENUM_CONSTANT_IN_SWITCH =
      const CompileTimeErrorCode(
          'MISSING_ENUM_CONSTANT_IN_SWITCH',
          "Missing case clause for '{0}'",
          "Add a case clause for the missing constant or add a default clause.");
```

Note the mismatch between the comment (warning) and the error level. I checked and 3rd ed Dart spec says it should be a warning:
> It is a static warning if all of the following conditions hold:
> • The switch statement does not have a default clause.
> • The static type of e is an enumerated typed with elements id1, . . . , idn.
> • The sets {e1, . . . , ek} and {id1, . . . , idn} are not the same.
> In other words, a warning will be issued if a switch statement over an enum is
not exhaustive.

**Comment by jmesserly** [comment]
I filed https://github.com/dart-lang/sdk/issues/25576 for the Analyzer bug

**Comment by munificent** [comment]
I'd be happy to take a look at this. I'll follow up on the analyzer one first.

**Comment by jmesserly** [comment]
this was fixed a while ago

**Comment by munificent** [comment]
Sorry I forgot to close this!
