### ISSUE TITLE
Support modular build from command line

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#439]
We should be able to do something like:

```
> ddc -o foo.js --deps angular2.dart:somecomponent.dart foo.dart bar.dart
```

to build an app consisting of `foo.dart` and `bar.dart` without generating code for its dependencies (e.g., in this case angular2.dart and somecomponent.dart).

**Comment by jmesserly** [comment]
Nice! Probably can refactor BatchCompiler to work this way. At some point I tried to disentangle compiling and linking a bit but didn't get too far.

**Comment by vsmenon** [comment]
BTW, an explicit motivation here is to make it easy to integrate with existing build systems like make or [bazel](http://bazel.io/).

@keertip

**Comment by keertip** [comment]
Yes, this is what we would like to see - generate a single js file for a set of dart files.

**Comment by donny-dont** [comment]
My thought for this was that if I have a dart package I could compile that out with DDC into something one of the many many package managers for the JS world could digest. So lets say I have a pubspec that was the following.

```
name: bar
dependencies:
  foo: ^0.1.0
```

The compilation would not bother compiling out foo but instead would just compile out bar so then I could push bar to the JS package manager. In the end the user could take all those packages and compile them out using babel or whatever to create the final product.

**Comment by jmesserly** [comment]
this is now done.

**Comment by donny-dont** [comment]
:confetti_ball: awesome work @jmesserly!
