### ISSUE TITLE
Tip-of-tree analyzer breaking codegen tests

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#443]
If I add a dependency_override to point directly at analyzer tip-of-tree in the SDK, I get the following failures in the codegen tests.

```
00:58 +3196 -18: codegen dartdevc test/codegen/language string_interpolation_newline_test.dart     
  The null object does not have a getter 'library'.
  
  NoSuchMethodError: method not found: 'library'
  Receiver: null
  Arguments: []
  dart:core                                                 Object.noSuchMethod
  package:dev_compiler/src/codegen/js_codegen.dart 3580:40  JSGenerator.generateLibrary
  package:dev_compiler/src/compiler.dart 185:16             BatchCompiler._processPending
  package:dev_compiler/src/compiler.dart 154:5              BatchCompiler._compileSource
  package:dev_compiler/src/compiler.dart 145:5              BatchCompiler._compileFromUri
  package:dev_compiler/src/compiler.dart 133:5              BatchCompiler.compileFromUriString
  test/codegen_test.dart 91:14                              main.compile
  test/codegen_test.dart 176:28                             main.<fn>.<fn>
```

It's failing in this code:

```dart
  String generateLibrary(LibraryUnit unit) {
    // Clone the AST first, so we can mutate it.
    unit = unit.clone();
    var library = unit.library.element.library;
    ...
```

It appears that `unit.library.element` is returning `null`.  (I verified by breaking the two `library` getters onto separate lines.)

@jmesserly @bwilkerson Any idea why this would be null now?

**Comment by vsmenon** [comment]
One other stack trace I missed.  These will block our next roll to the analyzer (not urgent yet).

```
The null object does not have a getter 'types'.

NoSuchMethodError: method not found: 'types'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      findFieldsNeedingStorage (package:dev_compiler/src/codegen/js_field_storage.dart:17:34)
#3      JSGenerator.generateLibrary (package:dev_compiler/src/codegen/js_codegen.dart:3582:18)
#4      BatchCompiler._processPending (package:dev_compiler/src/compiler.dart:185:16)
#5      BatchCompiler._compileSource (package:dev_compiler/src/compiler.dart:154:5)
#6      BatchCompiler._compileFromUri (package:dev_compiler/src/compiler.dart:145:5)
#7      BatchCompiler.compileFromUriString (package:dev_compiler/src/compiler.dart:133:5)
#8      Object&ListMixin.forEach (dart:collection/list.dart:63)
#9      BatchCompiler.run (package:dev_compiler/src/compiler.dart:124:20)
#10     compile (package:dev_compiler/src/compiler.dart:69:73)
#11     main (file:///Users/vsm/git/dev_compiler/bin/dartdevc.dart:49:10)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by vsmenon** [comment]
The second stack trace appears to be the same underlying issue - a library with a null `element`.

**Comment by bwilkerson** [comment]
No, I'm not sure why, but it looks to me that it has to have happened in BatchCompiler._processPending(). Earlier in the method (before the call to `generateLibrary`), there's the line:

    var library = unit.library.element.enclosingElement;

So at that point the unit's library had a non-null element. Not sure what happened to cause that to change by the time `generateLibrary` is called.

**Comment by jmesserly** [comment]
It sounds like we're not getting back a fully resolved AST? Or it got unresolved somehow, maybe by caching & re-resolution?

**Comment by jmesserly** [comment]
Aside: probably not related, but I'm in the process of seriously cleaning up that code. BatchCompiler is almost totally rewritten to process library cycles atomically.

**Comment by vsmenon** [comment]
Hmm, I added a couple asserts here.  The second one is failing.  It looks like ResolutionCopier is failing to copy.

```dart
  static CompilationUnit _cloneUnit(CompilationUnit oldNode) {
    assert(oldNode.element != null);
    var newNode = oldNode.accept(new _AstCloner());
    ResolutionCopier.copyResolutionData(oldNode, newNode);
    assert(newNode.element != null);
    return newNode;
  }
```

@bwilkerson - did anything change here?

**Comment by bwilkerson** [comment]
Not as far as I can remember. The method ResolutionCopierTest.test_visitCompilationUnit() appears to be testing exactly this case.

**Comment by vsmenon** [comment]
This appears to be related to the cloning of tokens in `AstCloner`.  `copyResolutionData` is failing because the tokens in `oldNode` and `newNode` do not match.

**Comment by bwilkerson** [comment]
@scheglov recently made the change that caused tokens to be copied. I'm guessing we just need to update ResolutionCopier to compare tokens differently.

**Comment by vsmenon** [comment]
@scheglov 

This problem appears to be in `AstCloner.visitCompilationUnit`:

```dart
  @override
  CompilationUnit visitCompilationUnit(CompilationUnit node) {
    ScriptTag scriptTag = cloneNode(node.scriptTag);
    List<Directive> directives = cloneNodeList(node.directives);
    List<CompilationUnitMember> declarations = cloneNodeList(node.declarations);
    Token endToken = cloneToken(node.endToken);
    Token beginToken = scriptTag?.beginToken ??
        (directives.isEmpty ? null : directives.first.beginToken) ??
        (declarations.isEmpty ? null : declarations.first.beginToken) ??
        endToken;
```

The cloned `beginToken` is skipping over comments in the original node.  FWIW, `cloneTokens` is set to `false` in this case.

**Comment by vsmenon** [comment]
If I replace that last line with:

```dart
Token beginToken = cloneToken(node.beginToken);
```

then, the resolution data is copied over.

**Comment by scheglov** [comment]
https://codereview.chromium.org/1686653003

**Comment by vsmenon** [comment]
This is fixed.
