### ISSUE TITLE
possible issue with user-defined runtimeType on extension interfaces

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#451]
I'm not sure if the following program will work:
```dart
class MyIterable extends Iterable {
  get runtimeType => String; // Take that, type system! ;-)
}
main() {
  Object o = new MyIterable();
  print(o.runtimeType); // should be 'String'
}
```

The bug isn't in how we generate JS, but in our hand coded runtime helper for "runtimeType". We'll call "obj.runtimeType" instead of "obj[dartx.runtimeType]".

Maybe this *does* work, because `[dartx.runtimeType]` is a trampoline that maps to `runtimeType`? Anyway -- something to investigate. Properties on Object are in a bit of an odd place.

**Comment by vsmenon** [comment]
This should work fine now.  For Object properties, we dispatch a little differently.  We generate either

```dart
o.runtimeType
```

if we know `o` is non-null and not a native JS object.  Otherwise, we generate:

```dart
dart.runtimeType(o)
```

**Comment by jmesserly** [comment]
yeah, but how does `dart.runtimeType` itself work? :)

Does MyIterable get generated with a `get runtimeType() { return core.String; }` getter?

Maybe it's okay, but consider the List case. It means we might shadow a name defined on Array.

**Comment by jmesserly** [comment]
Oh, toString has the same problem, and noSuchMethod too.

@vsmenon had an interesting idea -- since most call sites are fine, we could just go to the extension type and find the method with its Dart name, then use Function.prototype.call to invoke them.

**Comment by jmesserly** [comment]
p2 unless this comes up. I suspect our toStrings are broken though (e.g. on List). I'd swear we had another bug for this but I can't find it.

**Comment by jmesserly** [comment]
I believe this was fixed as part of another change. We now dispatch these differently if it's an extension type.
