### ISSUE TITLE
Fast transpilation mode for development? (without analysis)

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#457]
I know DDC precisely adds more types, better static checks, etc, but I think it would be great to have a draft compilation mode for development that wouldn't even need analyzer or analyzer summaries for incremental compilation:
- Assume all types are dynamic (for codegen purposes, not for runtime checks),
- Use dcall/dsend *everywhere* (how much bigger would the code be? might be okay even if 5x...),
- Only parse files without analyzing them,
- Still generate good sourcemaps
- Still emit type guards, systematic notNull checks, etc

That would allow us to introduce instant transpile-on-save behaviour (like TypeScript), lazy file-by-file transformer, etc.

Not sure how feasible it is, WDYT?

**Comment by jmesserly** [comment]
> I think it would be great to have a draft compilation mode for development that wouldn't even need analyzer or analyzer summaries for incremental compilation

I don't understand what the user benefit is? Analyzer is fast. This can be seen in server mode. The only problem we have is cold starts -- and summaries are almost here to fix that.

> Not sure how feasible it is, WDYT?

I don't think it would be feasible. Analyzer is our entire front end: scanner, parser, resolver (import resolution, name binding, error checking). Type checking costs very little of that.

**Comment by jmesserly** [comment]
FYI, Analyzer has summary support now, yay. I think we can tentatively close this
