### ISSUE TITLE
strong mode issue in collection and string_scanner

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#461]
Probably not the best place to track this, but `package:collection` and `package:string_scanner` have some strong mode issues: http://dart-atom.github.io/dartlang/entry_dart_results.html.

**Comment by vsmenon** [comment]
Here's a fix for string_scanner:

https://codereview.chromium.org/1722603005/

**Comment by devoncarew** [comment]
closing as probably obsolete
