### ISSUE TITLE
null inference does not correctly handle catch body

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#463]
```dart
main() {
  String x = '';
  try {} catch(e) {
    x = null;
  }
  print(x + '42');
}
```
It's supposed to generate a null check for "x", but it doesn't:
```js
  function main() {
    let x = '';
    try {
    } catch (e) {
      x = null;
    }

    core.print(x + '42');
  }
```

**Comment by jmesserly** [comment]
Discovered while I was refactoring the nullable inference code.

**Comment by jmesserly** [comment]
This one is pretty easy. It's just not visiting the catch body.

There's an issue though, in that all variable initializers are going to get visited at least twice, when only one visit should be required. That's what I had originally set out to refactor.

**Comment by jmesserly** [comment]
here's an example of a case that works, but is rather lucky :
```dart
main() {
  String x = '';
  String y = (x = null);
  print(x + '42');
  print(y + '42');
}
```
It ends up recording "y = (x = null)", and it also ends up recording "x = null". A chain of assignments like `a = b = c = d = e` will record:

- a = b = c = d = e
- b = c = d = e
- c = d = e
- d = e

Then we'll visit all of those RHS to determine if they are nullable, and to record any dependency between variables. That said, we're actually okay for now on performance, as _isNullableExpression doesn't handle AssignmentExpression. So each of those bails out quickly. But if it did, we might be in some performance trouble.

**Comment by jmesserly** [comment]
Few other things I've noticed:
* pre/postfix code was not kicking in (isAssignmentOperator is never true for `++`/`--`, isIncrementOperator is the correct check). I don't think this will affect things much, as usually it has no effect on nullability. The one case it would matter is user-defined operators.
* variable initializers weren't visited by the main assignment collector. This could lead to problems if the initializer contained a lambda--I don't think any of that nested lambda will be visited.

While we have the potential future problem of visiting initializers too much (see comment above), at the moment I want to get it to visiting the whole tree so we know all locals are handled. I'm tempted to flip the polarity -- right now, it computes the "nullable" set, and anything unknown is considered not-null. I'd feel more comfortable with the reverse--that way our analysis is conservative.

**Comment by ochafik** [comment]
For nested assignments, I guess when encountering `a = b = c` we could detect that the rhs is an assignment, then only record `a = b` and recurse on rhs, WDYT?

Re/ pre/postfix expressions, they go through a different code path than assignment ops (_LocalAssignmentsVisitor.visitPostfixExpression/visitPrefixExpression vs. visitBinaryExpression).

Variable initializers should be recursed onto in _LocalAssignmentsVisitor.visitVariableDeclaration, and constructor field initializers should also be recursed into.

Re/ invert the nullability analysis, not sure how trivial it is... I'd be happier fixing bugs as they're encountered for now :-)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1751963002/ fixes some.

Few things I didn't get to yet:
* smarter nested assignments
* only running analysis at function/method level
* isNullable can be improved in various ways, e.g. it doesn't seem to handle InstanceCreationExpression, identical at the moment
* we could also know that a lot of SDK methods won't return null. But non-null types is probably the right way to approach that.
