### ISSUE TITLE
incorrect generation of DivElement.append with transformer

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#464]
From @ferhatb [comment](https://github.com/dart-lang/dev_compiler/issues/252#issuecomment-189525666):
> Looks like DDC currently generates code with "normal" method names instead of symbols / computed properties, when trying to call methods on Element:
```dart
import 'dart:html';
main() {
  var e = new DivElement();
  e.append(null); // compiled to e.append, but should be e[dart.dartx.append]
}
```

**Comment by jmesserly** [comment]
CC @vsmenon

**Comment by jmesserly** [comment]
FYI -- I cannot reproduce this on master. Here is what I get (./bin/dartdevc.dart -o ~/tmp/ test.dart):
```js
  function main() {
    let e = html.DivElement.new();
    e[dartx.append](null);
  }
```
Perhaps we need to push out a new build?

@vsmenon's change to HTML was recent-ish. Before that we used a wrapper dart:html as a temporary workaround, which would not have used extension methods. That's my best guess.

Tentatively closing but let me know if you are seeing this on master/next DDC release.

**Comment by ochafik** [comment]
Reopened as transformer-specific issue. On first look, might be that the sdk is resolved to the system sdk. Lowered priority as it's just happening for the transformer.

**Comment by jmesserly** [comment]
I'm guessing we can close this one for now. When we reimplement on top of the new build package, we should be able to address this. (the root cause is probably https://github.com/dart-lang/dev_compiler/issues/478)
