### ISSUE TITLE
Typing of string concatenation broken

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/dev_compiler#465]
Getting the following error:
```
_isolate_helper.js:655 Uncaught TypeError: ("" + "").+ is not a function
```

From the following code:
```dart
main() {
  print('' '' + '');
}
```

(generated code refers to + method as `['+']`)

**Comment by ferhatb** [comment]
cc/ @ochafik

**Comment by jmesserly** [comment]
> (generated code refers to + method as ['+'])

That's intended for Dart types. However String should be using an extension method.

Looks to be several bugs here. For one, it should've used JS + directly so no JS implicit conversions are possible in this case.

FWIW, the output I see is:
```dart
  function main() {
    core.print(('' + '')['+'](''));
  }
```

**Comment by vsmenon** [comment]
Looks like cloning / resolution copy is not preserving the type on an AdjacentStrings node.  This should be fixed upstream, but I can add a temp fix in ddc.

**Comment by vsmenon** [comment]
Local fix:

https://codereview.chromium.org/1756563002/

**Comment by ochafik** [comment]
Thanks guys!
