### ISSUE TITLE
hello_app broken (dart:html regression)

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#467]
Repro:
```
cd test/transformer/hello_app
pub upgrade
pub serve
```
Then open [http://localhost:8080/hello_app/web/](http://localhost:8080/hello_app/web/)

Expected: 'Hello, World' on the page
Actual: empty page
(note: does print the message well on the console, which means it's really a problem with [document.body.innerHtml = message](https://github.com/dart-lang/dev_compiler/blob/222fbdc73ec7c8d283ea053fbb7ab0e549814d39/test/transformer/hello_app/web/main.dart#L10)

Note: the disabled transformer_e2e_test would have caught that, and probably can still be used to git-bissect the regression (`pub run test test/transformer_e2e_test.dart`)

**Comment by vsmenon** [comment]
I was hitting an issue with innerHtml independently yesterday.  As best as I can tell, innerHtml has been broken since I landed the full dart:html - at least my local test.

That's odd as the e2e test was still running and passing locally for me for a bit after landing the new dart:html.  We only disabled due to travis occasionally hanging.

**Comment by vsmenon** [comment]
When I run the transformer test locally, I get:

```
pub run test test/transformer_e2e_test.dart
00:00 +0: DDC transformer in pub serve serves functional hello world app                           # [e2e] Awaiting Selenium...
00:00 +0 -1: DDC transformer in pub serve serves functional hello world app                        
  Bad state: Pub get failed: The pubspec for dev_compiler 0.1.17 from path has version 0.1.21
```

Any ideas what that's about?

**Comment by ochafik** [comment]
Oh, that's a bug in the e2e test, it needs to run `pub upgrade` instead of `pub get` ([at this line](https://github.com/dart-lang/dev_compiler/blob/master/test/transformer_e2e_test.dart#L72)). Only happens locally, fixed in https://github.com/dart-lang/dev_compiler/pull/468

**Comment by vsmenon** [comment]
Okay, I'm looking into the `innerHtml` issue:

https://github.com/dart-lang/dev_compiler/issues/469

**Comment by jmesserly** [comment]
Hmm. That might be a `pub get` bug. There shouldn't be a difference between "get" and "upgrade", other than upgrade trying to find the very latest version. @munificent might know?

**Comment by ochafik** [comment]
This is getting worse: still no innerHtml display (#469 not fixed?), and now even the `print` statement is broken (just prints `undefined`).

**Comment by vsmenon** [comment]
This is a transformer issue.  Merging into #478
