### ISSUE TITLE
Element.innerHtml is broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#469]
It appears to crash in validation code.  It also appears to have regressed with the recent `dart:html` overhaul.

**Comment by ochafik** [comment]
Note that while it doesn't crash, it doesn't seem to work either.
```
import 'dart:html';
main() {
  document.body.innerHtml = "Hello?";
}
```

**Comment by vsmenon** [comment]
@ochafik the above is working fine for me.  E.g., naming the above `foo.dart`, this works:

```
dart -c bin/dartdevc.dart --server foo.dart 
```

Feels like you have an old `dart:html`.  Do you need to delete a `pubspec.lock`?

**Comment by ochafik** [comment]
Oh! Seems that it works well in command line, but not in the transformer...
```
  function main() {
    html.document[dartx.body][dartx.innerHtml] = "Hello?";
  }
```
vs.
```
  function main() {
    html.document.body.innerHtml = "Hello?";
  }
```
(as if it didn't recognize that dart:html is from the sdk, somehow? I probably have messed up the URI somehow, but it used to work)

**Comment by ochafik** [comment]
Seems to be the same as #464, reopening it from a transformer angle.
