### ISSUE TITLE
Interpolation needs to call dart.toString

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#470]
I've been hitting an issue in our error code in `core.js` where the following line throws an exception when `_memberName` is a symbol:

```js
return `NoSuchMethodError : method not found: '${this[_memberName]}'\n` 
```

The original code is:

```dart
return "NoSuchMethodError : method not found: '$_memberName'\n"
```

The error is:

```
Uncaught TypeError: Cannot convert a Symbol value to a string(…)
```

Should we explicitly call `toString` when we generate interpolation (possibly suppressing on primitives)?

**Comment by jmesserly** [comment]
BTW, it looks like [NoSuchMethodError](https://api.dartlang.org/1.14.2/dart-core/NoSuchMethodError-class.html) actually wants a *Dart Symbol*, which is even more confusing. :)

Dart symbols are semantically different from JS ones. JS ones being a lot more useful/powerful. Although I suppose would *could* treat our extension method JS Symbols as being equivalent to Dart Symbols of the same name. Whether that's a good idea, I'm not sure. If we cared about nSM performance, I would consider tricks like that, but I think we're pretty far away from caring about performance at this point.

**Comment by vsmenon** [comment]
Yeah, that's it exactly.  We're passing in a JS symbol instead.

**Comment by jmesserly** [comment]
Update: I think Vijay fixed the nSM bug but we still have an issue with using tagged template for toString, if we aren't already doing that.

**Comment by jmesserly** [comment]
taking a look

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1989663002/
