### ISSUE TITLE
Failing language tests against bleeding edge analyzer

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#471]
Running DDC at 507d3c541ae56afe4a5ad0f2304b3002981bb228 with dependency overrides to bleeding edge analyzer at 02f888711ce671b0d6e97e6f449017248e92dd33

I see language test failures on

language cascade2_test
compile_time_constant8_test

**Comment by jmesserly** [comment]
looking into these now

**Comment by jmesserly** [comment]
Our upward inference for list literals is too smart. Had to add explicit `<dynamic>` to keep the spirit of these tests :)
