### ISSUE TITLE
hello_app transformer test broken

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#476]
Broken since [latest analyzer sync](https://travis-ci.org/dart-lang/dev_compiler/builds/113485784).

Somehow, LibraryElement instances now collide in _compilationRecord map, causing libraries to not be generated (the first one is recorded as "true" / successful, which is picked up for all the others).

Doesn't seem to happen when running in CLI, so might be due to how the analyzer:
```
bin/dartdevc.dart -o tmp --use-multi-package --package-paths test/transformer/hello_app/packages/ test/transformer/hello_app/web/main.dart
```

**Comment by vsmenon** [comment]
Merging into #478
