### ISSUE TITLE
Transformer set up appears to be broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#478]
The transformer set up is getting the wrong version of sdk libraries.   The transformer bot is marked as ok-to-fail right now. 

We should put fixing this on hold though until we work out the modular build:

https://github.com/dart-lang/dev_compiler/issues/439

**Comment by jmesserly** [comment]
I'm guessing we can close this one for now. When we reimplement on top of the new build package, we should be able to address this.
