### ISSUE TITLE
Runtime does not properly cast classes that implement call to Function

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#479]
We get a cast error on the following code:

```dart
class Foo {
  void call(String x) {
    print(x);
  }
}

dynamic foo = new Foo();

main() {
  Function f = foo; // Fails here
  f("hello");
}
```

Note, the level of indirection through `dynamic` is needed to force the runtime check.  Without it, the code works.  

As written, the assignment of `foo` to `f` forces a check, and we're not handling that correctly.

**Comment by jmesserly** [comment]
it's interesting it fails on the cast. It might fail as well on the actual call -- I don't think we support codegen for objects with call methods yet.
