### ISSUE TITLE
not all output written as node modules

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#481]
Not all the output files are written as node modules. When running this command:

```
pub global run dev_compiler --no-destructure-named-params -oweb/ddc --modules=node web/entry.dart
```

All my app code is compiled into node modules, and the referenced packages, but the runtime code (<output>/dev_compiler/runtime/**) still uses DDC's proprietary format. The modules are a mix of different types, which seems odd and probably won't work great at runtime. Is there another setting, or some other step I should take to re-compile the runtime files?

**Comment by jmesserly** [comment]
yeah for the moment you'd have to compile the SDK. node_test does something like that:
https://github.com/dart-lang/dev_compiler/blob/master/tool/node_test.sh

it's not a great situation. Essentially this is https://github.com/dart-lang/dev_compiler/issues/397 (with https://github.com/dart-lang/dev_compiler/issues/257 making it tough to solve).

**Comment by jmesserly** [comment]
BTW, I think destructure-named-params is off by default.

**Comment by jmesserly** [comment]
going to dupe this against #397, but I'm looking into providing the Dart SDK in a few module formats.
