### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/dev_compiler#484]
I updated dev_compiler to 0.1.23 today, but get an unhandled exception:

Unhandled exception:
Invalid argument(s): join(null, "harmony_feature_check.js"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:572)
#1      Context.join (package:path/src/context.dart:210)
#2      join (package:path/path.dart:225)
#3      BatchCompiler._copyDartRuntime (package:dev_compiler/src/compiler.dart:257)
#4      BatchCompiler._compileLibrary (package:dev_compiler/src/compiler.dart:197)
#5      BatchCompiler._compileLibrary (package:dev_compiler/src/compiler.dart:204)
#6      BatchCompiler._compileSource (package:dev_compiler/src/compiler.dart:147)
#7      BatchCompiler._compileFromUri (package:dev_compiler/src/compiler.dart:140)
#8      BatchCompiler.compileFromUriString (package:dev_compiler/src/compiler.dart:128)
#9      Object&ListMixin.forEach (dart:collection/list.dart:63)
#10     BatchCompiler.run (package:dev_compiler/src/compiler.dart:119)
#11     compile (package:dev_compiler/src/compiler.dart:68)
#12     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dev_compiler/bin/dartdevc.dart:49)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by vsmenon** [comment]
What is your command line invocation look like?

**Comment by kzhdev** [comment]
@vsmenon 

dartdevc -o ~/repo/adl_js/dev_compiler/js  web/adl_app_controller.dart

**Comment by kzhdev** [comment]
@vsmenon 

I found out that dartdevc with version 0.1.21 is installed with dart. That is conflict with the one I installed through 'pub global activate dev_compiler' and caused this exception.
