### ISSUE TITLE
virtualField helper does not understand "final" fields

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#486]
When you override a getter/setter with a field, we use the "dart.virtualField" helper.
It always "induces" a getter and a setter. But for final fields, the setter should either not exist, or forward to the base setter (if there was one).

FWIW, there's also some logic already to look for an existing property, I'm not sure why it does that.

CC @vsmenon who caught this

**Comment by jmesserly** [comment]
Oh, and apparently you can declare a final field and a setter in the same class. So we'll need to be careful about that too

**Comment by jmesserly** [comment]
P1 because I believe this was hit in Angular

**Comment by hterkelsen** [comment]
```dart
class A {
  int _x = 42;
  void set x(int val) {
    _x = val;
  }
  int get x => _x;
}

class B extends A {
  final x = 3;
}

void main() {
  var b = new B();
  print(b.x);

  b.x = 21;
  print(b.x);
}
```

When run with the VM, the output is

```shell
3
3
```

The output from DDC is:

```js
(function() {
  'use strict';
  const dart_sdk = require('dart_sdk');
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const hello = Object.create(null);
  const _x = Symbol('_x');
  hello.A = class A extends core.Object {
    A() {
      this[_x] = 42;
    }
    set x(val) {
      this[_x] = val;
    }
    get x() {
      return this[_x];
    }
  };
  hello.B = class B extends hello.A {
    B() {
      this.x = 3;
      super.A();
    }
  };
  dart.virtualField(hello.B, 'x');
  hello.main = function() {
    let b = new hello.B();
    core.print(b.x);
    b.x = 21;
    core.print(b.x);
  };
  dart.fn(hello.main, dart.void, []);
  // Exports:
  exports.hello = hello;
})();

//# sourceMappingURL=hello.js.map
```

and when run in node, the output is:

```shell
3
21
```

DDC should know that `final` fields only override getters, and not setters.

**Comment by jmesserly** [comment]
Great example!
Also this should work:

```dart
class A {
  int _x = 42;
  void set x(int val) {
    _x = val;
  }
  int get x => _x;
}

class B extends A {
  final x = 3;
  int get y => super.x;
}

void main() {
  var b = new B();
  print(b.x);

  b.x = 21;
  print(b.x);
  print(b.y);
}
```

VM prints: 3, 3, 21.

**Comment by hterkelsen** [comment]
I don't think that `virtualField` can be made to work with `final` fields. If you override a getter/setter pair with a final field, then you need the setter in the subclass to forward to the superclass setter. However, since `virtualField` uses `Object.defineProperty`, it can't access `super`.

I think the correct way is to make a new `setFinal` helper that sets some symbol on the instance to whatever the initializer for the final variable is and then for each final field to generate a getter/setter pair where the getter just gets the Symbol from before and the setter calls the superclass setter.

**Comment by jmesserly** [comment]
> However, since virtualField uses Object.defineProperty, it can't access super.

You can definitely access it. The super property descriptor will look like:
```js
{ 'get': getFn, 'set': setFn }
```

getFn is the getter function, setFn is the setter function. I'm 99.9% sure it is possible to make it work :)
```js
var superProp = Object.getOwnPropertyDescriptor(superProto, name);
var superSet = superProp.set;
Object.defineProperty(myProto, name, { get: () => value, set: superSet });
```
