### ISSUE TITLE
NodeList is now JS iterable

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#487]
In Chrome Canary you can do something like `document.body.childNodes[Symbol.iterator]()` and you'll get an iterator. According to @vsmenon this creates a problem when we mixin ListMixin into the native NodeList (via registerExtension).

I'm not sure how we are avoiding this problem for native arrays, but presumably we're doing something, so maybe we can extend that approach :)

**Comment by jmesserly** [comment]
Oh and it's worth double checking native Array that we aren't stomping on Symbol.iterator with our own (slow) version.

**Comment by jmesserly** [comment]
I'm adding in a workaround thanks to @vsmenon ... need to follow up on a real fix though. As it is, we're overwriting the native iterator (super bad). I hope we aren't doing this for Array.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#28324
