### ISSUE TITLE
Object.toString broken?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#488]
we seem to have this workaround:
```js
    core.Object.toString = function() {
      // Interface types are represented by the corresponding constructor
      // function.  This ensures that Dart interface types print properly.
      return this.name;
    }
```

Surely the fix belongs somewhere else... not to mention, won't this break the default `toString()` for all other objects?

Apparently I missed this in the original review discussion: https://github.com/dart-lang/dev_compiler/commit/59a85c5495c2c8fffe913d604d64582a7202ead7

looks like we might have a lot to clean up w.r.t. throw and stack traces.

**Comment by vsmenon** [comment]
This was a hack to get `Type` objects to print correctly, but it seems broken now anyway.

**Comment by jmesserly** [comment]
What's funny about that hack: Type objects all seem to define identical toString() and name getters :)

**Comment by jmesserly** [comment]
I'm in the process of porting them to Dart, so I'll probably fix this along the way.
