### ISSUE TITLE
Extra parentheses / precedence issue with metalet?

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dev_compiler#489]
```dart
class Foo { int bar; }
main() {
  var foo = new Foo();
  print(foo..bar = 1);
}
```
Compiles very lispily:
```js
core.print(((() => {
  foo.bar = 1;
  return foo;
})()));
```

**Comment by jmesserly** [comment]
this sounds like an issue with js_ast precedence+printer, as that's the guy responsible for adding parens. In any case worth keeping open

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27347
