### ISSUE TITLE
only one of a top-level getter/setter pair works in some conditions

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#490]
This bug has been mostly hiding, because we were intelligently grouping top-level properties and defined them together. I'm simplifying things and got rid of that readability optimization (it's a neat optimization but we should implement it differently), but as a consequence, it exposed the bug that we try and define the getter/setter separately, and as a result the last one wins.

I'm working on a fix to this.

**Comment by jmesserly** [comment]
CC @vsmenon in case you hit something like this

**Comment by jmesserly** [comment]
fixed this :)

**Comment by vsmenon** [comment]
John, the bug I was hitting was this:

```dart
class A {
  int _x = 42;
  int get x => _x;
}

class B extends A {
  void set x(int val) { _x = val; }
}

void main() {
  var b = new B();
  print(b.x);  // Error, no getter defined (masked by setter in B)
}
```

Is this what you fixed?

**Comment by vsmenon** [comment]
Ahh, sorry, misread - this is about instance getter / setters.  I'll file a separate bug for this.

**Comment by jmesserly** [comment]
yeah that's a different but related bug :)
