### ISSUE TITLE
Using void in a generic function throws.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#496]
Repro:
```dart
wrapZone/*<E, R*/(/*R*/ callback(/*E*/ evt)) {

}
wrapZone/*<Event, void>*/(someCallback)
```
crashes the dev compiler. It would be nice to support this case but reasonable to just report an error instead of crashing.
```
Unhandled exception:
Invalid argument (name): not a valid identifier: ""
#0      Identifier.Identifier (package:dev_compiler/src/js/nodes.dart:1074:7)
#1      JSCodegenVisitor.visitSimpleIdentifier (package:dev_compiler/src/codegen/js_codegen.dart:1727:45)
#2      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8971:15)
#3      JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3482:23)
#4      JSCodegenVisitor._emitSend (package:dev_compiler/src/codegen/js_codegen.dart:3062:12)
#5      JSCodegenVisitor.visitBinaryExpression (package:dev_compiler/src/codegen/js_codegen.dart:2690:12)
#6      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1136:15)
#7      JSCodegenVisitor._visit (package:dev_compiler/src/codegen/js_codegen.dart:3482:23)
...
```

**Comment by jmesserly** [comment]
Yeah generic methods aren't implemented in DDC yet :)
Tracking bug for that https://github.com/dart-lang/dev_compiler/issues/301

But I think this is unrelated, my guess is Dart Analyzer will reject this in strong mode. I'll file it over at SDK repo

**Comment by jmesserly** [comment]
moved to https://github.com/dart-lang/sdk/issues/26275

BTW I think your stack is a reasonable bug to re-file if you can figure out a repro for it. Since it crashed in visitBinaryExpression and it was due to an unnamed identifier I'm guessing it was not related to "void"
