### ISSUE TITLE
Using super in an async method breaks

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#499]
This results in code that does not parse in V8.  V8 complains about an illegal `super`.

```dart
Future foo() async {
  var result = await super.foo();
  return result;
}
```

I can work around by creating a non-async helper method that forwards to the super class.

**Comment by lrhn** [comment]
Is this dart2js or DDC?

**Comment by vsmenon** [comment]
DDC.  I assume it works in dart2js (or at least compiles the code to
something that parses - no idea if it is actually used at runtime in the
app I'm looking at :-).

**Comment by jmesserly** [comment]
ah, yeah, that's not too surprising. It desugars to `function*` and unlike `=>` it probably doesn't support `super`.

I think we might've had similar issues with anything that uses `.bind(this)` ... from a quick search, visitFunctionDeclarationStatement has a similar problem (it is completely unnecessary there, we could've used `=>`).

**Comment by jmesserly** [comment]
> I can work around by creating a non-async helper method that forwards to the super class.

yeah, something like that is probably the solution for us too in code_generator :)
