### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dev_compiler#50]
A friendly tracking bug. First-class supported source maps is a critical part of DDC.

**Comment by jmesserly** [comment]
this should be pretty straightforward once #61 is fixed

**Comment by jmesserly** [comment]
well, source maps are likely going to need more refinement, but the initial CL is here:
https://codereview.chromium.org/965033002/

**Comment by jmesserly** [comment]
definitely file issues for cases where this is not working as expected. 
here's one https://github.com/dart-lang/dev_compiler/issues/72
