### ISSUE TITLE
We don't support Map.unmodifiable and List.unmodifiable

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#500]
Probably our SDK is too old - I assume this was a recent add?

**Comment by rakudrama** [comment]
a1fa72091ad2be244d5e6b9a43e4c30d13b4a4cb List.unmodifiable added.

**Comment by rakudrama** [comment]
1cdc0221a28e039143823d76f6c510f77035674c Map.unmodifiable added.
