### ISSUE TITLE
Don't generate super for field accesses

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#501]
The following Dart generates ES6 with a super call to access the field `x`.  That is erroneous.

```dart
class A {
  int y;
}

class B extends A {
  int get x => super.y;
  void set x(val) { super.y = val; }

}

void main() {
  var b = new B();
  b.x = 42;
  print(b.x);
}
```

The example above prints `undefined`.  If I change the dart source to use `this.y` instead of `super.y`, it works fine.

It appears that the generated ES6 code should generate `this.x` instead of `super.x`.  We know statically it's a field.

**Comment by jmesserly** [comment]
On the bright side, that's an easy fix :)

**Comment by vsmenon** [comment]
I oversimplified the bug.  I've updated the example in the first comment.
