### ISSUE TITLE
dynamic calls to private members on extension classes don't work 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#508]
For extension types (type that are or may be native), we install private symbols to avoid visible prototype changes.  On a dynamic calls, we use the `canonicalMember` helper to convert names to symbols if needed.  It appears we're sometimes calling it with a JS Symbol instead.  We need to either:

(1) Fix the codegen to only invoke with a String name
(2) Fix the helper to allow a Symbol.

**Comment by jmesserly** [comment]
yeah, the invariant is: dynamic calls are supposed to always be Strings, because we don't know what the target type is. If we know the target type, then we find an extension method, and it shouldn't be a dynamic call. I'd be really interested to see the reproduction for this case. I suspect it's caused by --unsafe-force-compile, but maybe there's another way this can happen.

**Comment by vsmenon** [comment]
Assigning to myself to at least find a repro.

**Comment by vsmenon** [comment]
The following line in `dart:html` is using a symbol and breaking:

```
dart.dput(contextElement, _innerHtml, html);
```

**Comment by jmesserly** [comment]
Ah, nice catch. So it's a dynamic op on private fields. Yeah, we'll need to fix that. A simple repro is probably something like:
```dart
class C { var _x = 42; }
main() {
  dynamic c = new C();
  c._x = 100;
}
```

I wonder if this affects operations other than `dput`. I'm pretty sure `dsend` worked okay on private methods at one point.

**Comment by munificent** [comment]
If no one minds, I'll take a shot at this.

**Comment by jmesserly** [comment]
sounds good!

**Comment by munificent** [comment]
> I'd be really interested to see the reproduction for this case. 

Ask and ye shall receive:

```dart
import 'dart:html';

main() {
  new BRElement().createFragment("Hi");
}
```

No `--unsafe-force-compile` needed.

**Comment by jmesserly** [comment]
why is that a dcall? https://api.dartlang.org/stable/1.16.0/dart-html/Element/createFragment.html
if it's ending up a dcall then that's a bug

**Comment by jmesserly** [comment]
I am seeing this as the compiler output: 
```js
html.BRElement.new()[dartx.createFragment]("Hi");
```
Seems unrelated to this bug?

**Comment by jmesserly** [comment]
Oh, maybe you're saying somewhere in the course of calling createFragment the bug is triggered?
Anyway I already have a repro up thread that doesn't involve dart:html -- https://github.com/dart-lang/dev_compiler/issues/508#issuecomment-214430336

compiles to:
```dart
dart.dput(c, _x, 100);
```
so the bug is with private fields

**Comment by jmesserly** [comment]
(update title)

**Comment by munificent** [comment]
> Oh, maybe you're saying somewhere in the course of calling createFragment the bug is triggered?

Yes, sorry. It ultimately calls `contextElement._innerHtml = html`, which fails.

>     dart.dput(c, _x, 100);

Is that wrong? What should it be?
