### ISSUE TITLE
Dynamic calls to hashCode are broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#510]
This:

```dart
main() {
  dynamic x = 72;
  print(x.hashCode);
}
```

prints `undefined`.  If the code is typed (or inferred via `var`), it works.  The problem is with the runtime dynamic call.

**Comment by jmesserly** [comment]
This isn't supposed to be a dynamic call. It's supposed to be understood to be a method on Object. Maybe our handling in Analyzer has regressed?
