### ISSUE TITLE
Calls to Type.toString are broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#511]
This:

```dart
main() {
  print(5.runtimeType.toString());
}
```

prints this at run time.  Note, we're calling the JS toString, not the Dart one on the Type class.

```
class int extends core.num {
    static fromEnvironment(name, opts) {
      let defaultValue = opts && 'defaultValue' in opts ? opts.defaultValue : null;
      dart.throw(new core.UnsupportedError('int.fromEnvironment can only be used as a const constructor'));
    }
    static parse(source, opts) {
      let radix = opts && 'radix' in opts ? opts.radix : null;
      let onError = opts && 'onError' in opts ? opts.onError : null;
      return _js_helper.Primitives.parseInt(source, radix, onError);
    }
  }
```

**Comment by jmesserly** [comment]
https://github.com/dart-lang/dev_compiler/issues/488 -- I think all Object.toString might broken right now

**Comment by jmesserly** [comment]
but specifically for Type -- we don't have a patch for it as far as I can tell. I'm not sure if it's specified what Type.toString returns, as `abstract class Type {}` in `dart:core` is defined to have no members. But we can certainly implement whatever the de facto standard is.

We'll want to treat `Type` as an extension type (so we'll generate the appropriate calling convention) and either via the code generation for Type or just hard coded in the runtime, hook `Function.prototype[dartx.toString]`. We can determine if the function is a Dart type (vs a JS constructor/function) pretty easily by finding our reflection info we put on all Dart types.
