### ISSUE TITLE
Support cross-frame dom objects

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#517]
DDC support for cross-frame dom objects are incorrect as it depends on dart:js concepts of interceptors. Supporting this correctly will require a way to apply dart extension methods to a new child window when that window object is referenced through dart:html.

(edit by @jmesserly: split custom elements to https://github.com/dart-lang/dev_compiler/issues/521)

**Comment by jmesserly** [comment]
> Supporting this correctly will require a way to apply dart extension methods to a new child window when that window object is referenced through dart:html.

I don't follow the relation to `window` object or how that comes into play?

**Comment by jacob314** [comment]
dart:html has hooks where every time you have a dom method that returns a window you check whether the window is *the* window. if it is not *the* window you wrap it as a limited functionality cross-domain window so that you don't get access to cross-frame objects.
in dart2js this was mainly just to support dartium. in dev compiler, the extension method design means you would need to add a whole ton of extension methods to all objects from the window's context if you wanted them to play nicely with dev compiler.

**Comment by vsmenon** [comment]
Right, the actual prototype objects are different in each iframe / window.  So, the Window or HTMLCanvasElement protos in a frame are different from the ones on the top-level page.  Same with native Array for that matter.

The dart.registerExtension commands we execute only affect the top-level context.  We'd need to reapply those somehow to the new contexts (windows).

**Comment by jmesserly** [comment]
Sorry about that, I was super confused because I didn't see what "cross frame dom objects" had to do with "custom elements" ... I split custom elements into its own bug.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#28326
