### ISSUE TITLE
Fix generation of binary operators

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#518]
We currently map too many directly to JS even though the semantics are different.
One basic one: x % y is always positive in Dart, can be negative in JS.  DDC incorrectly has the JS behavior.

**Comment by vsmenon** [comment]
@rakudrama - are you looking at this one already?

**Comment by rakudrama** [comment]
https://github.com/dart-lang/dev_compiler/commit/8ab6b7172aeaeabc17e229f2366fb73bebf1af6c fixes `%`, `&`, `|`, `^`, `>>`, `<<`, `~`
