### ISSUE TITLE
SymbolLiterals are incorrectly created / canonicalized

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#519]
This prints `true` in DDC:

```dart
main() {
  print(#hello == #world);
}
```

**Comment by vsmenon** [comment]
The problem is that DDC is generating a concrete `core.Symbol` - this is an abstract class.  The abstract class doesn't contain any fields, so our canonicalization can't tell the difference between any fields.

`core.Symbol` has a factory constructor that forwards the a concrete internal class (with the expected field).  Looks like we need to generate `core.Symbol.new` instead of `new core.Symbol`.

**Comment by jmesserly** [comment]
yeah, probably broke when we changed how factory calling pattern works. FWIW this is a simple fix in visitSymbolLiteral. it's hard coding JS.New(...).

**Comment by vsmenon** [comment]
Stealing this since @jmesserly is out.  It appears to break package:unittest.
