### ISSUE TITLE
ListMixin appears to be broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#520]
The following code:

```dart
import 'dart:js' as js;

main() {
  js.context.callMethod('eval', ["x = [1, 2, 3]"]);
  var x = js.context['x'];
  x.forEach((y) => print(y));
}
```

triggers the following error:

```
dart_sdk.js:590 Uncaught NoSuchMethodError : method not found: 'Symbol("forEach")'
Receiver: Instance of 'JsArray<dynamic>'
Arguments: [Instance of '(dynamic) -> void']
```

`JSArray` mixes in `ListMixin`, but it appears that `forEach` is not properly install (or invoked?).

**Comment by jmesserly** [comment]
I'm confused. But it's confusing :)

Our native array (called `JSArray` with uppercase S) does not mix in ListMixin:
https://github.com/dart-lang/dev_compiler/blob/1b461199920149e856272182187f506260f62cf5/tool/input_sdk/private/js_array.dart#L122

But it appears the one from dart:js JsArray (lowercase s):
https://api.dartlang.org/stable/1.15.0/dart-js/JsArray-class.html

@vsmenon thinks this could be an issue with mixing in ListMixin.

**Comment by jmesserly** [comment]
Ah we chatted more, I think ListMixin is probably broken for any Dart type. What happens is it is getting marked as "native" as a result of dart:html, but the extension mechanism wasn't designed to handle mixins (because the JS primitive types don't use mixins). So we've got some rethinking to do there

**Comment by vsmenon** [comment]
Assigning to myself to find a simpler repro.  I don't think this is a `dart:js` issue.

**Comment by vsmenon** [comment]
Here's a simpler repo:

```dart
import 'dart:collection';

class MyList extends ListBase with ListMixin {
  int operator[](int x) => 42;
  int length = 4;
  void operator[]=(int x, val) {}
}

main() {
  var x = new MyList();
  x.forEach((y) => print(y));
}
```

This shows a JS `TypeError`.  Change `var x = ...` to `dynamic x = ...` to get the same NSM as the original example.

**Comment by vsmenon** [comment]
One more - native types (like `NodeList` in html) appear to work fine.

**Comment by jmesserly** [comment]
Yeah, so what's going on here is the current extension mechanism is designed for native *interfaces*. It's not designed to handle *extending* a native type. That is not possible for the most part -- dart:core types explicitly disallow it, HTML types too. "Custom Elements" was added to make something actually subclassable.

ListMixin gets mixed into a native type (in dart:html) though, which causes it to be considered a *native interface*, even thought it's actually a pure Dart class.

That's tricky.

So what we can do is treat ListMixin as "ListMixin implements ListMixin" where the interface is native, but the class is a Dart class. That will cause the methods to be generated with "normal" names and defineExtensionMembers to generate "dartx" names. Then, we just have to be careful when we mix it into a native type, we only pull in the symbols. That ought to do it.

**Comment by vsmenon** [comment]
Here was my workaround in the old code base:

https://github.com/dart-lang/dev_compiler/commit/d7ad9622108f8e6ebef6113a593c0daf1082df90

Primarily, it differentiates between classes known to be native and interfaces that may be implemented by a native type.

**Comment by jmesserly** [comment]
Hmmm, I'd call that a "fix" more than a "workaround". Looks like useful info to track in any case :)
I think we might have a hard coded list now (we were working around something, I forget what), but 

Do you recall offhand how it changed ListMixin code generation? In particular you should see Dart  method names, with symbols only implemented after the fact (defineExtensionMembers).

**Comment by vsmenon** [comment]
My next patch appears to have the changes:

https://github.com/dart-lang/dev_compiler/commit/bc11257b074a3c68f2ece5042eb9a2992e2333f9

**Comment by jmesserly** [comment]
Nice!!! Okay I'll try and roll that forward, I'm going to change our SDK extension type finder to be part of ./tool/build_sdk.sh so we can more easily tweak this kind of thing going forward

**Comment by jmesserly** [comment]
Oh Rectangle may be affected as well. Good catch @jacob314 !

**Comment by jmesserly** [comment]
I rolled forward the fix ... it seems to work, but I'm hitting a problem where nothing in dart:html shows up as native anymore. Perhaps a summary issue, not sure yet.

**Comment by jmesserly** [comment]
yeah it's a summary issue. It doesn't look dart:html's `@Native` annotation is not being picked up in the dart2js summary (`element.metadata` on the ClassElements). If I comment out useSummary on the Dart SDK resolver, then it works. @stereotype441 -- any thoughts on what might cause this?

**Comment by jmesserly** [comment]
I'll see how hard it is to have us generate a hard coded metadata list again (as part of tool/build_sdk) in the meantime.

**Comment by jmesserly** [comment]
Thanks to @stereotype441 for a workaround, I can use the ElementAnnotation's .element property to see if it's `@Native` since I don't care about the string value for my purposes. (`metadata.constantValue` seems to be null)

**Comment by jmesserly** [comment]
Okay I have a partial fix, DDC is still a bit messed up with extension members that are fields (`final int length = 5`) going to see if that is an easy fix, otherwise I may send out my partial fix

**Comment by jmesserly** [comment]
split #548 for the other issue. CL is https://codereview.chromium.org/1949163003
