### ISSUE TITLE
implement custom elements correctly in ddc

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#521]
split from https://github.com/dart-lang/dev_compiler/issues/517

custom elements in our dart:html are implemented in some way that depends on dart2js interceptors.
But we should be able to do something much more like how ES6 classes are used with custom elements.

**Comment by jmesserly** [comment]
cc @dam0vm3nt who hit this. What you may be able to do is use JS interop to access the "real" custom element registration in the DOM (bypassing dart:html) and try to register the element class that way. I'm not sure our constructors will be compatible but that should be a start.

**Comment by dam0vm3nt** [comment]
ok, tnx. that means  `new JsObject.fromBrowserObject(document).call('registerElement',['my-tag',MyDartType])` ?

**Comment by dam0vm3nt** [comment]
I can also making a js helper that can to it also "unwrapping" the dart type (i.e. calling `dart.unwrapType(x)`)

**Comment by donny-dont** [comment]
@jmesserly @jacob314 is there anything that outside contributors can do to get this rolling?

Custom Elements V1 is enabled in Canary by default and it would be great to get things hooked in to test.

**Comment by jmesserly** [comment]
yeah it's probably some small tweaks to DDC's html_dart2js.dart file. Needs someone to debug what is going wrong. IIRC it was calling some dart2js code that doesn't exist in DDC. It may be as simple as ripping those calls out, but without trying I'm not sure.

**Comment by donny-dont** [comment]
The interceptor stuff looked like that was how it would find the created constructor as well as the attached and detached methods. I'll see if I can find anything that's being passed in that might be of interest.

**Comment by donny-dont** [comment]
@jmesserly @jacob314 so here's a quickie experiment.

```
  html$._registerCustomElement = function(context, document, tag, type, extendsTagName) {
    let unwrapped = dart.unwrapType(type);
    let proxy = new Proxy(unwrapped, {
      construct: function(target, argumentsList, newTarget) {
        return new unwrapped.created();
      }
    });
   window.customElements.define(tag, proxy);
  };
```

The construct method from the proxy is being called when doing `new html.Element.tag('x-test')`. It ends up dying in class Element in the created constructor. It cannot set some of the properties. Commenting them out gets things a bit further but then it dies with `The result must implement HTMLElement interface`.

Is there a particular strategy for doing the interop with HTML elements? The Proxy implementation looks promising and is ES6. I'm just wondering if the DOM stuff in general needs to be gutted for dev compiler.

**Comment by jmesserly** [comment]
yeah the existing dart:html complexity definitely needs to be gutted.

Trying to set `offsetParent` does sound like a bug. How'd you hit that?

**Comment by donny-dont** [comment]
The first thing that came up with some googling was related to https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype-chain.

```
  dart.defineNamedConstructor = function(clazz, name) {
    let proto = clazz.prototype;
    let initMethod = proto[name];
    let ctor = function(...args) {
      initMethod.apply(this, args);
    };
    ctor[dart.isNamedConstructor] = true;
    ctor.prototype = proto;
    dart.defineProperty(clazz, name, {value: ctor, configurable: true});
  };
```

From what's happening here it looks like that might be the issue.

Other thing I noticed was the DivElement constructor was never getting called in DDC compiled code when doing `new html.Element.div()`. That's what got me wondering what sort of state the HTML interop was with DDC.

**Comment by jmesserly** [comment]
well constructor shouldn't be called, it should call createElement ultimately right?

**Comment by jmesserly** [comment]
but that's a fair point to @jacob314 -- we should skip generating a constructor for native types. This kind of thing is why this bug is still open :)

**Comment by donny-dont** [comment]
First time really digging into this so I had assumed that there would be some sort of wrapping going on for things like streams and other `dart:html` niceties. Hadn't found where that was happening yet.

**Comment by jmesserly** [comment]
IIRC they're all overlays not wrappers. We use ES6 symbols so we can add props in a safe way to HTML types.

**Comment by jmesserly** [comment]
That should ultimately make Custom Elements easier, once we're over the growing pains :)

**Comment by donny-dont** [comment]
Ah okay so the adding of props happens like this then?

```
  dart.setSignature(html$.Node, {
    constructors: () => ({
      _created: dart.definiteFunctionType(html$.Node, []),
      _: dart.definiteFunctionType(html$.Node, [])
    }),
    fields: () => ({
      [dartx.childNodes]: ListOfNode(),
      [dartx.baseUri]: core.String,
      [dartx.firstChild]: html$.Node,
      [dartx.lastChild]: html$.Node,
      [_localName]: core.String,
      [_namespaceUri]: core.String,
      [dartx.nextNode]: html$.Node,
      [dartx.nodeName]: core.String,
      [dartx.nodeType]: core.int,
      [dartx.nodeValue]: core.String,
      [dartx.ownerDocument]: html$.Document,
      [dartx.parent]: html$.Element,
      [dartx.parentNode]: html$.Node,
      [dartx.previousNode]: html$.Node,
      [dartx.text]: core.String
    }),
```

**Comment by jmesserly** [comment]
that's the runtime type info (for tear-offs, dynamic call checks). I believe it's something like "defineExtensionMembers" or something of that nature. It takes the real DOM type and the fake type we've created and merges the properties in

**Comment by vsmenon** [comment]
That's more a record of what happened for mirrors or dynamic ops.  See the `registerExtension` function.  That's where the Dart members are injected on the underlying JS ones for overlayed types.

**Comment by donny-dont** [comment]
Thanks @vsmenon and @jmesserly. Its definitely making more sense how its setup now.

So if you comment out the contents of `created` in Element and Node. You can do the following and get something back.

```
    static createElement_tag(tag, typeExtension) {
      if (typeExtension != null) {
        return document.createElement(tag, typeExtension);
      }
      var constructor = window.customElements.get(tag);

      if (constructor) {
        return new constructor();
      } else {
        return document.createElement(tag);
      }
```

The thing you end up getting back from document.createElement isn't quite right though. The prototype chains are mentioning HtmlElement not HTMLElement so something is going wrong.

**Comment by donny-dont** [comment]
So should HTMLElement and the like be mixed in with the html$.HtmlElement? Not sure if that would do the trick for this.

**Comment by jmesserly** [comment]
yeah html$.HtmlElement should be mixed into HTMLElement.

For your custom element, you want it to inherit from HTMLElement most likely. Likely need a tweak in the compiler to understand that when user classes inherit from "native" SDK classes, they need to use the "native" type not the Dart type.

**Comment by vsmenon** [comment]
Alternatively, in Dart, define:

```dart
class MyFooInDart extends HtmlElement { ... }
```

in JS, something like:

```javascript
class MyFooInJs extends HTMLElement { ... }
dart.registerExtension(MyFooInJs, MyFooInDart);
customElements.define("my-foo", MyFooInJs);
```

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27311
