### ISSUE TITLE
Static fields that "conflict" with super classes can cause TypeErrors in JS

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#522]
This code results in a JS TypeError when compiled with DDC and run:

```dart
class Foo {
  static int get x => 42;
}

class Bar extends Foo {
  static int x = 12;
}

void main() {
  print(Bar.x);
}
```

Here's the generated code:

```js
  hello.Foo = class Foo extends core.Object {
    static get x() {
      return 42;
    }
  };
  hello.Bar = class Bar extends hello.Foo {};
  hello.Bar.x = 12;
  hello.main = function() {
    core.print(hello.Bar.x);
  };
```

The TypeError is on the assignment to `hello.Bar.x`.

**Comment by vsmenon** [comment]
This is coming up in `dart:html`.  We have to comment out static fields in `SvgElement` that conflict with fields in `Element`.

**Comment by vsmenon** [comment]
See https://codereview.chromium.org/1904373002/

**Comment by hterkelsen** [comment]
I think this means that static fields also need the `virtualField` treatment.

**Comment by hterkelsen** [comment]
It seems like static overrides in ES6 need a virtual field for the same reason as non-static fields:

```
class A {
  static int get x => 1;
  static void set x(_) {};
}

class B {
  static int x = 2;
}

main {
  print(B.x);
}
```

The dart VM prints:
```
2
```

DDC outputs:
```
  hello.Foo = class Foo extends core.Object {
    static get x() {
      return 1;
    }
    static set x(value) {}
  };
  hello.Bar = class Bar extends hello.Foo {};
  hello.Bar.x = 2;
  hello.main = function() {
    core.print(hello.Bar.x);
  };
```

which, when run in `node`, prints:
```
1
```

**Comment by jmesserly** [comment]
@hterkelsen that sounds like it's on the right track.

Note that you can also use Object.defineProperty too (indeed see defineLazyProperty). I'm guessing all lazy static fields already work. The bug is because we opted for the "pretty" pattern, which we do if we believe the initializer is a constant.

e.g. you can just comment out this and it should work
https://github.com/dart-lang/dev_compiler/blob/1c49f6b660c5e6d81aed08c373999e57634d0f0b/lib/src/compiler/code_generator.dart#L1020

So the trick is to back off the readability optimization if we discover a static "override"

**Comment by rakudrama** [comment]
If I uncomment the affected code in `input_sdk/lib/svg/dart2js/svg_dart2js.dart`:

```dart
/* TODO(vsm): see bug 522 which requires us to comment out this code.
  static const EventStreamProvider<Event> abortEvent = const EventStreamProvider<Event>('abort');
```

I get the following error:

```
Chrome 50.0.2661 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot set property abortEvent of class Element extends html$.Node {
      static html(html, opts) {
        let validator = opts && 'validator' in o...<omitted>... } which has only a getter
  at /usr/local/google/home/sra/ddc/dev_compiler/lib/runtime/dart_sdk.js:71966
```

The error line (71966) is:
```
  svg$.SvgElement.abortEvent = dart.const(new (html$.EventStreamProvider$(html$.Event))('abort'));
```
