### ISSUE TITLE
finally + super don't play nice

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#528]
This is possibly more of an ES6 bug than a DDC bug, but you can probably triage this more accurately,.

I'm seeing issues when making a super method call within a finally block. For example:

```dart
class A {
   foo() => print('a');
}

class B {
  foo() => print('b');

  bar() {
    try { ... }
    finally { super.foo(); }
  }
}
```

The generated code contains `finally { super.foo() }`, which produces a runtime syntax error saying `super keyword unexpected here`.

**Comment by sigmundch** [comment]
It's easy to work around though (just pull the super call into a helper method)

**Comment by vsmenon** [comment]
This is related to #499 (though more surprising here).  The fix is probably same - the compiler can create a helper method.

**Comment by jmesserly** [comment]
yup. @sigmundch did you hit this in real code that will block folks? If so please mark P1. thanks :)

**Comment by sigmundch** [comment]
it was in a testing library that was easy to fix locally. In fact, the code was temporary to begin with and a change just landed that got rid of the code that was causing this altogether, so no blocker.
