### ISSUE TITLE
Assert in ModuleCompiler that we're in strong mode?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#529]
@jakemac53 was accidentally passing in a non-strong analysis context to ModuleCompiler and it led to subtle errors in the generated code.  Perhaps we should check and throw in this case.  You'd never hit it from the command line.

**Comment by jmesserly** [comment]
Great idea! And check the SDK context too :)

**Comment by jmesserly** [comment]
I fixed this in https://github.com/dart-lang/dev_compiler/commit/2b594db0bcbb1b0c0a44e573e2f6927095543899
