### ISSUE TITLE
validate type bounds in dynamic generic method call

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#532]
The initial implementation will not validate type bounds.

We actually have the same issue with generic classes. But there, it can only be triggered via JavaScript interop, because `C<InvalidType>` would be rejected at compile time. Generic methods must handle this at run time.

Since we represent these types as a function like `(T, S) => dart.functionType(...)`, once option is to generate an assertion in the body. Same trick would work for generic classes, although we might not want it there, because it would be triggered (once) for every class, whereas if we look up a runtime type signature of a generic method, we're already in the dynamic dispatch code path.

**Comment by jmesserly** [comment]
(Note, if we ever want mirror support for type bounds, we'll need to store this in a way we can get at it. https://api.dartlang.org/stable/1.16.0/dart-mirrors/TypeVariableMirror-class.html -- that's pretty obscure though, unclear where mirrors is headed for DDC)

**Comment by jmesserly** [comment]
Oh also: we'll need to instantiate to bounds at runtime in dcall/dsend. This is not implemented yet. Perhaps we can do default values on the type parameters.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27256
