### ISSUE TITLE
better code for boolean conversions

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dev_compiler#536]
We should make boolean conversions explicit and lighter weight. Rather than relying on `notNull` and `as`,

    if (dart.notNull(dart.as(x, core.bool))) ...

we should have a special (and efficient) helper for this common case, something like

    if (dart.test(x)) ...

**Comment by jmesserly** [comment]
in addition to boolean conversions (which are pretty common) we can also merge `as` and `notNull` more generally
