### ISSUE TITLE
JsArray broken due to wrong summary

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#537]
The following code breaks on the constructor call at runtime.  We generate a factory call (as it's a factory constructor in the VM-based summary), but our version of `dart:js` has a regular constructor instead.

```dart
import 'dart:js';

void main() {
  var a = new JsArray();
  print(a);
}
```

Do we need anything besides the latest analyzer to fix this?  @stereotype441 fixed the analyzer side of this.

On a related node, we may consider always generating the factory pattern (`JsArray.new` instead of `new JsArray`) for uniformity.

**Comment by jmesserly** [comment]
This should be fixed already -- can you verify with latest SDK & then we can close this?
