### ISSUE TITLE
export of non-classes does not work 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#543]
It appears that exported symbols are copied too early.  If the following 3 files are compiler together in one module:

```
dart ~/git/ddc/bin/dartdevc.dart compile --modules node --out foo.js foo.dart bar.dart baz.dart
```

foo.dart:
```dart
import 'baz.dart';
import 'bar.dart' as bar;

final y = 38;
final info = new Info();

void main() {
  print(info.x);
  print(bar.y);
}
```

bar.dart:
```dart
export 'foo.dart';
```

baz.dart:
```dart
import 'bar.dart';

class Info {
  int x = y;
}
```

and run, we get a JS runtime type error that `baz.Info` is not a constructor.

**Comment by vsmenon** [comment]
Here is the generated JS.  Note that `foo.info` is accessed before the `Info` class is defined.

```
(function() {
  'use strict';
  const dart_sdk = require('dart_sdk');
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const foo = Object.create(null);
  const bar = Object.create(null);
  const baz = Object.create(null);
  foo.y = 38;
  dart.defineLazy(foo, {
    get info() {
      return new baz.Info();
    }
  });
  foo.main = function() {
    core.print(foo.info.x);
    core.print(foo.y);
  };
  dart.fn(foo.main, dart.void, []);
  bar.y = foo.y;
  bar.info = foo.info;
  bar.main = foo.main;
  baz.Info = class Info extends core.Object {
    Info() {
      this.x = foo.y;
    }
  };
  // Exports:
  exports.foo = foo;
  exports.bar = bar;
  exports.baz = baz;
})();
```

**Comment by jmesserly** [comment]
yeah I wrestled with exports ... left in place most of our existing mechanism, so it still tries to see if the export is "lazy", but I guess the bit is not computed transitively. That's why it emits `foo.info` as lazy, but `bar.info` does not respect that and calls the lazy getter at the top level.

Two ways to fix it:
* quick fix is to make them all lazy, but that seemed super ugly which is why I didn't do it the first time
* real fix is to teach element_loader about exports (right now it knows nothing -- they are not collected in _collectElements)

**Comment by jmesserly** [comment]
I'm just going to do the real fix. To be honest I almost included it in the "big modular compile" CL but it was already too crazy. I had somehow fooled myself into thinking our old logic for exports was working. Nope :)

**Comment by vsmenon** [comment]
Adding P0 - this is blocking loading of apps right now.  Will see if I can workaround.

**Comment by jmesserly** [comment]
Hmmm, actually this looks better than I'd thought. I did appear to fix the ordering in visitExportDirective already. So I don't think this is an ordering issue at all. It is just incorrectly exporting top-level variables. They need to be lazy per Dart semantics.

**Comment by vsmenon** [comment]
I can workaround by modifying `visitExportDirective` to add to a separate list and to append that list to `_moduleItems` in `_emitModule`.  I don't think that's a correct solution though - these still need to be spit out in the right order, right?

**Comment by jmesserly** [comment]
It has nothing to do with order. The bug is we don't generate any library properties (fields, getters, setters) correctly at all. I'm not sure to what extent it was already broken, or regressed with the modular compiler.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1949733002/

**Comment by jmesserly** [comment]
aside: this also fixes local_export_test, which *appeared* to pass, but was not really working. It "worked" because it tried to export `["A="]` which is totally wrong :)

**Comment by vsmenon** [comment]
@jmesserly I'm still hitting an error when the `dart.export` happens before the from property is set.  `copyProperty` fails with a null `desc`.

**Comment by jmesserly** [comment]
New repro? The old one is included in https://github.com/dart-lang/dev_compiler/commit/698e84ab5fe24e02299029e46f6d4aa0e7d16ed5 and it's passing

**Comment by vsmenon** [comment]
Assigning to myself to come up with a repro.

**Comment by vsmenon** [comment]
Here's a new repor:

foo.dart
```dart
import 'bar.dart' as bar;

final y = 38;
int get info => 42;

void main() {
  print(bar.info + y);
}
```

bar.dart:
```dart
export 'foo.dart';
```

Compile step:
```
> dart ~/git/ddc/bin/dartdevc.dart compile --modules node --out foo.js bar.dart foo.dart
```

Runtime error:
```
/Users/vsm/ddctest/dart_sdk.js:1186
    return Object.defineProperty(obj, name, desc);
                  ^
TypeError: Property description must be an object: undefined
    at Function.defineProperty (native)
    at dart.defineProperty (/Users/vsm/ddctest/dart_sdk.js:1186:19)
    at dart.copyProperty (/Users/vsm/ddctest/dart_sdk.js:1269:10)
    at dart.export (/Users/vsm/ddctest/dart_sdk.js:1272:17)
    at /Users/vsm/ddctest/foo.js:11:14
    at Object.<anonymous> (/Users/vsm/ddctest/foo.js:25:3)
    at Module._compile (module.js:539:32)
    at Object.Module._extensions..js (module.js:548:10)
    at Module.load (module.js:454:32)
    at tryModuleLoad (module.js:413:12)
```

**Comment by jmesserly** [comment]
out of curiosity do you know if it fails because of "info" or "y"?

(one is a getter one is a field, so they use different element model structure in Analyzer... maybe we're still not implementing all permutations correctly, in particular the getter jumps out at me)

**Comment by vsmenon** [comment]
`info`

Here's the generated JS - it's throwing on the call to `dart.export`:
```
(function() {
  'use strict';
  const dart_sdk = require('dart_sdk');
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  const bar = Object.create(null);
  const foo = Object.create(null);
  foo.y = 38;
  bar.y = foo.y;
  dart.export(bar, foo, 'info');
  foo.main = function() {
    core.print(dart.notNull(foo.info) + dart.notNull(foo.y));
  };
  dart.fn(foo.main, dart.void, []);
  bar.main = foo.main;
  dart.copyProperties(foo, {
    get info() {
      return 42;
    }
  });
  // Exports:
  exports.bar = bar;
  exports.foo = foo;
})();
```

**Comment by jmesserly** [comment]
ah yup. I know what that is. I guess we're tracking getter/setter elements individually, so when we ask loader to load the property, it's like "uh, I don't know what that is -- sure, let's pretend it's loaded!"

**Comment by jmesserly** [comment]
aside: if we ever get the mythical "time to pay off technical debt" I'd love to make the ordering system issue better errors. e.g. it could easily tell that you're asking it to load something *from the current module* which it does not know. that's a clear sign something is amiss

**Comment by jmesserly** [comment]
I'm going to split properties into its own bug ... more satisfying that way, plus the original issue was fields which is fixed :)
https://github.com/dart-lang/dev_compiler/issues/549
