### ISSUE TITLE
Unwrap futures on async functions

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#545]
The following code - no static issues - fails at runtime on a cast from `Future` to `String`.  Should we be unwrapping in DDC?

```dart
import 'dart:async';

Future<String> foo() async {
  return (1 > 0) ? new Future<String>.value('hello') : "world";
}

main() async {
  var result = await foo();
  print(result);
}
```

**Comment by vsmenon** [comment]
@leafpetersen

**Comment by leafpetersen** [comment]
Yes.  We support it in the type system, I thought we had already implemented support for it in the async/await implementation, but maybe that was only for `await 42`?  :)  @jmesserly ?

**Comment by jmesserly** [comment]
Well this is `return` not `await`.

A guess: future flattening was not implemented in DDC. We hadn't decided on what to do yet at that point in time. What is likely going on is it tries to create a `Future<Future<String>>` at some point (probably runtime) and it doesn't understand that flattens to `Future<String>`. We'll need the same Future flattening logic at runtime, right? e.g. if I have a generic type `C<T>` and I make a `Future<T>` that needs to be `Future< flatten(T) >`

**Comment by jmesserly** [comment]
Oh: and compiler could also generate `Future< flatten(T) >` since we can find it statically, but I suspect we are doing `Future< T >` inside of our dart.async helper method.

**Comment by jmesserly** [comment]
https://github.com/dart-lang/dev_compiler/blob/1cdc0221a28e039143823d76f6c510f77035674c/tool/input_sdk/private/ddc_runtime/generators.dart#L50 is potentially a trouble spot for us. Depends what `T` was passed in. Maybe it was flattened for us already, not sure.

a few lines up on:
https://github.com/dart-lang/dev_compiler/blob/1cdc0221a28e039143823d76f6c510f77035674c/tool/input_sdk/private/ddc_runtime/generators.dart#L41

... is probably where things go wrong for this example. It doesn't know to flatten the return value.

**Comment by leafpetersen** [comment]
Sounds like there are probably two issues here:

1) When a future is returned from an async function we need to unwrap it.
2) We need to flatten future type representations.

I can try to look at the second, or both.

**Comment by jmesserly** [comment]
yeah go for either or both :)

**Comment by jmesserly** [comment]
I can take this if you didn't start on it yet @leafpetersen

**Comment by leafpetersen** [comment]
You're welcome to it, or if you want me to move this up in my queue I can.

**Comment by jmesserly** [comment]
Interesting one. So we're generating a cast on the return value to type String. Bug in coercion reification? Something wacky with LUB? Unclear yet. But we don't even get to the runtime helper or constructing a `Future<Future<String>>` at runtime so seems unrelated to those
```js
return dart.as(dart.notNull(x) > 0 ? async.Future$(core.String).value('hello') : "world", core.String);
```

**Comment by jmesserly** [comment]
Oh shoot. Looks like a CodeChecker bug (_checkReturnOrYield) specifically where it puts the downcast. We don't do anything special in DDC other than insert the cast where Strong Mode told us to put it.

**Comment by jmesserly** [comment]
And it looks like the downcast comes into play because of LUB. LUB of `Future<String>` and `String` is `Object`, so Strong Mode thinks it needs to insert *some* downcast there for soundness. Strong Mode would be happy to cast to either a `Future<String>` or `String`, but in this case it doesn't know what to cast to, and we don't have a way to represent a cast to a union type, so it picks `String` (somewhat arbitrary choice).

This looks to me like I feel confident saying this is a problem with Strong Mode, not DDC.

(aside: we may not need Strong Mode to insert a cast in this case, due to how DDC's async function body works, but regardless it needs to be sorted out what to do in the type system side.)

**Comment by jmesserly** [comment]
Moved to https://github.com/dart-lang/sdk/issues/26404.
I'll open another bug about the runtime future flattening, once I figure out a repro :)

**Comment by jmesserly** [comment]
future flattening: https://github.com/dart-lang/dev_compiler/issues/551

I forgot these examples tend to fail on VM as well, so maybe not very high priority on that one.
