### ISSUE TITLE
Bug in function subtyping?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#550]
If I uncomment the definition of `f`, I get a static error.  With it commented, the code prints `true`.  I think this is a runtime bug.

```dart
typedef T Func<S, T>(S x);
typedef T Func2<R, S, T>(Func<R, S> f);

int foo(Func<num, int> f) {
  print(f(32));
}

void main() {
  // Func2<int, int, num> f = foo;
  print(foo is Func2<int, int, num>); 
}
```

**Comment by vsmenon** [comment]
@leafpetersen : seeing this before and after your CL.

**Comment by leafpetersen** [comment]
I think that's the behavior I would expect: Functions are in the ignore whitelist.  Or are you not seeing a console warning about ignoring a cast failure?

**Comment by vsmenon** [comment]
Not seeing a console warning.  Doesn't appear to hit that path.

**Comment by leafpetersen** [comment]
Bug in runtime for subtyping generic typedefs.  Generic typedefs were matching the class subtyping path, and hence getting subtyped covariantly.  Fix coming.
