### ISSUE TITLE
implement Future flattening

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#551]
Strong Mode interprets `Future<T>` as `Future<flatten(T)>`. We have not implemented this in DDC's type system yet.

Note that this is broken in checked mode in some cases on the VM too. For example:
```dart
import 'dart:async';

class G<T> {
  m(x) {
    Future<T> y = x;
  } 
}

main() {
  new G<Future<String>>().m(new Future<String>.value('hi'));
}
```

The cast to "y" fails on the VM and DDC too. With generic methods you can create DDC specific failure modes (until VM implements them).

**Comment by jmesserly** [comment]
@vsmenon  is hitting this. I think @leafpetersen is going to take a look.

**Comment by jmesserly** [comment]
Leaf fixed in https://github.com/dart-lang/dev_compiler/commit/a12069c96264ba929068dc544e5a7b58ac4b67c7 :)

**Comment by vsmenon** [comment]
We need this around `_Future` as well.  In `dart:async`, I see some calls to `new _Future(T)` which aren't handled.
