### ISSUE TITLE
dart.hashCode, etc. aren't forwarding to the right methods

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#552]
This:

```dart
void main() {
  var value = "hello";
  print(value.hashCode);
  print(value.runtimeType.hashCode);
}
```

prints `5` and `undefined`.  We're compiling the corresponding dart2js implementations, but not forwarding.  (String is just returning length for now.)

**Comment by vsmenon** [comment]
Looks like a `_LinkedHashMap` on `Type` is interpreting undefined as 0 - and putting everything in one bucket....

**Comment by jmesserly** [comment]
Oh interesting. This particular example may not be an instance of the general problem (that our Object members on native types are kind of broken), this one might be specific to our TypeReps which I'm not sure are hooked up to core.Object.

**Comment by jmesserly** [comment]
So I've fixed TypeReps. Now trying to figure out what to do with object members.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1962823002/
