### ISSUE TITLE
Provide a module root flag

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#553]
Provide a `--module-root` flag to qualify the module name in the generated output.  We currently use the basename of the outfile (without the extension) as the module name.  This option would qualify the module name wrt the provided root.
```
dartdevc --module-root foo --out foo/bar/baz.js foo/bar/baz.dart
```
would create a JS file with module name `bar/baz`.

@sigmundch - this correct?

**Comment by sigmundch** [comment]
correct, thanks Vijay.

This was probably implied by the above, but just wanted to note that the `--module-root` would also be used to generate imports to modules that were loaded from summaries. So if you have:

```
dartdevc --module-root foo -s foo/a/b.ds --out foo/bar/baz.js foo/bar/baz.dart
```

and `baz.dart` contains an import resolved under `b.ds` then the output module `bar/baz` will load the module `a/b` .
