### ISSUE TITLE
Support structural types in dart:html on ddc

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#558]
There are currently about 200 types in dart:html that cannot be properly implemented in ddc as they don't really have a concrete prototype.
For now, we should just remove these classes from the extension method list and make sure all these
methods are generated without extension method conventions so that typical user code is not broken.

**Comment by jmesserly** [comment]
if you remove `@Native` it will remove it from extension type list.
https://github.com/dart-lang/dev_compiler/blob/f8f914081cf7e738cb105b20c8397d2bc31820f8/lib/src/compiler/extension_types.dart#L83

**Comment by vsmenon** [comment]
@terrylucas had been studying these types.  We could annotate them differently - I think the relevant info is in the source IDL.

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27310
