### ISSUE TITLE
type checks for primitive types could be much faster

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#560]
e.g. `dart.as(expr, core.bool)` and `dart.as(expr, core.String)` jump out as especially egregious :)

I think we have a helper for testing int, not sure if it's called though.

**Comment by jmesserly** [comment]
CC @leafpetersen @rakudrama

**Comment by jmesserly** [comment]
Related: https://github.com/dart-lang/dev_compiler/issues/536

**Comment by rakudrama** [comment]
This is much better after https://github.com/dart-lang/dev_compiler/commit/bcc5f9d9c76e4fd1aa640518da35c9b96b8e13e7, which places the test on the type, i.e.

    dart.as(expr, core.bool)

is now

    core.bool.as(expr)

with a custom `as` method on `core.bool`

**Comment by jmesserly** [comment]
Nice. Going to say this is done :)
