### ISSUE TITLE
Update "dart:" libraries to latest from Dart repo

### ISSUE THREAD

**Issue by munificent** [dart-lang/dev_compiler#565]
DDC has its own copy of the "dart:" library sources and they were forked some time ago. Eventually, we want to unfork (#257), but, until, then we're going to rev our forked copy to be closer to up-to-date with the current version of Dart.

Here's what's left to do:

- [x] dart:async
- [ ] dart:collection (in-progress)
    - (Looks like there are some changes in collection_patch to bring over.)
- [x] dart:convert
- [ ] dart:core
    - [ ] HashMap and HashSet
    - [x] StackTrace
- [ ] dart:isolate
- [x] dart:math
- [ ] dart:typed_data

The web libraries are handled separately since they are actively maintained:

- dart:html
- dart:indexed_db
- dart:js
- dart:svg
- dart:web_audio
- dart:web_gl
- dart:web_sql

(cc @jacobr)

These are not supported by DDC:

- dart:developer
- dart:mirrors
- dart:io

**Comment by munificent** [comment]
cc @rakudrama @hterkelsen

**Comment by munificent** [comment]
I'll take StackTrace.

**Comment by jmesserly** [comment]
I'll take dart:math

**Comment by munificent** [comment]
Oh, sorry, Harry is working on dart:math. :)

**Comment by munificent** [comment]
I'll take dart:developer.

**Comment by munificent** [comment]
Oh, never mind. DDC obviously doesn't support that. :)

**Comment by munificent** [comment]
I'll look at the dart:collection stuff.

**Comment by jmesserly** [comment]
have ya'll considered bringing over dart:io? We don't have it yet but dart2js provides some of it:
https://github.com/dart-lang/sdk/blob/c566fc30c617f149eac6b5f52ce8f072684f50c8/sdk/lib/_internal/js_runtime/lib/io_patch.dart

**Comment by jmesserly** [comment]
I'm going to follow up and see if I can snip the dart:io dependency, it might be we are including unused stuff in unittest module

**Comment by munificent** [comment]
I'll take a look at dart:isolate, though I'm guessing there's nothing there we want to bring over right now.

**Comment by jmesserly** [comment]
I think this was done, or at least the P1 stuff was. We need to unfork SDK though still.

**Comment by jmesserly** [comment]
(unforking SDK is covered by https://github.com/dart-lang/dev_compiler/issues/257)
