### ISSUE TITLE
throw the right exception types for failures

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#566]
the runtime helpers seem to be a bit confused right now between StrongModeError, NoSuchMethodError, TypeError and others.

**Comment by rakudrama** [comment]
Lots of tests would pass if we generated TypeError instead of CastError for the places that in the spec are type assertions.

The injected as-checks should be generated as a different helper, e.g.

dart.as(x, T)  -->  dart.check(x, T).

**Comment by rakudrama** [comment]
A related issue is null checking. This needs to distinguish a receiver from an argument.

    a + b

which we currently potentially generate as

    dart.notNull(a) + dart.notNull(b)

should throw a `NoSuchMethodError` for a==null but an `ArgumentError` for b==null.

**Comment by rakudrama** [comment]
I'm tackling making more cases generate TypeError.

**Comment by jmesserly** [comment]
I believe this was fixed.
