### ISSUE TITLE
inference results in different behavior with "is" tests

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#567]
reported by @vsmenon in this [comment](https://github.com/dart-lang/dev_compiler/issues/296#issuecomment-132648045)

> On a very related note, after #236, strong mode and standard Dart print different values for:
```dart
class Foo<T> {
  bool bar(x) => x is T;
}
void main() {
  Foo<int> foo = new Foo();
  print(foo.bar("hello"));
}
```

> We used to reject this. 

---

[comment](https://github.com/dart-lang/dev_compiler/issues/296#issuecomment-132654465) by me:

> ah, because of inference... eeeep.
```dart
class Foo<T> {
  bool bar(x) => x is T;
}
void main() {
  Foo<int> foo = new Foo();
  var foo2 = new Foo<int>();
  print(foo.bar("hello"));
  print(foo2.bar("hello"));
}
```
> it seems really nice if foo2 could work, even if foo doesn't.

**Comment by jmesserly** [comment]
CC  @leafpetersen 

I'm not sure what the right answer is. With an eye towards future Dart, does this seem like something we need to address?

**Comment by lrhn** [comment]
On Thu, May 12, 2016 at 8:06 PM, John Messerly <notifications@github.com>
wrote:

> CC @leafpetersen <https://github.com/leafpetersen>
>
> I'm not sure what the right answer is. With an eye towards future Dart,
> does this seem like something we need to address?
>
We definitely need to figure out what we want. :)
With generic methods, this problem doesn't even need a class any more:

    bool isit<T>(Object x) => x is T;

    main() {
      print(isit<String>("ab"));
      print(isit<int>("ab"));
      print(isit("ab"));
    }

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by vsmenon** [comment]
Yeah, we used to reject these statically - i.e., reject `is` and `as` checks on all types where strong mode would differ (type params, non-dynamic functions, non-dynamic generics).

We could explore doing that again.

We could also allow but throw a `StrongModeError` at runtime if the test on a non-ground type ever returns false.

Neither are great answers, though the latter is particularly bad.  :-)

**Comment by jmesserly** [comment]
@vsmenon can we close this? not sure we have any plans to address it and Dart 2 will make it obsolete

**Comment by vsmenon** [comment]
yeah, not a dev_compiler issue.
