### ISSUE TITLE
Calls to dart.const aren't moved to higher levels and aren't cached.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#569]
I see lots of time spent in dart.const in profiles.  There is hot code which has calls to dart.const - each call will produce the same value but discovering that it relatively expensive.  We could sometimes hoist the constant up to a higher level.   We could also cache these constants in local variables at an appropriate scope by doing something like this:

```dart
let t1; // at an appropriate scope
foo() {
     bar(t1 || (t1 = dart.const(new ConstObject(....));
}
```

The scope at which the cache variable is located has to account for both type and term variables that occur within the constant (so that we don't end up sharing constants with different runtime types).  If we just don't do this for constant constructors, we can probably ignore the term variable issue.

**Comment by jmesserly** [comment]
@leafpetersen -- if we're looking at startup speed, you could just make the consts back into lazy static properties. It's a "readability" optimization to initialize them at top-level. It's not required for semantics.

I presume you're seeing mostly top-level ones. There is definitely a related perf issue of constants inside of method bodies, which would need the fix you illustrate. I'm not sure if we're running enough code to really hit that? But if we are, it'd be good to optimize.

**Comment by leafpetersen** [comment]
We're hitting both.  Making top level lazy is worth a try - might speed up startup.  I also see hot code at runtime with constants being used repeatedly in method bodies.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1976923003/ fixes top-level

**Comment by jmesserly** [comment]
almost ready on this one. I think all I need to worry about is type params, unless I'm missing something. for now if we have type params, it just skips the optimization (we can do better for generic classes, probably not for generic methods. I left both as a TODO.)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1979013003
