### ISSUE TITLE
_installProperties is slow

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#570]
something combinatoric is going on since dart:html was added. We're seeing a ton of calls to this.

**Comment by jmesserly** [comment]
@leafpetersen is looking at this too

**Comment by rakudrama** [comment]
Loading dart_sdk goes from  ~1500ms to ~800ms with https://github.com/dart-lang/dev_compiler/commit/a637e4102fff7d32760bd800971c7645309f5855

About ~350ms of the ~800ms is parsing the body of the dart_sdk.js library loader function. This is (miss)-attributed to the function that calls the library loader function (LibraryLoader.load).
