### ISSUE TITLE
Runtime type information should be named and hoisted

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#573]
We generate lots of inline type information.  This costs at startup to parse and evaluate, and costs at runtime to repeatedly allocate and canonicalize.  We should name types in some or all contexts so that instances are semantically shared.

**Comment by leafpetersen** [comment]
@rakudrama @jmesserly I'm going to start working on this unless either of you have already jumped on this.

**Comment by jmesserly** [comment]
go for it

**Comment by rakudrama** [comment]
Is this finished?

**Comment by leafpetersen** [comment]
yes.
