### ISSUE TITLE
DateTime code does unnecessary dynamic sends

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dev_compiler#579]
For example, in Date formatting a method like getYear which just sends year to date ends up going through Primitives.getYear, which does a dynamic isUtc call.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2004463004/

**Comment by jmesserly** [comment]
fixed in https://github.com/dart-lang/dev_compiler/commit/dac62b61ee9cd2bd411bd5bba47576b52804010d
