### ISSUE TITLE
Tests that fail to compile succeed

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#580]
For codegen tests, if they fail to compile we just don't generate a js file, and so nothing gets run, and so the tests succeed.  We need to notice if things fail to compile.

**Comment by rakudrama** [comment]
We should put the status in a file so that it can be consumed by the compile step and the execution step.
I though of generating dummy files for compile failures that have a main program that emits the compile errors but that is somewhat indirect.

**Comment by vsmenon** [comment]
I'll look at this before we start triaging tests further.

**Comment by vsmenon** [comment]
This should be fixed now.
