### ISSUE TITLE
Runtime error on static field named 'name'

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#587]
```dart
class Field {
  static const name = 'Foo';
}

void main() {
  print(Field.name);
}
```

triggers this at runtime:

```
TypeError: Cannot assign to read only property 'name' of function 'class Field extends core.Object {}'
```

**Comment by vsmenon** [comment]
Looks like we don't check statics for conflicts in `_emitMemberName`.

**Comment by jmesserly** [comment]
Huh. I could swear this used to work. :)

We need to use Object.defineProperty to define it. I think we used to send these down the lazy field path, which uses defineProperty, so it worked. It would also be fine to `Object.defineProperty(Field.prototype, 'name', { value: 'Foo' });` ... the laziness is not important, only that we use defineProperty.

**Comment by vsmenon** [comment]
Should we be overwriting `name`?  We could rename it (as we'd do with `constructor` I think).

Alternatively, we could revisit putting statics here.

**Comment by jmesserly** [comment]
Yeah we shouldn't rename it. It's equivalent to this perfectly legal ES6 code:
```js
class Foo {
  static get name() { return 'Foo'; }
}
```

**Comment by smanilov** [comment]
I'm not sure I can reproduce this.

I'm invoking DDC like this:

`dartdevc.dart compile -o foo bug.dart`

where `bug.dart` contains the code from the initial comment.

**Comment by smanilov** [comment]
Explanation on how to run the code here: #485
