### ISSUE TITLE
Functions do not support Object members.

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#591]
I don't think we treat functions as native types/extension interfaces. So they don't get Object members. I imagine that none of the object members are working, or if they are, I don't understand how :).

This affects == and hashCode of tear offs, toString, and noSuchMethod on functions. Also runtimeType may not give the right answer either.

**Comment by vsmenon** [comment]
Should this be dispatched / handled via `dart.hashCode`, etc.?

**Comment by jmesserly** [comment]
Yeah, exactly. The question is where do the Function implementations live? Normally the helpers just check for null, then if we have an extension type, use `obj[dartx.hashCode]` else `obj.hashCode` So we either will want to install `[dartx.hashCode]` and friends on JS functions, or we have a special check for `typeof obj == "function"` and hard code the function logic.

**Comment by jmesserly** [comment]
FYI -- I'm looking into this. Some of the nSM tests pass functions and they were not passing for this reason.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2061373003
