### ISSUE TITLE
implement configuration specific imports

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#595]
See SDK bug: https://github.com/dart-lang/sdk/issues/24581

Guessing this should be pretty easy, mostly plumbing through the right configuration to Analyzer.

CC @alan-knight

**Comment by anders-sandholm** [comment]
When do you expect to see this land?

Would be great to get this landed. Look's like this might be the last bit missing in enabling a re-write of package http to use config-specific imports instead of mirrors.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27302
