### ISSUE TITLE
merge analyzer errors with static info

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#6]
The idea is that we use the same mechanism to report all errors. Currently analyzer errors don't hold a reference to the AstNode, so the integration is not trivial.

One option is to move away from storing static info per node (just store it by offset & length like the analyzer does). This might be OK since the codegen doesn't need all the static info, just some bits here and there.

**Comment by jmesserly** [comment]
looking into this as part of analyzer_cli integration. Unclear yet if I'll fix it entirely, but starting to look that way.

**Comment by jmesserly** [comment]
partially fixed in https://github.com/dart-lang/dev_compiler/commit/0ff64c1c9805e8fe6406e2acb05e34891d2f9f83 ... testChecker no longer depends on nodes. still more work to do to push it all the way back into CodeChecker

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1230903002/ fixes most of it.
