### ISSUE TITLE
noSuchMethod Invocation does not include generic type arguments 

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#604]
Dart's Invocation object doesn't have type arguments, so they get dropped when we call nSM. There's no way to access them from nSM.

@leafpetersen - thoughts on this? Should we add them to Invocation?

**Comment by jmesserly** [comment]
Reason I marked as p2, if folks want to mock generic methods, they might hit this issue.

**Comment by leafpetersen** [comment]
Yeah, this should be supported.

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27323
