### ISSUE TITLE
Support loading files via non-file: URIs

### ISSUE THREAD

**Issue by nex3** [dart-lang/dev_compiler#609]
Currently the dev compiler only supports compiling sources with `file:` URIs. To match other implementations, it should support `http:`, `https:` and `data:` URIs as well.

This is blocking dart-lang/test#414, which needs to be able to compile from HTTP to support `pub serve`.

**Comment by jmesserly** [comment]
(marked P1 if it's a blocker)

I can see how data could work, but what is http(s) supposed to do for a command line compiler? I don't see any code in analyzer_cli for it,  and none of those URI schemes seem to work for dartanalyzer (as far as I can tell). If there's some way to make this work in Analyzer I'm all for it. (And probably we should implement it in pkg:analyzer so DDC doesn't need custom logic, and all front ends can get the same URI support...)

**Comment by jmesserly** [comment]
Aside, the idea of a compiler needing to support HTTP is a bit crazy on principle :). But I can see how we got there with our crazy concurrency story :|

**Comment by jmesserly** [comment]
Hey @nex3 did you have thoughts on how we could support this? It didn't look like Analyzer has support for these URI schemes but I may have missed something.

**Comment by nex3** [comment]
I don't really know the internals of analyzer that well... you may have to add support for other URI schemes in its code. Doesn't it have a fairly separate abstraction for reading inputs that you can hook into?

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27266
