### ISSUE TITLE
Allow sources to be provided as a file

### ISSUE THREAD

**Issue by nex3** [dart-lang/dev_compiler#614]
Currently, all sources for a compilation must be provided as command-line arguments. However, if a module contains many sources, it can run up against command-line length limits. This could be avoided by providing an argument that takes a file that contains newline-separated source file names, like `tar`'s `--files-from`. Bonus points if it's possible to provide files via stdin by passing `--sources-from -` or something like that.

**Comment by jmesserly** [comment]
Oh! so it turns out you can supply args via `@file_path` and all of those will be loaded:
https://github.com/dart-lang/dev_compiler/blob/617e3b69a61e6994bfc8eb9e2a807deda52cfd45/bin/dartdevc.dart#L143

I presume we have @jakemac53 to thank for this feature :)

**Comment by nex3** [comment]
Cool! I'll add that to #613.
