### ISSUE TITLE
Static methods do not work on callable classes

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#616]
The following generates an error in DDC:

```dart
class Foo<T> {
  void call(x) {
    print(x);
  }
  static void bar() {
    print('in bar');
  }
}

void main() {
  Foo.bar();
}
```

Here's the error:

```
    callable.Foo.bar();
                 ^
TypeError: callable.Foo.bar is not a function
```

It works fine if the `call` is removed even though that's not invoked in this tests.  It appears that the static function isn't added to the object created by `dart.callableClass`.

**Comment by jmesserly** [comment]
probably this only affects generic classes?

**Comment by jmesserly** [comment]
we'll need to make sure the statics end up on the constructor function. I forgot that we use ES6 statics, so they get added to the ES6 class. But we don't change the constructor function's __proto__ so the statics aren't hooked up. I suspect copying the properties is safest here.

**Comment by jmesserly** [comment]
Huh. It looks like we're supposed to be hooking up the prototype for statics. Very strange.

**Comment by jmesserly** [comment]
Generic callable classes do seem broken however, I'm not able to get either of these two things to work:
```dart
class Z<T> {
  final T value;
  Z(this.value);
  call() => value;
}
main() {
  Function z = new Z<int>(123);
  Expect.equals(z(), 123); // doesn't work

  var zz = new Z<int>(123);
  Expect.equals(zz(), 123); // also doesn't work
}
```

**Comment by jmesserly** [comment]
ideally we could work around it instead of having a critical bug? Anyway, close to a fix for 2 of the 3 problems I found.

**Comment by vsmenon** [comment]
Removing the call appears to work for the app in question, so lowering P1.
