### ISSUE TITLE
Not reifying map literals properly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#621]
This code should throw an exception.  Instead, it prints 23.  We're not reifying the map literal with the right type.

```dart
void foo(Map m) {
  m[23] = 23;
}

void main() {
  Map<String, dynamic> map = {};
  foo(map);
  print(map.keys.first);
}
```

**Comment by jmesserly** [comment]
ouch, yeah: https://github.com/dart-lang/dev_compiler/blob/057a9c8ad213fc51959093f31bfed3ca972a8eab/lib/src/compiler/code_generator.dart#L4971

totally broken. It's only going to reify the type args if they aren't inferred. It should be going to the staticType.

**Comment by jmesserly** [comment]
visitListLiteral by contrast looks correct.

**Comment by vsmenon** [comment]
https://codereview.chromium.org/2211293002/
