### ISSUE TITLE
Custom Element Support

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/dev_compiler#623]
Hello,
I'm trying to make the  [web-components](https://github.com/dart-lang/web-components)  work with `dev_compiler`. I've suceeded in building it but when I try to register an element I get an `IllegalArgument` exception.

I've tracked down the exception to this piece of code in `dart_sdk.js` : 

```
 let interceptorClass = _interceptors.findInterceptorConstructorForType(type);
    if (interceptorClass == null) {
      dart.throw(new core.ArgumentError(type));
    }
``` 

The strange thing is that `findInterceptorConstrutorForType` has an empty implementation and always returns null.

Is custom element registration not yet supported for `dev_compiler` or am I missing something ?

**Comment by vsmenon** [comment]
Not yet - see #521
