### ISSUE TITLE
Call method on functions broken

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#624]
```dart
void bar(Object x) { print(x); }

void main() {
  bar.call(42);
}
```

prints `null` not `42`.

**Comment by vsmenon** [comment]
@jmesserly - this may be somewhat fixed with your recent work - the code above (with analyzer from pub) is generating a `dsend` in main, but apparently that's broken here:

```
  nullaware.bar = function(x) {
    core.print(x);
  };
  dart.fn(nullaware.bar, ObjectTovoid());
  nullaware.main = function() {
    dart.dsend(nullaware.bar, 'call', 42);
  };
  dart.fn(nullaware.main, VoidTovoid()
```

**Comment by jmesserly** [comment]
Shouldn't this be a static call now in Analyzer?

We don't have support on the DDC side yet though, that's definitely true. We'll have to add some support to method invocations to understand "call" on a FunctionType target.

**Comment by jmesserly** [comment]
(... I don't know I'd say this is "broken" ... it was never implemented in the first place :) )
