### ISSUE TITLE
remove "_uncheckedWhitelist" in code_generator

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#629]
see my comment here:
https://github.com/dart-lang/dev_compiler/blob/f39c13e0837e3a884c4309ec18cf36a9d7620dd6/lib/src/compiler/code_generator.dart#L5272

This whitelist is hugely problematic. In addition to the soundness problem it is totally unmaintainable to be hard coding file and method names from a web framework in a compiler. What if they refactor their code? I empathize that we may have hit a tough problem, but this can't be the right solution.

**Comment by jmesserly** [comment]
thanks to @vsmenon for reminding me to file an issue on this

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27255
