### ISSUE TITLE
unittest tests are broken in karma runner

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#631]
as @vsmenon noticed, this seems to have been the case prior to our recent requirejs module change, but the breakage is more obvious now (actually reported as a failure).

Some of these tests (html ones?) are very fragile in Karma because they do a full page refresh and tend to corrupt the HTML page state.

for now I'm disabling these tests but we'll need to investigate them. What may make sense is to switch most of our tests to running in node, which would be a lot more debuggable and easy to isolate. We could then keep a handful of HTML ones.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27261
