### ISSUE TITLE
implicit downcasts in op assign may not be reified correctly

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#632]
I'm fixing https://github.com/dart-lang/sdk/issues/27110, and I discovered these casts are not marked in an unambiguous way, so it's likely we're inserting the implicit cast in the wrong place.

**Comment by jmesserly** [comment]
ah, apparently we get an exception, not a missing cast. Bumping priority, @stereotype441 I'll have a look now. Thanks @leafpetersen for alerting me to this.

**Comment by jmesserly** [comment]
Hmmm, actually I'm going to change how Analyzer marks this so DDC doesn't pick it up. Working on the back end of this change made me notice a few things that were suboptimal about my previous Analyzer CL.

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27254
