### ISSUE TITLE
async_await test is flaky on travis

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#634]
Haven't noticed a local failure, but I'm often seeing this on the bots:

```
[Chrome 55.0.2846 (Linux 0.0.0)  async_await_test_03_multi FAILED[39m
	Not allowed when tests are running.
```

E.g: https://s3.amazonaws.com/archive.travis-ci.org/jobs/156371116/log.txt

**Comment by jmesserly** [comment]
This issue was moved to dart-lang/sdk#27224
