### ISSUE TITLE
make some changes to js_ast to improve output

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#66]
Some that come to mind:
  * change `\n` printing to blocks, so that `if(foo) return bah;` can be a single line
  * add newlines at the end of classes (I think the separation helps)

**Comment by jmesserly** [comment]
regarding:

> add newlines at the end of classes (I think the separation helps)

I tried this, it looked a little off because other top level stuff doesn't necessarily have spacing. we could do a newline before an after, though. Another idea I had was to use ES6 modules, and then they can have better spacing between top level code.

**Comment by jmesserly** [comment]
moved to https://github.com/dart-lang/dev_compiler/issues/425
