### ISSUE TITLE
code doesn't understand some bools cannot be null

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#68]
in particular:
* results of JS calls: `JS('bool', ...)`
* results of many kinds of boolean expressions, e.g. `obj is SomeType` `(x || y) && z` (the result of `x || y` can't be null)

**Comment by jmesserly** [comment]
btw, we have a similar issue with `num` and intermediate values.

**Comment by vsmenon** [comment]
BTW, I have not yet landed my CL to make bool non-nullable - in part because #70 is giving problems in real code (on int and double).

**Comment by jmesserly** [comment]
ah, that explains it :)

**Comment by jmesserly** [comment]
this is almost certainly obsolete
