### ISSUE TITLE
Module names and class names can conflict in generated JS

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#69]
This comes up in DeltaBlue and other benchmarks:

    var BenchmarkBase;
    (function(BenchmarkBase) {
      ...
      class BenchmarkBase extends dart.Object { ... }
      ...

Running this triggers:

lib/src/DeltaBlue/dart/ddc/BenchmarkBase/BenchmarkBase.js:65: SyntaxError: Identifier 'BenchmarkBase' has already been declared

when the class is parsed by v8.

**Comment by jmesserly** [comment]
yeah hoping we can fix this and some related issues via https://github.com/dart-lang/dev_compiler/issues/34: use ES6 modules and have a more sane desugaring

**Comment by jmesserly** [comment]
https://codereview.chromium.org/967713002/
