### ISSUE TITLE
fix checks for dynamic calls

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#7]
Copied from John:
> Consider:
> ```dart
>class M {
>  call(x,y) => x+y;
>}
>main() {
>  M m = new M();
>  print(m(1,2)); // works
>  print(m(1,2,3)); // NoSuchMethodError at runtime. analyzer fails to catch
>  print(m.call(1,2,3)); // analyzer correctly detects this
>}
>```
> This blows up due to wrong number of arguments at runtime. However, I don't see any warnings or errors from dart2js or dartanalyzer.
> DDC does not really catch this either. It is treated as dynamic dispatch and allowed, for some reason, even though we could've caught it statically.

Turns out that in checker.dart we only look at:
```dart
 if (type.isDynamic || type.isDartCoreFunction || type is! FunctionType) { ...
```

we should additionaly check if the type implements `call` and use it's type instead:
```dart
if (type is InterfaceType) {
  var callMethod = type.lookUpMethod("call", _current.library);
  if (callMethod != null) type = callMethod.type;
}
...
```

**Comment by leafpetersen** [comment]
The analyzer seems to have fixed the issue that allows m(1, 2, 3).  There is another bug which seems to cause it to treat the return types incorrectly (dartbug.com/23252).  I have a CL pending which fixes the dynamic dispatch issue.
