### ISSUE TITLE
Implement local initialized-before-read analysis

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#70]
We need this to really do non-nullability.  E.g., if T is non-nullable, we currently complain that x is not initialized even though it's guaranteed to be written before a read:

    T x;
    if (...) {
      x = y;
    } else {
      x = z;
    }
    foo(x);

**Comment by jmesserly** [comment]
this also might be a good checker feature... warn if locals are not definitely assigned to something. C# and Java have forms of this, with C#'s being precise (http://en.wikipedia.org/wiki/Definite_assignment_analysis).

**Comment by jmesserly** [comment]
another thought ... the analyzer probably has this analysis already?

**Comment by vsmenon** [comment]
No, I had asked @bwilkerson about this.  The spec says these are implicitly null, and I believe the analyzer is not supposed to emit a warning regardless.

We could experiment with how often this is actually used in programs though.

**Comment by jmesserly** [comment]
@vsmenon did you have any work in progress on this? else maybe kick it back to unassigned in case someone feels inspired :)

**Comment by chalin** [comment]
FYI, this is on my NNBD Analyzer to-do list (via feature [E.3.6 Reducing the annotation burden for local variables, an alternative](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#local-var-analysis)), though I'm not sure how soon I will get to it. But if you guys implement it first (in a manner that it can be used in/ported to the analyzer) that would be grand :).

**Comment by jmesserly** [comment]
useful but I think this is part of language non-null work now, not DDC. so closing out
