### ISSUE TITLE
Dynamic invocation should support all ES 6 function variants.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#71]
See ES 6 spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function.prototype.tostring

We currently support only FunctionDeclaration and FunctionExpression (in dart_runtime.js).

**Comment by jmesserly** [comment]
or at least the ones we generate :)
which may end up being all of them

**Comment by jmesserly** [comment]
I think this is fixed. We still may want the argument list parsing later on for mirrors.
