### ISSUE TITLE
reuse analyzer's lineinfo where possible

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#73]
reporter.dart uses SourceFile to compute line breaks, but analyzer has already done that on CompilationUnit. We could reuse that info. JS codegen now uses the analyzer-provided linebreaks so perhaps a refactoring

**Comment by sigmundch** [comment]
I played a bit with this, but then realized that its better not to switch entirely off using SourceFile in our reporter for now. Not at least until we can give the same experience were we report errors from the beginning of a line like we do for FileSpans.

We might be able to get there by exporting the line-breaks from analyzer and extending SourceFile to accept a constructor with the line-breaks pre-calculated.... 

or, maybe we can get the analyzer to use `source_span`?

**Comment by sigmundch** [comment]
Ok - the main thing is just to find the preceding line break, which we can do by just scanning the source string backwards from the begin offset.

The second thing we need to do is to define our own Span implementation that mixes the default Span but improves the logic in `message` to include the code from beginning of the line.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1141013002/
