### ISSUE TITLE
add naive in-memory summaries for server

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#76]
Before we have full support for library summaries, we can create a notion of a summary that includes:
 - type + name of public symbols
 - hash for other libraries that are exposed as part of the signature

Overall we'd like to be able to quickly decide whether to rebuild certain files based on summaries from changes in other files.

Here is an example we'd like to support. Given this code:

a.dart:
```dart
import 'b.dart';

main() { new B().c.d.e = 2; }
```

b.dart:
```dart
class B { 
  C c;
}
```

c.dart:
```dart
class C {
  D d;
```

The code generated for a.dart could be like this:
```js
new B().c.d.e = 2;
```

If we change `c.dart` and remove the type `D`, we should recognize that we need to rebuild `a.dart` (even though it doesn't import `c.dart` directly) and generate:
```js
dstore(new B().c.d, "e", 2);
```

Summaries can help by storing in b.dart that it depends on `c.dart`, the hash of `c.dart` changed, so `b.dart` summary is different, and because of that, we rebuild `a.dart`.

**Comment by jmesserly** [comment]
Full summaries are here. We can start using them :)
