### ISSUE TITLE
generate extended class before use

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#78]
`class Foo extends Bar` needs Bar to exist. We can't preserve source order of declarations for cases like this.

**Comment by sigmundch** [comment]
Note that this can be especially challenging for separate compilation in the presence of cycles in library imports. For example, this is valid in dart:

a.dart:
```
import 'b.dart';
class A1 extends B {}
class A2 {}
```

b.dart:
```
import 'a.dart';
class B extends A2 {}
```

which requires that we emit them in order A2, B, A2.

**Comment by jmesserly** [comment]
@sigmundch library cycles are an even bigger issue :) do you want to file that separately? in general, we may need to collapse library cycles into a single output artifact. We have a similar problem with imported names, and I can imagine it shows up in other ways.

**Comment by jmesserly** [comment]
going to work on at least a partial fix here. (but possibly just fixing the whole thing).

**Comment by jmesserly** [comment]
ended up fixing the whole thing: https://codereview.chromium.org/1016003003
