### ISSUE TITLE
Spurious Downcast info messages for const.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#8]
I don't think this code should be generating a downcast. BAR should have static type String.

Repo:
```dart
class Foo {
  static const BAR = 'hi';
}

class Baz {
  String bla = Foo.BAR; // Info: DownCast
}
```

Note this seems to impact all const and final fields. Fixing this bug will fix a large number of the DownCasts.

**Comment by jmesserly** [comment]
@sigmundch is this working now?

**Comment by sigmundch** [comment]
yes, this is now fixed. transitive inference between consts is still in the works though :)
