### ISSUE TITLE
handle library cycles in codegen

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#81]
A big issue we need to handle is cycles in the library imports and references across these libraries. See for example the issue with extending classes in #78.

Some options are:
  * collapsing library cycles into a single output file
  * go the opposite way: break out our current file-per-library to be more fine-grain. This would give the option of combining the output files in an appropriate order when building the HTML output file.

**Comment by jmesserly** [comment]
interestingly, ES6 modules appear to support cycles. So we got that going for us.

**Comment by jmesserly** [comment]
We fixed this a while back. Current solution is okay-ish: library maps to module, and cycles are handled by generating code that is defensive to ordering. We may want to revisit this though, not sure anyone is super happy with the current code readability when cycles are present.

Longer term, I'm leaning towards generating finer grained pieces, and "re-exporting" them. To make that nice, we really want modules. IMO
