### ISSUE TITLE
infer-from-overrides is non-deterministic

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#86]
It appears to depend on ordering of file processing.

I'll disable by default until we fix.

**Comment by sigmundch** [comment]
:-( thanks.

**Comment by jmesserly** [comment]
I think this was fixed, as it's turned back on (was it https://github.com/dart-lang/dev_compiler/commit/97984fa6bd10c8438b9da8af56dc5360a7fa80e6?)
