### ISSUE TITLE
server should recover from errors?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#88]
Currently if we hit an error we report it, we even re run the compiler after errors, but we don't seem to generate code after that. Basically the `failure` detected on a previous request stays persistent and is not cleared on rebuilds.

One issue is that we need to keep track of failures per library in order to correctly assess if we are free of errors at that point.

Other options:
* server turns on `--force-compile` by default
* do library-based force-compile, so failures are not tracked globally when running in server mode.

**Comment by jmesserly** [comment]
we might do this in another tool but not in the modular compiler
