### ISSUE TITLE
add `dart_core.js` to the output

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#89]

**Comment by sigmundch** [comment]
CL out: https://codereview.chromium.org/986023003/

**Comment by sethladd** [comment]
I just tried the latest dev_compiler from git, and `dart_core.js` was not included in my `-o` directory. I only saw `file.js` and `file.js.map`.

**Comment by sigmundch** [comment]
A yes, sorry I didn't follow up here. The compiler currently only works well if you have it as a dependency on your project. That shouldn't be needed though, and I'd like to have a fix for this soon (see #96).
