### ISSUE TITLE
copy dev_compiler runtime even when project doesn't depend directly on dev_compiler

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#96]
Currently we copy `dart_core.js`, `dart_runtime.js`, etc, from a package: url, which only works if the project being compiled has a dependency on dev_compiler itself.

That's unlikely and we should refer to the sources differently:

* if running from sources, we can get it out of the source location
* if running from a snapshot
  * we can determine if the snapshot is within a pub-cache and use that source location
  * long term we need to pre-bundle these sources within the compiler.

**Comment by sethladd** [comment]
How do we know if we are running via a snapshot?

**Comment by vsmenon** [comment]
The versioning observation here is interesting.  If someone directly imports one version of the dev_compiler but runs with a second version, should we give an error or warning?

**Comment by sigmundch** [comment]
Fix on its way here: https://codereview.chromium.org/1013363002/

@sethladd  - I currently detect a snapshot only if the snapshot was generated by `pub global activate` in which case the filename ends with `.dart.snapshot` and is located under `.pub_cache/global_packages/package_name/dev_compiler/bin/devc.dart.snapshot`.

@vsmenon - good point, we could, but not sure if its necessary until we have something that users will import from the dev\_compiler package into their code. For now, it seems that as long as the compiler uses a runtime that is consistent with itself, we should be good.
