### ISSUE TITLE
dynamic dispatch for operations on Object

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#98]
e.g.
```dart
stringify(obj) => obj.toString();
```

At least, `dynamic` and `Object` should be treated the same ... there's legit question about how to call `runtimeType` and `hashCode` which JS Objects don't have.

**Comment by vsmenon** [comment]
Two parts to this: 
1. Treat dynamic and Object the same for operations on Object.
2. Treat Object operations specially in the JS backend (for runtimeType and hashCode on primitives and other JS objects).

**Comment by vsmenon** [comment]
This should be fixed now.
